### ISSUE TITLE
OpenAPI Alternate Schema Support

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/ogcapi-features#129]
The OpenAPI TSC is considering an extension to the spec which will allow an API definition to identify multiple formats for a response (see OpenAPI Issue 1532).  This extension should be useful for WFS 3.0.  Please review and provide comments.

Here is an example:  

[AlternateSchemaExample.txt](https://github.com/opengeospatial/WFS_FES/files/1946931/AlternateSchemaExample.txt)

**Comment by cmheazel** [comment]
The OpenAPI TSC has decided to make proposed extensions to OpenAPI publicly available.  The categories for these extensions are:
- draft:proposal - we’re still hashing out the details
- draft:pilot - go ahead and implement it
- draft:graduated - we’ve seen the implementations, it will go into the next minor/major release
- draft:abandoned - didn't succeed, do not use
First in the queue for draft:pilot is Alternate Schema.

**Comment by cmheazel** [comment]
The AsciiDoc for the alternative schema addition to OpenAPI is [here](https://github.com/opengeospatial/WFS_FES/files/2272529/Alternative.Schema.txt)

**Comment by cportele** [comment]
Looking at the issue in the OpenAPI repo, the discussion is still ongoing. I would say we wait for the publication by OAI as draft:pilot or higher before we update the GML application schema example in the Core.

**Comment by cportele** [comment]
06-MAY-2019 Conference call: TSC is working on the pull request to publish on OpenAPI GitHub. Once it is available Clemens will update the example.

**Comment by cportele** [comment]
Move it to an extension.

**Comment by cmheazel** [comment]
Pull request #256 partially addresses this issue.
