### ISSUE TITLE
extent.bbox not consistently described among files

### ISSUE THREAD

**Issue by rouault** [opengeospatial/ogcapi-features#259]
/core/openapi/ogcapi-features-1.yaml describes well the situation where there are 6 values, but /core/openapi/schemas/extent.yaml and /core/standard/clause_7_core.adoc are lagging behind.

**Comment by rouault** [comment]
Actually, there's an apparent duplication of information in ogcapi-features-1.yaml
bbox is described in https://github.com/opengeospatial/ogcapi-features/blob/32ef4ad28129a15cab4950f17861d324e593c097/core/openapi/ogcapi-features-1.yaml#L19 and  https://github.com/opengeospatial/ogcapi-features/blob/32ef4ad28129a15cab4950f17861d324e593c097/core/openapi/ogcapi-features-1.yaml#L202 . In case the duplication isn't justified, having a single source of truth would seem to be better.

**Comment by cportele** [comment]
This is not a duplication. One is the query parameter on /collections/{collectionId}/items and the other is part of the extent schema in the collection resource (/collections/{collectionId}). 

I will have a look and see, if we can update/consolidate the schema/description at this stage in the process, i.e. before publication. This might be possible as it would be an editorial change.
