### ISSUE TITLE
Weird convention for extent.bbox with 6 parameters

### ISSUE THREAD

**Issue by rouault** [opengeospatial/ogcapi-features#260]
/core/openapi/ogcapi-features-1.yaml mentions
```
        * Lower left corner, coordinate axis 1
        * Lower left corner, coordinate axis 2
        * Lower left corner, coordinate axis 3 (optional)
        * Upper right corner, coordinate axis 1
        * Upper right corner, coordinate axis 2
        * Upper right corner, coordinate axis 3 (optional)
```
Regarding the Z axis, it seems a bit useless to take the elevation precisely at the LL and UR corners. I guess what people really want is the minimum and maximum elevation of the geometries over the whole collection.

**Comment by cportele** [comment]
This is of course what is meant. In 3D the bbox is a box, not a rectangle.

I will check, if we can update the wording at this stage in the process to make that clearer.

**Comment by cportele** [comment]
@rouault @pvretano 

I have created a pull request, #263. Could you check, if this would be clearer?

As an aside, out of interest I had a look at GeoJSON and their wording has a similar ambiguity/confusion ([link](https://tools.ietf.org/html/rfc7946#section-5)):

> The value of the bbox member MUST be an array of length 2*n where n is the number of dimensions represented in the contained geometries, with all axes of the most southwesterly point followed by all axes of the more northeasterly point.
