### ISSUE TITLE
URIs of conformance classes are inconsistent

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ogcapi-features#269]
The specification uses two different URI patterns for conformance classes:
* `http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/*` (29 occurrences)
* `http://www.opengis.net/spec/ogcapi-features-1/1.0/req/*` (12 occurrences)

Which pattern is correct? The specification should be updated according to the answer.

**Comment by cportele** [comment]
@dstenger - Except in one place (a separate JSON example file), both URI patterns are correctly used. "conf" is used for conformance classes, "req" for requirements classes. See the OGC modular specification policy document and the OGC Naming Authority URI scheme. Requirements classes aggregate the requirements (these are used in clauses 7/8/9) and conformance classes aggregate test cases and are used in clause 2 and annex A. The conformance declaration is about conformance classes and therefore uses the conformance class URIs. The spec document is consistent with all this as far as I can tell. If not let me know where an incorrect URI is used.
