### ISSUE TITLE
Issues with CRS linking in Part 2

### ISSUE THREAD

**Issue by rouault** [opengeospatial/ogcapi-features#274]
Part 2 currently mentions : "Rather the global list of CRS identifiers must be explicitly referenced in the collection metadata using a JSON link."

1) "JSON link" would make think of https://tools.ietf.org/id/draft-wparad-json-links-02.html, which is more or less what is used for the "links" property of Part-1, whereas here it is a different mechanism, which should probably be "JSON reference" https://tools.ietf.org/html/draft-pbryan-zyp-json-ref-03 

2) The examples have type where #/crs is used without double quoting. But even "#/crs" would no be compliant with JSON reference. Should rather be { "$ref" : "#/crs" }

**Comment by cportele** [comment]
I think the underlying standard is or at least should be [JSON Pointer (RFC 6901)](https://tools.ietf.org/html/rfc6901). Correct @pvretano? "JSON link" is unclear and needs to be changed.

And yes, the value is a string and needs to be in double quotes.

A value "#/crs" would then seem to be correct, if we require that each value in the `crs` array is a URI, identfying either a single CRS or another CRS array (using JSON Pointer for the fragment).

Alternatively we could use JSON Reference and then would allow something like the following instead.

````
"crs": [
          { "$ref": "#/crs" },
          "http://www.opengis.net/def/crs/OGC/1.3/CRS41001",
          "http://www.opengis.net/def/crs/OGC/0/2246",
          "http://www.opengis.net/def/crs/OGC/0/3130",
          ...
       ]
````

Any views what is easier to handle by clients?

**Comment by cportele** [comment]
Discussed in 2019-10-28 call: keep this as an open issue, we need more input whether we use "just" JSON Pointer or JSON Reference. Maybe we should also restrict it to a local pointer within the same document.

**Comment by cportele** [comment]
Meeting 2020-05-11: Since we have not received other feedback we keep the current style, but restrict it to the local pointer.
