### ISSUE TITLE
CORS issue on schema locations

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-features#275]
When trying to reference directly against schemas.opengis.net, there is a CORS error:

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing).

Context is providing an OpenAPI document with refs like `"http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/ogcapi-features-1.yaml#/components/responses/LandingPage"`

**Comment by cportele** [comment]
@gbuehler, @kstegemoller 
Would it be possible to add support for cross origin requests on schemas.opengis.net (at least for everything in http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/)?

**Comment by tomkralidis** [comment]
Note that the context is a webapp (like Swagger) rendering an OpenAPI document which references YAML things in http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi

**Comment by kstegemoller** [comment]
http://schemas.opengis.net/ogcapi/ now has CORS header set to "Access-Control-Allow-Origin: *"

**Comment by tomkralidis** [comment]
Looks like this work, thanks @kstegemoller.

Aside: are there any plans to provide schemas.opengis.net via HTTPS?  I can open a (new) issue elsewhere if that helps.

**Comment by kstegemoller** [comment]
Opened Issue #276 about providing HTTPS
