### ISSUE TITLE
Collection extent properties not required?

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/ogcapi-features#278]
As far as I understand the specification, the spatial and temporal extents in Collections are required.

Unfortunately, the corresponding OpenAPI fragment doesn't require them: http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/extent.yaml

It is specified as follows:
```json
    extent:
      type: object
      description: |-
        The extent of the features in the collection. In the Core only spatial and temporal
        extents are specified. Extensions may add additional members to represent other
        extents, for example, thermal or pressure ranges.
      properties:
```

but should be:
```json
    extent:
      type: object
      description: |-
        The extent of the features in the collection. In the Core only spatial and temporal
        extents are specified. Extensions may add additional members to represent other
        extents, for example, thermal or pressure ranges.
      required:
        - spatial
        - temporal
      properties:
```

**Comment by cportele** [comment]
The spec states that the extent information (spatial and/or temporal) is optional. An extent should be provided for collections where they apply to support clients, but they are not strictly required. Some quotes, the bolding is mine:

> Requirement "/req/core/fc-md-extent":  For each feature collection, the extent property, **if provided**, SHALL provide bounding boxes that include all spatial geometries and time intervals that include all temporal geometries in this collection. The temporal extent may use null values to indicate an open time interval.

> An **optional** extent that can be used to provide an indication of the spatial and temporal extent of the collection - typically derived from the data

In other words, the lack of "required" values is intentional and consistent with the normative statements and the text.

Clients should be prepared to have no extent information for a collection.

Other specs building on Features Core can of course make extent information required for their APIs.

**Comment by m-mohr** [comment]
@cportele Thank you for the explanation, but I understand the requirement differently: You can choose to either not provide the extent field at all OR you **shall** provide spatial and temporal properties.

So this is valid (no extent):
```json
{
  id: "123",
  ...
}
```

This is invalid:
```json
{
  id: "123",
  extent: {}
}
```

This is valid:
```json
{
  id: "123",
  extent: {
    spatial: {...},
    temporal: {...}
  }
}
```

**Comment by cportele** [comment]
No extent or an empty extent are basically the same thing. I do not think that the spec specifies any distinction between these two representations?

Also note that an extent that just has a "temporal" member would be valid, too.

**Comment by cportele** [comment]
OK, on second reading I see where you are coming from with the current wording. I think that we should clarify the wording of the requirement in a future revision. 

Any other thoughts?

**Comment by m-mohr** [comment]
Probably not very good code, but:
```
if (typeof obj.extent === 'undefined') // no extent
else console.log(obj.extent.temporal.interval, obj.extent.spatial.bbox); // I would expect that and it would fail
```

That's where I'm coming from. ;-)

We require extent in STAC anyway, but I was just quite confused about the OAF OpenAPI Schema when doing the alignment with STAC API.

**Comment by cportele** [comment]
Yes, but a generic client should always check, if "spatial" or "temporal" is present in an "extent" and not assume that one is available if "extent" is provided. "spatial" really only makes sense, if the features in the collection have a spatial geometry. Same for "temporal" and a temporal geometry (instant, interval) in the features.

**Comment by m-mohr** [comment]
Good to know, thanks. Looking forward to the clarification in the docs.

**Comment by m-mohr** [comment]
@cportele I stumbled across another thing:

* In the temporal object, the interval field is not required although it feels like it should, because minItems is set to 1.
* In the spatial object, the bbox field is not required although it feels like it should, because minItems is set to 1.

Is that correct?

**Comment by cportele** [comment]
@m-mohr: I think we could have set `bbox` and `interval` as required properties of `spatial` and `temporal` respectively. The only reason for not making them required would be to allow future extensions that use something else than a bbox/interval to describe the spatial/temporal extent.
