### ISSUE TITLE
Search for collections missing?

### ISSUE THREAD

**Issue by uvoges** [opengeospatial/ogcapi-features#281]
Hi,
I read the OGC API-Common spec (27.10.2019) and didn't find covered the use case to search for collections (...in case of hundreds or thousands of collections). I just saw the possibility to search for items within a collection or to navigate through all collections.
Thanks, best regards, Uwe

**Comment by cportele** [comment]
If it is a comment on Common, maybe open an issue there?

Regarding the behaviour in Features: For the core we decided to not specify such a mechanism as most APIs won't have that many collections. But we have normative statements in there to support pagination and/or filtering in an implementation or in a standard extension. See http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#per_core_fc-md-items and #76.

**Comment by cportele** [comment]
An issue has been opened in the Common repo: https://github.com/opengeospatial/oapi_common/issues/69.

I am closing this issue here.
