### ISSUE TITLE
DELETE in simple transactions

### ISSUE THREAD

**Issue by elpaso** [opengeospatial/ogcapi-features#292]
A question about DELETE: the preliminary specs do not say anything about the response content, is that supposed to be empty?
Maybe we should also set the Location to the parent (items) url.

**Comment by cportele** [comment]
2020-08-16: Yes, response content is supposed to be empty. The response should be a `204` (standard case of immediate deletion) or a `202` (queued for deletion) and have no content. We do not see why a Location header should be added or what purpose it would serve.

**Comment by cportele** [comment]
Thanks, that sounds like a good point. I will check what is good practice and if it good practice, I will add this.

**Comment by cportele** [comment]
@elpaso - I had a look and did not find any evidence that including a `Location` header in the response to a successful DELETE request is "standard practice in web applications". In fact, I did not find any example where this is done. Could you provide more information where this is used?

Perhaps as importantly, the [definition of the header in the HTTP RFC](https://tools.ietf.org/html/rfc7231#section-7.1.2) only discusses the header in the context of 201 (created) and 3xx (redirects) responses.

I agree that such a link is useful and we should allow that APIs provide it, but it seems to me that it should be in the payload, if provided.

**Comment by cportele** [comment]
Meeting 2020-09-14: We do not want to prevent such a behavior (maek sure that the wording does not do it), but if it is not common practice we should not recommend it.

**Comment by cportele** [comment]
2021-01-18: @cportele will check that a 204 is returned (or 200 or 202, and explain when which one is to be used) and close the issue afterwards.
