### ISSUE TITLE
part 2 : requirements 7 and 12 (bbox-crs and crs values)

### ISSUE THREAD

**Issue by dsarafinof** [opengeospatial/ogcapi-features#294]
Current draft for part 2 proposes req 7 (/req/core/fc-bbox-crs-valid-value) and req 12 (/req/core/fc-crs-valid-value); both requirements seem to apply to the client (structure/content) of the request, not to the server/web api.

I totally understand the constraint of these parameters, but this should be formulated as how the server shall behave on the differents situation (valid or invalid content of the request). 
Thinking of the test related to these (req 7 & 12) this would end up on a test on the request that is not a reponsability of the server.

**Comment by cportele** [comment]
The intention is a requirement on the API (if the value is not one from the list of CRSs then the server needs to return a 400 response, see req 9 `/req/core/query-param-invalid` in Core). Maybe they should be reworded to make that clearer.

**Comment by cportele** [comment]
Meeting 2020-05-11: Reword as discussed to make the requirement on the server implementation clear.
