### ISSUE TITLE
License recommendation in Core

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-features#299]
There seems to be a mistake in the recommendation regarding the license: the recommendation says

> [...] include an item for each supported encoding [...]

but that should be a link to a license.

**Comment by cportele** [comment]
Meeting 2019-11-25:  The updated wording is fine and probably easier to read. The change is editorial. We will keep issues and PRs like this open until a future update of the standard and tag them accordingly. Such a future update may be bugfixes or editorial aligment with ISO 19168-1 or OGC API Common. 

Note: The text of the recommendation is correct as it is. "the `links` property should include an item" is the same as "the `links` property should include a link" - the value of the `links` property is an array.
