### ISSUE TITLE
Core: description of status code 406

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-features#303]
A server could also return status code 406 Not Acceptable when the language negotiation (mentioned in 7.10. String internationalization) or the content negotiation based on `Accept-Charset` or `Accept-Encoding` fails.

I would like to see a more general description of 406.

F.eks.:

Content negotiation failed. For example, the `Accept` header submitted in the request did not support any of the media types supported by the server for the requested resource.

**Comment by cportele** [comment]
Meeting 2019-11-25:  Agreed. This is something that should be addressed in OGC API Common (once we reference Common, the table will likely be removed from the Features document).

**Comment by cmheazel** [comment]
@heidivanparys API Common has been updated using your text.
