### ISSUE TITLE
Core: example 4

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-features#306]
A suggestion for a minor editorial change: example 4 could be updated to have an explanation regarding all links present.

![image](https://user-images.githubusercontent.com/11427611/69555148-01a68e80-0fa3-11ea-84c0-55016c4d046f.png)

**Comment by cportele** [comment]
Meeting 2019-11-25:  Same as #303.

**Comment by cmheazel** [comment]
This change has been made to API-Common
