### ISSUE TITLE
Core: Req 12 from the modular spec

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-features#309]
It seems that the specification does not follow requirement 12 from the OGC modular specification:

> A Conformance class shall specify any other conformance class upon which it is dependent and that other conformance class shall be used to test the specified dependency.

E.g. for Conformance Class GeoSJON: it does not contain a test saying sth like "A Web API passing the  Conformance Class GeoSJON shall first pass the Conformance Class Core" and the conformance class does not declare a dependency on Conformance Class Core either. So it you would give only the Abstract Test Suite to a developer that has to write an Executable Test Suite, the dependencies wouldn't be reflected (unless that developer reads the spec itself from start to end 😉, where the dependencies for the requirements classes are declared).

![image](https://user-images.githubusercontent.com/11427611/69612254-9fe03600-102f-11ea-90e7-273d94c14f90.png)

**Comment by cportele** [comment]
Yes, I agree. The dependencies should be in the CC tables, too.

@ogcscotts - I think this is a defect in the OGC standards template. Dependencies are part of the req class template, but there is no equivalent for the abstract tests.

**Comment by cmheazel** [comment]
@cportele The conformance class tables are not a part of the template. So we can't yell at @ogcscotts about that one. The November 29 PR for API-Common (mentioned in #301) will include the addition of dependencies to the ATS CC tables and explicit requirements and tests for conformance with all dependencies.

**Comment by cportele** [comment]
I am not yelling :) I was just pointing out that while we have templates for requirements and requirements classes in the template, such templates do not exist for the tests and should be added.

**Comment by cmheazel** [comment]
@cportele why have OGC staff if we cannot yell at them? :) 
The ATS template is in annex-a.adoc. Yes, we have greatly expanded what the template supplies. An yes, we should submit these changes to Scot to include in the template.

**Comment by ogcscotts** [comment]
@cportele @cmheazel non-yelling heard. Looks like we need an update to the template. I'll do so in the coming weeks.

**Comment by cmheazel** [comment]
@serich no rush. We'll hash out these issues in API-Common. When we are done, you will have an example to build on.

**Comment by ogcscotts** [comment]
@serich don't worry about this one, it was meant for @ogcscotts ! Get back to your vacation.

**Comment by cmheazel** [comment]
In today's API-Common update: Dependencies between Requirements Classes are identified in the Requirements Class table.  Dependencies between Conformance Test Classes are identified in the Conformance Test Class table.  Each Conformance Test Class table identifies the Requirements Class that that Conformance Test Class is testing.
