### ISSUE TITLE
Confirm whether Requirement 12 to 15 have URIs beginning with /req/core/

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-features#313]
This came up during the OGC API - Coverages SWG telecon on 2019-12-18.

Requirements 12 to 15 have URIs beginning with `/req/core/`. Is this intentional or perhaps they are typos that should be corrected to `/req/crs/` ?

**Comment by cportele** [comment]
This refers to http://docs.opengeospatial.org/DRAFTS/18-058.html, correct? 

It is a copy/paste error, it should be `/req/crs`! Thanks.
