### ISSUE TITLE
Global CRS list could be placed in its own resource

### ISSUE THREAD

**Issue by aaime** [opengeospatial/ogcapi-features#315]
Putting the global list of all supported CRSs in the collections resource could cause that resource to grow by a significant amount, especially if the server supports lots of potential target CRSs.

For example, GeoServer by default allows to reproject in all the ones supported by the local EPSG database, eventually failing to do the reprojection when requested.
Client that are not interested in the CRS extension would have to get that list anyways.

May I suggest to place that list in a dedicated resource instead, for example "serviceRoot/crs"?

**Comment by pvretano** [comment]
@aaime, sure.  I don't think I have a problem with this proposal.

**Comment by cportele** [comment]
Agreed. Just to note that this would have an impact on #274 as in that case the references could not be restricted to a pointer within the document.

**Comment by pvretano** [comment]
@cportele So, we would use a full URL to reference the resource rather than an internal pointer; I can't think of any problems with that.  Do you see any issues?

**Comment by cportele** [comment]
@pvretano - no problems per se, but more options that the clients need to support (richer pointer syntax, fetching a remote resource)

**Comment by cportele** [comment]
Meeting 2020-05-11: The problem with `/crs` is that at this point the global list of the CRSs for the feature collections, but not necessarily for other resources like coverages or tile sets. We, therefore, believe that the global list needs to be part of the collections resource.

**Comment by aaime** [comment]
Not sure how to read it. Does that mean it would be in a different place, or fully repeated for each collection?

**Comment by cportele** [comment]
The global list is in `/collections`, not in every collection in the collections resource. See http://docs.opengeospatial.org/DRAFTS/18-058.html#example_1

**Comment by aaime** [comment]
Ah right sorry, now I remember! Pity for how large the collections resource might grow, but ok.
