### ISSUE TITLE
Review Comments (C. Reed) for CRS Part 2

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-features#319]
**DOCX with review comments:** https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/crs/review/Review_Comments_Part2_CReed.docx

**C. Reed (2019-12-31):**
Attached is my initial review of the Features API Part 2 - CRS. I have provided a number of suggested minor edits. A number of the edits have to do with shortening "coordinate reference systems" to "CRS".

My main issue is that a number of concepts and terms are used but not defined in Part 2. An example is collection metadata. So I checked Features API Core. Concepts and terms are used but some not until the ATS. Perhaps these concepts and terms - such as collection metadata - are defined in the new Common API. The solution is simple but perhaps time consuming - add links from Part 2 (and the core) to where these things are defined.

Also, I have a question regarding the ability (need?) to have multiple CRSs specified for a feature collection. I am not sure if this is necessary. I would think that typically a client would ask the server to return all features requested in a specified CRS and not in multiple CRSs. That said, I could not determine how a CRS is "linked" to the feature set in a feature collection that have that CRS.

**@pvretano (2019-12-31):**
I'll review the terms you have highlighted and make sure that they are either defined or reworded to align with core.
I think I may need to reword this bit because it is clear that the intent is not well described if this is what you got from the document! 
Which CRSs is used to store features in the server's data store is irrelevant as far as the extension is concerned; it could be that features, in the database, are stored in multiple CRSs.
The extension is only concerned with which, single, CRS is used to present features in a response document. 
If a client requests features (i.e. GET /collections/{collectionId}/items[?...]) without specifying any CRS then they will get the features in the default CRS specified in the core (i.e. CRS84).
Otherwise the client may specify a CRS to be used for presentation in a response document using the "crs" parameter (i.e. GET /collections/{collectionId}/items?...&crs=blah&...).  Valid values for the CRS parameter for the specified feature collection are listed by the server in the "crs" array in the collection metadata (i.e. the document you GET at /collection/{collectionId}).  See the example on Page 9/10 of the word document you attached.
In all cases, the server is responsible for transforming the features from whatever storage CRS is being used to the requested presentation CRS.
I hope this clears up the intent.

**@cportele (2020-01-01):**
On the use of "collection metadata": This is outdated language that is used in some cases in part 2. The resource names that so far are standardized in OGC API Features are

* Landing page (/)
* Conformance declaration (/conformance)
* Feature collections (/collections)
  * Feature collection (/collections/{collectionId})
    * Features (/collections/{collectionId}/items)
      * Feature (/collections/{collectionId}/items/{featureId})

See http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#tldr or http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#core-overview.

"collection metadata" was in earlier drafts sometimes of the Core used for (/collections/{collectionId}), but this is/was incorrect, the resource is the collection. Yes, a GET on the resource will fetch a document that mainly contains metadata about the collection, but that is an implementation choice as immediately returning the features (collection items), too, does not match the usual workflows, especially if there are more than just a handful of features in the collection. This is why sub-resources are available for each collection to enable clients to fetch the parts of the collection they need.

**Comment by cportele** [comment]
Meeting 2020-05-11: @pvretano will address the edits and get back to Carl and/or the SWG, if needed.
