### ISSUE TITLE
build instructions?

### ISSUE THREAD

**Issue by cholmes** [opengeospatial/ogcapi-features#322]
Perhaps I'm just missing it, but I can't seem to find clear instructions on how to build the html page from the various adoc fragments here.

If the instructions are somewhere let me know and I'd be happy to make a PR to update the readme to link to it. Or if someone wants to just tell me how to do it in this ticket I can likely update the readme myself with a 'building' section.

**Comment by cportele** [comment]
In general, there is no need to build the HTML yourself, this is done nightly for the Editor's drafts (master branch).

* Part 1: http://docs.opengeospatial.org/DRAFTS/17-069r4.html
* Part 2: http://docs.opengeospatial.org/DRAFTS/18-058.html

This is controlled by https://github.com/opengeospatial/ogcapi-features/blob/master/asciidoctor.json, which also specifies the parameters passed to asciidoctor.

Since we don't really need the extra parameters at this point you can create a HTML for part 1 simply with `asciidoctor core/standard/17-069.adoc`.

**Comment by cholmes** [comment]
Ok, cool. I think it's worth putting in a line or two in a 'building' section, that just says 'install asciidoctor' and run 'asciidoctor core/standard/17-069.adoc'. 

And yeah, I'm psyched that the html is built every night, but it's still good practice for a repo to explain to people how to build it. Indeed I started with Tiles which does not have an nightly build afaik.

**Comment by lieberjosh** [comment]
There is one more bit to the recipe, which is that each chapter or section file needs to be referenced in the base document, e.g. [17-069.adoc](https://github.com/opengeospatial/ogcapi-features/blob/master/core/standard/17-069.adoc)

**Comment by cportele** [comment]
I will add build section for this repo.

And no idea why Tiles/Maps/Common/Processes don't use the nightly builds. Coverages does, but the others have broken asciidoctor.json files that do not point to the adoc file.

**Comment by cholmes** [comment]
Just did a quick PR for it. Feel free to tweak / do your own.

And yeah, I would love nightly builds for all of them. @ogcscotts - any insight why those don't yet have builds?

**Comment by cportele** [comment]
Thanks for the PR, @cholmes. I will tweak it a bit to add information for the additional parts and point to the nightly drafts on the OGC website.

**Comment by cmheazel** [comment]
You only get a nightly build if you ask Greg to set it up.  In the case of Common, I do the builds as-needed so we haven't asked Greg to automate it.

**Comment by cmheazel** [comment]
The build tools are not trivial.  It took me a bit of time to run down the dependencies and configure the necessary software.  The second time was much easier.  Unfortunately I didn't document the process.  Maybe we should.

**Comment by cportele** [comment]
@cmheazel 

if you add a file `asciidoctor.json` to the OGC API Common root directory with the following content and send an email to Greg you should be all set with the daily builds.

````
{
        "0":  {
                "OGC_doc_number": "19-072",
                "urn":"http://www.opengis.net/doc/IS/ogcapi-common-1/1.0",
                "title":"OGC API - Common - Part 1: Core",
                "path":"standard/OAPI_Common.adoc",
                "options": ["--trace"]
        }
}
````
