### ISSUE TITLE
Changes to core.xsd

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-features#327]
There are a couple of places where core.xsd deviates from the JSON version of the same information and so I am going to make the following changes to core.xsd

1. Make the **version** attribute in **core:BaseResponseType** optional.  The core has no real concept of versioning and so I think it is unclear what the attribute means.  Alternatively we could include text is the specification that says something about the version attribute; perhaps that it is the version of the standard document? ... although that information is also conveyed by the namespace.
2. Current the **core:Collection** element is a child of the **core:Collections** element which means that the response to /collection/{collectionId} would be invalid if the root element was **core:Collection** (as it should be).
3. Add **core:ItemType** to the collection which was missing.
4. Make the **service** element in **core:BaseResponseType** optional and don't fix its value so that other API specifications that want to use XML can do so.
5. Bump the version of the schema document to 1.0.1(?)

If anyone has any objections to these changes let me know.  If anyone has other changes that I should make too, let me know that too -- now is your change! ;)

**Comment by cportele** [comment]
This change should be done with the planned 1.0.1 corrigendum. 

Regarding item 2: This is in conflict with the spec, which requires the response to be 

> `core:Collections`, with just one entry for the collection `collectionId`

See http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#table_3

I will look at the other changes later or tomorrow, but I would suggest you create a PR that everyone can review first.

**Comment by pvretano** [comment]
In JSON, for the /collections/{collectionId} response, we don't return an array with a single collection object ... right?  That seems a little inconsistent no?
As for a PR, I use git from the command line so I don't know how to do PR's.  It that even possible from the command line?

**Comment by cportele** [comment]
Maybe, but we obviously did a conscious decision at the time (maybe there is a reason documented in the comments, but I don't remember) and we cannot change it now as it would break implementations.

**Comment by pvretano** [comment]
Applied changes 1, 3, 4 & 5 and added crs list to align with the JSON version.  See:
https://github.com/opengeospatial/ogcapi-features/commit/758571d0618f7fe2eb2e71dcfabc320a66a4ce9b#diff-f2b0c0225b654b459d31a7b8a41c0abe
