### ISSUE TITLE
What should deleting a non-existing feature do?

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-features#328]
Should 'DELETE /collection/{collectionId}/items/{featureId}' return a 404 or 200 if the featureId does not exist?  Right now Simple Transactions says nothing about this but is should say something.

**Comment by cportele** [comment]
Meeting 2020-02-17: 

* If it is deleted without a response payload, you should get a 204. If the feature does not exist, return a 404.
* Just allow any valid 2xx response in accordance with the HTTP RFC and have examples with 204/202/200. Note: 202 = the server will delete it later; 200 = the server returns some content

**Comment by cportele** [comment]
2020-08-16: @pvretano will update the document, since there were no further comments.

**Comment by cportele** [comment]
While working on #504, I left this a bit more open, because I did not see much harm in doing so (the end result is always the same, there is no feature) and some seem to have a strong interpretation of "idempotent" and think repeated DELETE requests should return the same response status.

> Note that if no resource with the identifier exists in the collection, the server can respond with a success status (`200` or `204`) or with a not-found exception (`404`).

For discussion...

**Comment by cportele** [comment]
Meeting 2021-02-01: We will keep this open and look for more feedback. 

Security considerations may have a place here, too. @cmheazel will look at this.

**Comment by jampukka** [comment]
Do note that Replace is currently required to return `404` if the feature doesn't exist by `/req/create-replace-delete/update-put-rid-exception`. What should be returned if the collection in `DELETE /collections/{collectionId}/items/{featureId}` doesn't exist? I'm guessing that's should be `404` but one could argue the end result is the same, the resource to delete no longer exists.

**Comment by cportele** [comment]
> What should be returned if the collection in DELETE /collections/{collectionId}/items/{featureId} doesn't exist? I'm guessing that should be 404 but one could argue the end result is the same, the resource to delete no longer exists.

In practice there is probably not much difference, but I think a `404` is the adequate response in this case. It will also be a `404` on repeat requests.

**Comment by jampukka** [comment]
Should there be a difference between `DELETE /collections/{c}/items/{featureId-that's-been-deleted}` and `DELETE /collections/{c}/items/{featureId-that-never-was}`? Same question applies to the previous question about the collection not existing (anymore or ever).

The point of these questions is to better understand and explore the `204` way and the edge-cases involved. Currently I can't tell if leaving it open is problem-free.

**Comment by MTachon** [comment]
Making a difference between `DELETE /collections/{c}/items/{featureId-that's-been-deleted}` and `DELETE /collections/{c}/items/{featureId-that-never-was}` would require server implementations to keep a record for all deleted features. May be much for often updated collections on servers that run for a long time.
