### ISSUE TITLE
How should PUT operate?

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-features#329]
The Simple Transactions extension does not allow PUT to create new features since assignment of feature ids is up to the server.  Given this, how should PUT behave?  Should it behave at it is now specified, return a 404 if an non-existent feature id is specified OR should it behave as specified in the HTTP specification in this regard.  That is, it should create a new resource with the feature id specified by the client.  There is another alternative I believe as well; the server could accept the request, create a new feature, assign a new feature id and the return a 301.

**Comment by jvanulde** [comment]
Should return a 201 with the location header set to the new resource.

**Comment by pvretano** [comment]
@jvanulde returning a 201 assumes that the server accepts whatever featureId the client provides.  That might be a problem for some systems like those that facade WFS 2.X servers which mandates that the featureId used to retrieve the feature is assigned by the server.  In this case, a 301 would be more appropriate and this situation is described in HTTP RFC (2616 or whatever obsoletes it).

Anyway, we discussed the issue at yesterday's SWG teleconference (17-FEB-2020) and it was decided that we would circle back on the PUT description and make sure it behaves as described in HTTP RFC  There was also some discussion about the use of conditional headers and so we need to looks at that too.

**Comment by cportele** [comment]
2020-08-16: There is a use case for client specifying the feature id, so we need to support both options (an API that only supports POST and always assign the id and an API that supports client specified ids using PUT). We need separate requirements classes for this. @pvretano will address this.

**Comment by cportele** [comment]
Meeting 2021-01-18: We have second thoughts about allowing PUT to create features with a client generated `featureId`. Like in WFS it should be the server that decides about the feature identifier. How servers determine the `featureId` of a new feature is up to the server (and it may use feature properties for this). Features may also have other identifiers as properties that can be used in queries.

**Comment by cportele** [comment]
Meeting 2021-02-15: The current version is clear about the behaviour of POST, PUT and PATCH, so we think the issue can be closed. See also #478.
