### ISSUE TITLE
CQL BNF does not support double quoted identifiers

### ISSUE THREAD

**Issue by aaime** [opengeospatial/ogcapi-features#332]
From the catalog 3.0 BNF:

```
<regular identifier> ::= <identifier body>
                     | <double quote> {unicode_character} <double quote>[16]
```

The [16] is a footnote with the following description:

>  This change is inspired in SQL in order to accept local character sets as property name. Moreover, it resolves the clash problem between cql keywords and property names.

GeoServer CQL implementation supports double quoted identifiers for this very reason, avoid clashes and deal with special characters that might have been used a part of an identifier (relationa databases seems to allow pretty much anything in column names, as long as the name is double quoted).

**Comment by cportele** [comment]
2020-08-03: @pvretano will review this and we will get back to it afterwards. The question is whether we want to support such identifiers in CQL. This has an impact on queryables and their representation, too. Are we making life of everyone just more complex? We probably need more feedback from implementers, perhaps keep this open in the public review and explicitly ask for feedback.

**Comment by cportele** [comment]
Meeting 2020-11-23: It has been added to the BNF (or more correctly the text encoding), but it is unclear if/how to add it to the JSON encoding. This makes sense and we will leave it at that and wait for any comments.

**Comment by cportele** [comment]
Reopen for review in SWG meeting on 2020-12-07
