### ISSUE TITLE
CQL: existence operators

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-features#335]
The current BNF has the following:

````
#=============================================================================#
# The existence predicate evalues whether the specified property exists
# in the current context. This predicate was added to accomodate the fact
# that OAPIF feature collections (and likely other specification) are
# heterogeneous with respect to schema.
#=============================================================================#
existencePredicate = propertyName "EXISTS"
                   | propertyName "DOES" "NOT" "EXIST";
````

We have not implemented this predicate so far as we currently return a 400, if a filter references a property that is not a queryable in the query context.

Unlike all the other predicates this one seems to apply to the schema of the instance, not the instance value (IS NULL handles that), but that is not clear. Do we really want that in the CQL core?

If yes, I think we need to clarify the expected behaviour. What does "exists" mean? A queryable in the collection of the feature/object? A potential property in the output of the feature/object? And how should implementations that are schemaless implement the operator?

**Comment by aaime** [comment]
I think it was meant to check for existence of the property before using it in other operators.
Since we are moving towards schemaless, the difference between "not being part of the schema" and "not having a value" might just disappear.

**Comment by cportele** [comment]
2020-07-20: The queryables already identify the properties that can be queried, so the need for `EXISTS` is not obvious. We will take it out for now. If a new need and clear definition comes up, we can add it in a separate conformance class in the future.
