### ISSUE TITLE
Core: describedby instead of describedBy

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-features#338]
According to the [IANA Link Relation Types registry](https://www.iana.org/assignments/link-relations/link-relations.xml), a resource that provides information about the link's context must be indicated with the name `describedby`, instead of `describedBy`, which is currently used in Core.

![image](https://user-images.githubusercontent.com/11427611/75674307-17ec7680-5c85-11ea-8c87-370b65096c4b.png)

![image](https://user-images.githubusercontent.com/11427611/75674482-66017a00-5c85-11ea-898f-115021e6d42e.png)

**Comment by cportele** [comment]
Thanks, @heidivanparys.

I will fix it. It is an editorial fix, the link relation types are case-insensitive (or their comparison is).
