### ISSUE TITLE
Bulk download (2)

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-features#342]
In an earlier issue, #230 , it was agreed to add a recommendation regarding the use of an `enclosure` link.

There is an ongoing discussion in the INSPIRE community regarding `enclosure`:

> [...] we appreciate the usefulness of 7.2.2, “Download of the whole data set”, but are not sure that “rel = enclosure” easily communicates this. We recognize that it is adopted from the Atom specifications & IANA link relation register – but we’re not sure how many users (developers?) find that ‘mainstream’.

There is currently a proposal to use the extension relation type http://www.w3.org/ns/dcat#downloadURL , see also section 2.1.2 from the IETF Proposed Standard [RFC 8288](https://www.rfc-editor.org/info/rfc8288).

There are several parallel discussion in the same issue, the most relevant part for this topic starts here: https://github.com/INSPIRE-MIF/gp-ogc-api-features/issues/22#issuecomment-573791098

Feedback on this would be greatly appreciated, here or in INSPIRE-MIF/gp-ogc-api-features#22

**Comment by cportele** [comment]
There was a recent discussion about the future approach to link relation types in the OGC Naming Authority, triggered by the discussion in [Common](https://github.com/opengeospatial/oapi_common/issues/76), the OGC Architecture Board and with IANA experts. The decision was (see [slide 172 of the public slides from the Ottawa closing plenary](https://portal.ogc.org/files/?artifact_id=92552)):

> The OGC-NA recommends the establishment of the following guidelines and rules for the governance of link relations.
> * Reuse existing link relation types registered with IANA wherever appropriate.
> * If an OGC specific relation type is needed, it will be prefixed with an “ogc-”
> * The OGC-NA will work with IANA to find a way to register these link relation types in the IANA register.

Based on this, I assume we will continue to use "enclosure" in the OGC API standards - at least until someone registers a new link relation type that expresses a dataset distribution download link more clearly.

**Comment by cportele** [comment]
Since [INSPIRE will continue to use "enclosure"](https://github.com/INSPIRE-MIF/gp-ogc-api-features/issues/46), I am going to close this issue.
