### ISSUE TITLE
Where are the conformance class URLs formally specified?

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-features#355]
In the OAPIF specification there is an example:
{
  "conformsTo": [
    "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/core",
    "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30",
    "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/html",
    "http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/geojson"
  ]
}
but I don't see anywhere where those URIs are formally defined.  Should they be listed in clause 2  or something?  I think it gets a bit confusing when you see the following normative URIs in the document:

http://www.opengis.net/spec/ogcapi-features-1/1.0/req/core, etc...

but the the URIs in the example are all "conf" and the "conf" URIs are not formally defined anywhere.  One is left with the feeling of "are the URIs in the example correct?"

There also seems to be some inconsistency in OAPICommon and in other OGC API specifications too; commons uses the "req" URIs not the "conf" URIs in the conformance example.   I will enter an issue again OAPICommon for that since I think these should should consistent across all the specifications; especially if you have an integrated service like ours where the /conformance output could potentially list classes from a number of specifications.

**Comment by cportele** [comment]
The conformance class URIs are defined in the conformance classes :wink:

For example: http://docs.opengeospatial.org/is/17-069r3/17-069r3.html#_conformance_class_core

If Common uses the requirements class URIs, Common needs to be updated.

See also #244 and #269.

**Comment by pvretano** [comment]
Ah, completely missed that!  Could we also include those URIs in clause 2, up front so that they are more prominent?

**Comment by cportele** [comment]
Have a look at PR #356...
