### ISSUE TITLE
UML for OpenAPI

### ISSUE THREAD

**Issue by cmheazel** [opengeospatial/ogcapi-features#36]
I have put together a UML model (Enterprise Architect) of OpenAPI 3.0. I thought it may be of use to this effort. Since I put it together for my own use, it is still a bit rough around the edges. I'll put the time into cleaning it up and aligning it with other WFS UML models if there is any interest.

[OpenAPI_20180130.zip](https://github.com/opengeospatial/WFS_FES/files/1679832/OpenAPI_20180130.zip)

**Comment by cportele** [comment]
Agreement on 2018-02-01: Table it for now, but probably it should be a separate resource that we (and others could) reference.
