### ISSUE TITLE
CRS and Payload

### ISSUE THREAD

**Issue by marqh** [opengeospatial/ogcapi-features#363]
In reviewing Part 2 - CRS
https://portal.ogc.org/files/91976

Feedback comment 

6.1. Overview

Recommendation 1 describes the www.opengis.net domain, but the document does not seem to address the issue that CRS definitions may come from other sources, such as the EPSG registry, e.g.
http://www.epsg-registry.org/export.htm?wkt=urn:ogc:def:crs:EPSG::4326

Further, there is no mention in section 6 of what format the CRS definitions may be expected to be returned in.  I would expect a section on the expectations on payload resolved from an identifying URI.
I would expect this payload encoding to explicitly reference WKT-CRS defined jointly by OGC and ISO in ISO19162
https://www.ogc.org/standards/wkt-crs
(18-101r7 at time of writing)
(http://docs.opengeospatial.org/is/18-010r7/18-010r7.html)

**Comment by heidivanparys** [comment]
> Recommendation 1 describes the [www.opengis.net](http://www.opengis.net) domain, but the document does not seem to address the issue that CRS definitions may come from other sources, such as the EPSG registry, e.g.
> http://www.epsg-registry.org/export.htm?wkt=urn:ogc:def:crs:EPSG::4326

According to the [Closing plenary public consolidated slides from the meeting in Leuven in 2019](https://portal.ogc.org/files/84732), slide 130, 

> Requests for EPSG definitions, sent to the OGC Definitions Server, shall be redirected to the EPSG registry Application Programming Interface (API).

Assuming that this has been implemented, the definition that is retrieved from the opengis.net domain is the same as the one in the EPSG registry. It is the GML definition though, I am not sure how to retrieve the WKT definition through opengis.net, if possible at all.

Is this also described in some other official/public OGC document that could be referred to from OGC API - Features - Part 2?

**Comment by cportele** [comment]
Meeting 2020-04-27: The scope of Part 2 is CRSs that are identified by a URI. There is no requirement that these URIs a resolvable and return anything. The payload of any CRS URI response is out-of-scope of part 2. This would change, if we add a conformance class for CRSs based on their WKT definition, etc, but this is not what Part 2 is about.

**Comment by cportele** [comment]
Meeting 2020-05-11: This issue can be closed for Part 2 as it is out-of-scope. @marqh - please reopen, if there is anything else from the comment that we need to address.
