### ISSUE TITLE
Axis Order CRS

### ISSUE THREAD

**Issue by marqh** [opengeospatial/ogcapi-features#364]
In reviewing Part 2 - CRS
https://portal.ogc.org/files/91976

Feedback comment

6.3.4. Coordinate system and axis order

This section is valuable.
However, it is not clear to me whether using the 'axisOrder' to override the axis order definition within the resolvable resource is allowed.
I believe the position should be that the axisOrder must be consistent with the payload defined by the URI.
That this provision cannot be used to change the axis order defined by the CRS URI

Indeed the very example provided is an example of this being done in contravention of the specification of ISO19111, OGC topic 2.

EPSG4326 defines the axis order to be "(latitude,longitude)"
http://www.epsg-registry.org/export.htm?wkt=urn:ogc:def:crs:EPSG::4326

So to provide an exemplar referencing 4326, via an OGC authority, which does not resolve
http://www.opengis.net/def/crs/OGC/0/4326

and which appears to reverse the axis order seems wrong on a number of levels.

This needs to be fixed, I think.
It would be good to get the broad intent clarified, and the text improved, as well as the example corrected.

**Comment by cportele** [comment]
Meeting 2020-04-27: The current expectation is that we change the HTTP header to the `Content-Crs` header based on the conneg-by-CRS proposal. See https://github.com/opengeospatial/ogcapi-features/issues/153#issuecomment-559050363. This would remove the capability to make the axis order explicit or change it.

**Comment by marqh** [comment]
Hello @cportele 

thank you for the update

Please may I ask that you confirm for me whether it is recognised that the example given in the reviewed draft indeed has mistakes related to CRS definitions and axis order?

I understand that there are expectations on how this will be handled in future drafts.  It would help me to know whether the current draft text is recognised as having errors, or whether there is some underlying intent here from one or more contributors that should be understood.

thank you
mark

**Comment by pvretano** [comment]
@marqh Yes, the current draft has errors.  Among the 10000 things I am working on this is but one and I made a mistake.  We will fix it and you will have a chance to review the fix.  Be aware that before we can submit this document to the TC for a vote we need to resolve all issues including this one.

**Comment by marqh** [comment]
thank you @pvretano, the clarification is appreciated

**Comment by cportele** [comment]
Meeting 2020-05-11: @cportele to write a PR for this and #153.

**Comment by cportele** [comment]
Addressed by #391 

Meeting 2020-05-25: Merge the change requests to create a consolidated readable draft document with all edits and distribute for review in the SWG. We can reopen issues, where needed.
