### ISSUE TITLE
Review Comment: Advertising the default CRS

### ISSUE THREAD

**Issue by cmorriscmps** [opengeospatial/ogcapi-features#376]
I take it from requirement 2 that support for CRS84/CRS84h is required, but advertising it is not.  I would suggest requiring the identifier to be in the advertised crs list unless the crs list is omitted altogether.  I think it is asking for confusion to make them implied.  It is a design goal that developers be able to understand how to use an API just by looking at its OpenAPI document, but, an uninitiated developer would likely assume that CRS84 is not supported if it is not advertised.

**Comment by cportele** [comment]
+1 from me, I think the default CRS should always be listed, too

**Comment by cportele** [comment]
Meeting 2020-05-11: Include the default CRS in the list.
