### ISSUE TITLE
Review Comment: Advertising spatial extents in multiple coordinate systems

### ISSUE THREAD

**Issue by cmorriscmps** [opengeospatial/ogcapi-features#378]
The core part of the spec contains a crs property associated with the spatial extent, and states that extensions may support additional coordinate reference systems and add additional enum values. 
However, there is no mention of it in the current part 2 (CRS) draft.  Has it been determined that there is no value in advertising spatial extents in anything but CRS84/CRS84h?

**Comment by cportele** [comment]
Meeting 2020-05-11: The main value in the spatial extent is to have that information in a commonly understood CRS, which is the default CRS, WGS84. The interoperability value of specifying the extent in other CRSs is not clear and not considered in scope of Part 2.
