### ISSUE TITLE
Review Comment: Storage CRS requirement for Simple Transactions requires clients to support CRS extension

### ISSUE THREAD

**Issue by jampukka** [opengeospatial/ogcapi-features#380]
Currently the draft version requires that if a server supports CRS extension then the geometries in POSTs and PUTs should be in storage crs advertised by the server.

This is problematic since it forces the client to also support CRS extension. The client needs to check if the server supports CRS extension possibly reproject the data to storageCRS. Not doing so violates the requirement.

I suggest that if both client and server support CRS extension (client should check first) then #153 / https://github.com/opengeospatial/conneg-by-crs could be used to determine the CRS of the geometry values. In addition the usage of storageCRS should be a Recommendation instead of a Requirement.

To be safe, a server supporting both simpletx and CRS should include the CRS information back in a header to the 201 Created (POST) / 200 OK (PUT). This would allow the client to double-check if server understood and accepted the CRS. If the header is missing the client should assume that CRS84(h) was used (as would be the case for servers supporting simpletx but not supporting CRS).

**Comment by cportele** [comment]
2020-08-16: Good point, there should be a separate requirements class so that one can have an API that only uses CRS84, but still supports transactions.

**Comment by pvretano** [comment]
Loosened the storage crs requirement for servers that support the CRS extension and instead, allow the client and server to negotiate a mutually agreeables CRS for the interaction.  I also added a recommendation to use the storage CRS if that is convenient and to set the Content-Crs header upon feature creation.
