### ISSUE TITLE
GML media types seem to be erroneous

### ISSUE THREAD

**Issue by dstenger** [opengeospatial/ogcapi-features#381]
Requirements `/req/gmlsf0/definition` and `/req/gmlsf2/definition` state that media types `application/gml+xml; version=3.2; profile=http://www.opengis.net/def/profile/ogc/2.0/gml-sf0` and `application/gml+xml; version=3.2; profile=http://www.opengis.net/def/profile/ogc/2.0/gml-sf2` shall be supported.

Shouldn't the profile parameter values be put into quotation marks?

Example: `application/gml+xml; version=3.2; profile="http://www.opengis.net/def/profile/ogc/2.0/gml-sf0"`

**Comment by cportele** [comment]
Yes, that is correct. The "/" and ":" are characters that need to be in quotes according to RFC 2045. I create a fix.
