### ISSUE TITLE
queryables link relation type

### ISSUE THREAD

**Issue by tomkralidis** [opengeospatial/ogcapi-features#383]
cc @alpha-beta-soup

If one wants to provide a link to a given collection's `queryables` endpoint, what link relation should they use (if any)?

Is there a suitable IANA type (`describes`?) Should there be an extension (`ogc-cql-queryables`)?

**Comment by cportele** [comment]
The current draft indeed does not (yet) have a requirement for a link from the collection.

I think we need a more specific relation type than the `describes`/`describedBy` ones. But it should not be CQL-specific, the queryables are applicable independent of the filter language. So my proposal would be `ogc-queryables`.

**Comment by tomkralidis** [comment]
Thanks @cportele.  Would `"rel": "ogc:queryables"` work or is it not allowed (or safer to use `-` for some other reason)?

**Comment by cportele** [comment]
The colon is only allowed in a `rel` value that is a URI, not in a plain text value. See https://tools.ietf.org/html/rfc8288#section-3.3.

And in a URI `ogc:` does not work as there is no URI scheme `ogc`. See the syntax of `URI` in https://tools.ietf.org/html/rfc3986#section-3.

But see also https://github.com/opengeospatial/oapi_common/issues/76, which will determine if it should be something like `ogc-queryables`, `http://www.opengis.net/def/rel/ogc/1.0/queryables`, or ...

Right now, we have to wait for the outcome of the discussion in Common.

**Comment by cportele** [comment]
Reopen for review in SWG meeting on 2020-12-07
