### ISSUE TITLE
CQL schemas are not aligned with OpenAPI 3.0 specifications

### ISSUE THREAD

**Issue by FarheenB** [opengeospatial/ogcapi-features#400]
The schemas in the following files are not aligned with the latest [OpenAPI3.0 specifications](https://swagger.io/specification/)
- [cql.json](https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/schema/cql.json) 
- [filter-capabilities.json](https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/schema/filter-capabilities.json)

The "definition" paradigm is no more supported in [OpenAPI3.0 specifications](https://swagger.io/docs/specification/basic-structure). Instead they have introduced "components/schemas" for Input Output Models. So updating the references from **{"$ref": "#/definitions/intersects"}** to **{"$ref": "#/components/schemas/intersects"}** is required.

**Comment by cportele** [comment]
Thanks, @FarheenB. 

These schemas conform to JSON Schema (draft 7), not the OpenAPI 3.0 Schema object. We do not have an OpenAPI 3.0 Schema variant yet, but eventually we will have one.

Note that with OpenAPI 3.1 and its use of the latest JSON Schema draft it will consistently be `#/$defs/intersects` in JSON Schema and OpenAPI Schema.

**Comment by cportele** [comment]
2020-08-03: @cportele will have a look at this and propose changes.

**Comment by cportele** [comment]
The schema has been moved to the normative text in the CQL JSON requirements class (http://docs.opengeospatial.org/DRAFTS/19-079.html#cql-json) and should be updated to draft 2019-09 (to prepare for OpenAPI 3.1) and to OpenAPI 3.0.

**Comment by cportele** [comment]
Updated schema / grammar documents:

* [JSON Schema in '2019-09'](https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/standard/schema/cql.json)
* [JSON Schema in 'draft 07'](https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/standard/schema/cql-draft7.json)
* [OpenAPI schema](https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/standard/schema/cql.yml)
* [ABNF](https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/standard/schema/cql.bnf)

**Comment by m-mohr** [comment]
Regarding the schemas, is which is the "entry-point", i.e. what cqlFilter is in the BNF? Is it predicates?

**Comment by cportele** [comment]
@m-mohr - Yes, it is `#/$defs/predicates`. 

@pvretano - Is there a reason why you used slightly different terms and tokens in the JSON schema?

**Comment by pvretano** [comment]
@cportele um, not really.  I guess I was just not paying attention.  I'll align that in the pull request for issue #460 (since there a lot of changes there already) so that when it gets merges, the alignment will come along for the ride!  Sound good?

**Comment by cportele** [comment]
Yes, sounds excellent.

**Comment by m-mohr** [comment]
Sounds like it is breaking my last PR to STAC, so we need to take care to update the $ref in https://github.com/radiantearth/stac-api-spec/pull/51

**Comment by m-mohr** [comment]
No worries, I made a comment to that PR and will just check back again every once in a while whether #461 has been merged. Thanks!
