### ISSUE TITLE
URI = uniform resource identifier not unique resource identifier 

### ISSUE THREAD

**Issue by nmtoken** [opengeospatial/ogcapi-features#405]
ref: http://docs.opengeospatial.org/DRAFTS/18-058.html

In requirement 1 the text is:

_Each CRS supported by a server SHALL be referenceable by a unique resource identifier (i.e. a URI)._

However URI acronym is `uniform resource identifier ` not `unique resource identifier`  ~ https://tools.ietf.org/html/rfc3986

**Comment by cportele** [comment]
Thanks @nmtoken - I will fix that!
