### ISSUE TITLE
Core: question regarding link with "self" relation type for feature collection

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-features#410]
There is no statement in the standard regarding a link with link relation type "self" for a feature collection:

![image](https://user-images.githubusercontent.com/11427611/86568701-8e6bee80-bf6d-11ea-8c49-68d0212c258b.png)

https://github.com/opengeospatial/ogcapi-features/blob/master/core/examples/json/Collection.json does not contain  a link with link relation type "self" either.

Is there any guidance on that, and arguments behind that guidance?

Is something perhaps missing in the standard? A permission that it may be present? A recommendation that it should be present? Or perhaps a requirement that it shall not be present?

**Comment by cportele** [comment]
It is an oversight that we have not included anything about the self/alternate links for each Collection in the normative text. In the Collections resource there should be a self link for each Collection and in the Collection resource there should be self and alternate. The implementations that I have checked include them, but this is not in the spec. Two options:

* Include them in the spec as recommendations only (to avoid breaking implementations)
* Classify this as an error and add requirements in v1.0.1

**Comment by cportele** [comment]
Meeting 2020-07-06: Add these as recommendations with a note that clarifies that the missing links were an oversight and implementers should really implement the links. @cportele to create a pull request.

**Comment by heidivanparys** [comment]
How about the ETS? Can that be implemented in a way so it comes with a warning (not a failure) if the links are missing?

**Comment by cportele** [comment]
@ghobona @dstenger - could you answer the question of @heidivanparys above? I don't know, if the CITE tests can support warnings for recommendations that have not been implemented. Thanks!

**Comment by ghobona** [comment]
@heidivanparys We'll look into your suggestion.  

Please track the CITE issue at https://github.com/opengeospatial/ets-ogcapi-features10/issues/114

**Comment by heidivanparys** [comment]
@ghobona @cportele Regarding the suggestion for a warning to (try to) make sure that implementers add the "self" and "alternate" links, I think that for INSPIRE, it can be solved in a different way with INSPIRE-MIF/gp-ogc-api-features#39 .
