### ISSUE TITLE
Rename CQL extension to filtering (can support multiple filtering languages)

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-features#423]
The extension is currently called CQL, but allows for filtering in other languages.

For example our implementation does not currently support CQL, but supports filtering through CMSS expressions.

We also just discussed following the Maps API that this extension may also be applicable to other APIs (e.g. Maps, Tiles), so is this  a candidate for Common?

**Comment by pvretano** [comment]
@jerstlouis you are confusing the language with the parameters (filter, filter-lang and filter-crs) that bind the language to the features specification.  The language is CQL.  The parameters are not part of the language.  Another binding might allow you to POST CQL to a specific endpoint (e.g. /search) without using the query parameters ... but the language remains the same.

**Comment by pvretano** [comment]
@jerstlouis CQL started in features but the intent from the very beginning was that CQL would move into Common.  That is why we segregated the language from the binding.  Common may also decide to define standard bindings like filter, filter-lang and filter-crs  and/or a "/search" endpoint that other referencing specification may decide to use.  In any case, the referencing specification would need to include a clause describing any additional requirements for its resource type(s).

**Comment by jerstlouis** [comment]
@pvretano Ah OK, so this extension defines CQL the language itself.

But in https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/standard/clause_6_filter.adoc, it defines Q\ueryables, filter, filter-lang, filter-crs...

If CQL is intended to be stand alone, shouldn't that be separated, i.e. a seprate extension for the binding aspect?

Thanks.

**Comment by akuckartz** [comment]
> If CQL is intended to be stand alone, shouldn't that be separated, i.e. a seperate extension for the binding aspect?

👍 

> If this is the extension that defines these filtering bindings, regardless of which filtering language you use, I still think the extension would better be called "filtering", even if it does define one language to do it.

:-1: because that blocks alternative languages from being used, "filtering" would imply "CQL".

**Comment by jerstlouis** [comment]
>  because that blocks alternative languages from being used, "filtering" would imply "CQL".

Well not if they are organized as separate conformance classes of the extension, e.g. one conformance class being CQL.

**Comment by cportele** [comment]
2020-08-03:

* The "Filter" requirements class could later be moved to Common.
* The same is true for the CQL filter language and its encodings ("Simple CQL", the CQL enhancement requirements classes and the encodings requirements classes).
* These could be defined in separate documents or kept in a single document. For now, a single document as it is is fine, too, just like we have HTML/GeoJSON/GML-SF/OpenAPI 3.0 encodings in Core. If moved to Common, Common could decide to split this into two documents. To reflect the double purpose we will rename the document to "Filtering and Common Query Language (CQL)".
* The "Features Filter" requirements class has to stay in Features and will always be in Part 3 of Features.

We will add a discussion about this in the introduction.
