### ISSUE TITLE
Question on core and OpenAPI: definition server & paths

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-features#427]
In most examples and implementations something like the following is used:

```
    "servers": [
        {
            "url": "https://my.url.com/v1/mydata",
            "description": "My description"
        }
    ],
    "tags": [
        ...
    ],
    "paths": {
        "/": {
            ...
        },
        "/conformance": {
            ...
        },
        "/collections": {
            ...
        },
		...
    }
```

Is the following a valid approach as well, or not? I've read through the spec and also the OpenAPI spec, but I can't seem to find a clear answer.

```
    "servers": [
        {
            "url": "https://my.url.com",
            "description": "My description"
        }
    ],
    "tags": [
        ...
    ],
    "paths": {
        "/v1/mydata/": {
            ...
        },
        "/v1/mydata/conformance": {
            ...
        },
        "/v1/mydata/collections": {
            ...
        },
		...
    }
```

Currently, the ETS assumes the first model is used, and does e.g. not find the conformances classes implemented by the API when the second model is used (see https://github.com/opengeospatial/ets-ogcapi-features10/issues/116 ).

**Comment by cportele** [comment]
Both variants are valid. There is an explicit note in 7.1 that clarifies this:

> All paths (e.g., `/`) are relative. If the API covers other resources beyond those specified in this document, the landing page can also be, for example, a sub-resource of the base URL of the API.

@ghobona, @dstenger - Sounds like the CITE tests might need an update.

**Comment by heidivanparys** [comment]
@cportele Ok, thanks for the clarification.
