### ISSUE TITLE
Core: question on bbox in response

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-features#435]
I have a question regarding `/req/core/fc-bbox-response` (highlighting is mine):

> Requirement 23 | /req/core/fc-bbox-response
> -- | --
> D | **The bounding box is provided as four or six numbers**, depending on  whether the coordinate reference system includes a vertical axis (height  or depth):     Lower left corner, coordinate axis 1   Lower left corner, coordinate axis 2   Minimum value, coordinate axis 3 (optional)   Upper right corner, coordinate axis 1   Upper right corner, coordinate axis 2   Maximum value, coordinate axis 3 (optional)
> E | **The bounding box SHALL consist of four numbers** and the coordinate  reference system of the values SHALL be interpreted as WGS 84  longitude/latitude (http://www.opengis.net/def/crs/OGC/1.3/CRS84) unless a different coordinate reference system is specified in a parameter bbox-crs.

How should I read this? Now I see two subrequirements for the bounding box in the **response** of the server:

- The bounding box is (SHALL be?) provided (in the response? as it is located in `/req/core/fc-bbox-response`) as four or six numbers
- The bounding box (in the response) SHALL consist of four numbers

Is there a conflict there? What should happen if the client supplies a bbox in http://www.opengis.net/def/crs/OGC/0/CRS84h and the server returns features in http://www.opengis.net/def/crs/OGC/0/CRS84h ? What should the bbox in the request look like?

And what should happen when a client supplies a bbox in http://www.opengis.net/def/crs/OGC/0/CRS84h but the server only serves data in http://www.opengis.net/def/crs/OGC/0/CRS84? Returning an error or just ignoring the height parameters?

**Comment by cportele** [comment]
> The bounding box is (SHALL be?) provided (in the response? as it is located in /req/core/fc-bbox-response) as four or six numbers
> The bounding box (in the response) SHALL consist of four numbers

There are no requirements regarding any bounding box information in the response. These sub-requirements are about the bbox value provided with the request. I see the point, sub-requirements D and E fit better to "/req/core/fc-bbox-definition" and could be moved there and the "is" could also be changed to "SHALL be".

> Is there a conflict there? What should happen if the client supplies a bbox in http://www.opengis.net/def/crs/OGC/0/CRS84h and the server returns features in http://www.opengis.net/def/crs/OGC/0/CRS84h ? What should the bbox in the request look like?

No conflict.

```
bbox=7.22,51.28,0,8.01,51.69,100&
bbox-crs=http%3A%2F%2Fwww.opengis.net%2Fdef%2Fcrs%2FOGC%2F0%2FCRS84h&
crs=http%3A%2F%2Fwww.opengis.net%2Fdef%2Fcrs%2FOGC%2F0%2FCRS84h
```

> And what should happen when a client supplies a bbox in http://www.opengis.net/def/crs/OGC/0/CRS84h but the server only serves data in http://www.opengis.net/def/crs/OGC/0/CRS84? Returning an error or just ignoring the height parameters?

Return an error. See http://docs.opengeospatial.org/DRAFTS/18-058.html#req_crs_fc-bbox-crs-valid-value.

**Comment by heidivanparys** [comment]
@cportele Thanks for the clarification.

One additional question:

I am confused when I compare [/req/core/fc-bbox-response](http://docs.opengeospatial.org/DRAFTS/17-069r4.html#req_core_fc-bbox-response)

> Requirement 23 | /req/core/fc-bbox-response
> -- | --
> E | The bounding box SHALL consist of four numbers and the coordinate reference system of the values SHALL be interpreted as WGS 84  longitude/latitude (http://www.opengis.net/def/crs/OGC/1.3/CRS84) unless a different coordinate reference system is specified in a parameter bbox-crs.

with [/req/crs/fc-bbox-crs-valid-defaultValue](http://docs.opengeospatial.org/DRAFTS/18-058.html#req_crs_fc-bbox-crs-valid-defaultValue)

> | Requirement 8 | /req/crs/fc-bbox-crs-valid-defaultValue |
> | -- | -- |
> | | If the bbox-crs parameter is not specified then the coordinate values of the bbox parameter SHALL be assumed to be in the default CRS specified in OGC API - Feature - Part 1: Core; that is http://www.opengis.net/def/crs/OGC/1.3/CRS84 for coordinates without height and http://www.opengis.net/def/crs/OGC/0/CRS84h for coordinates with height. |

So according to [/req/core/fc-bbox-response](http://docs.opengeospatial.org/DRAFTS/17-069r4.html#req_core_fc-bbox-response), the bounding box shall consist of four numbers when no bbox-crs parameter is specified. However, according to [/req/crs/fc-bbox-crs-valid-defaultValue](http://docs.opengeospatial.org/DRAFTS/18-058.html#req_crs_fc-bbox-crs-valid-defaultValue), the bounding bbox may be specified using coordinates with height ⇒ a bbox parameter consisting of 6 numbers.

**Comment by cportele** [comment]
Good point, I think we need to update this to make it consistent. I will work on a PR before the SWG meeting next week. I will have a look at other places in the document, too.

**Comment by heidivanparys** [comment]
> I will have a look at other places in the document, too.

Thanks. I think everywhere where the two standards say something about "default CRS", the text (including YAML schemas and examples) should be double-checked.

**Comment by cportele** [comment]
Meeting 2020-09-14: Review the pull request until the next SWG meeting on 2020-09-28.
