### ISSUE TITLE
Core: question on landing page response and "self" link

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-features#436]
I noticed that the example for a landing page response contains a link with `self` link relation type, but such a link is not mentioned in the accompanying text and not in the normative statements regarding the landing page response (in contrast to the statements regarding the other resources). Should something be added to the specification? Is that link recommended or simply optional?

![image](https://user-images.githubusercontent.com/11427611/92384881-25d9f300-f111-11ea-8099-5f993a036c46.png)

**Comment by cportele** [comment]
Meeting 2020-10-12: @cportele to add a recommendation PR as the `self` and `alternate` links are helpful. A requirement would be a breaking change and such links are not essential.
