### ISSUE TITLE
Link to editor's draft with errata from the OGC standards page

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-features#452]
Meeting 2020-11-09: We are collecting errata and editorial updates to version 1.0.0 in the editor's draft at http://docs.ogc.org/DRAFTS/17-069r4.html which eventually will be published as version 1.0.1. This document only includes changes that have been agreed by the SWG and the document is updated daily. It might be helpful to include a link to the editor's draft from the landing page for OGC API Features on the OGC website at https://www.ogc.org/standards/ogcapi-features. 

@ogcscotts @ghobona: any views on this?

**Comment by ghobona** [comment]
I discussed this with @ogcscotts. Here is the guidance we agreed on.

Errata and editorial changes can be made through a corrigendum, so the SWG would just need to post the revised version on Pending, either a summary of changes or a presentation to the TC, then a Plenary or 2-week email vote.

**Comment by cportele** [comment]
Thanks @ghobona. The idea, however, was to avoid creating frequent corrigenda, but rather collect errata/clarifications for a while in the Editor's draft and at the same time make everyone aware that there are errata/clarifications. Currently, a visitor will only be pointed from the OGC websites to the published version and has to go to the Features repo to find a link to the latest version based on SWG decisions.

We have had a number of clarifications [since 1.0.0](http://docs.opengeospatial.org/DRAFTS/17-069r4.html#_revision_history) and there are also a few open issues that may result in further clarifications. We thought it might be better to wait a bit more to move the changes through the corrigendum process.

**Comment by ghobona** [comment]
So is the proposal to add a line such as **"Clarifications are available on the [Editor's draft](http://docs.opengeospatial.org/DRAFTS/17-069r4.html) of a Corrigendum"** on the following pages?

* https://ogcapi.ogc.org/features/
* https://www.ogc.org/standards/ogcapi-features

**Comment by cportele** [comment]
@ghobona - yes, exactly. It should be close to the links to the published version(s).

**Comment by ogcscotts** [comment]
@cportele @ghobona I think that such a link is fine provided that we make the link to the approved version dominant and this link clearly less-dominant. We had problems in the past with user confusion over which GeoPackage draft should be implemented because the status of linked documents was not super-clear.

**Comment by cportele** [comment]
@ogcscotts - Understood!

**Comment by cportele** [comment]
Meeting 2021-01-18: We discussed approaches for spec navigation links and @ghobona will be working on a proposal based on the discussion and the conclusion documented above. We will keep the issue open until it is done.

**Comment by ghobona** [comment]
Both the [OGC API website](https://ogcapi.ogc.org/features/) and the [main OGC website](https://www.ogc.org/standards/ogcapi-features) have been updated with links to the Editor's Draft.

**Comment by cportele** [comment]
Thanks, @ghobona. I will close this issue.

One final comment: The link text on both sites has a typo and uses "verison" instead of "version".

**Comment by ghobona** [comment]
Thanks for spotting the "verison" issue. I'll have it updated.
