### ISSUE TITLE
Core refers to bbox-crs

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/ogcapi-features#454]
The Core specification refers to a parameter called bbox-crs in several places, but it's not defined anywhere in the Core spec. I'm personally aware that it's likely defined in the CRS extension, but the average reader probably not. So either it should be removed from Core or Core should make clear in the spec that this is a parameter not available unless the CRS extension is implemented.

**Comment by cportele** [comment]
The text currently states:

> This standard does not specify requirements for the parameter bbox-crs. Those requirements will be specified in an additional part of the OGC API Features series.

But this is stated only once and not everywhere bbox-crs is mentioned.

> it's likely defined in the CRS extension

It is. With part 2 published, we could also add a reference to the [bbox-crs definition](https://docs.opengeospatial.org/is/18-058/18-058.html#_parameter_bbox_crs).
