### ISSUE TITLE
OGC Architecture Board draft motion on OGC API guidelines

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-features#459]
The OGC Architecture Board (OAB) is discussing the following motion:

> OAB does not approve any API for Public RFC until the API SWGs agree to common set of non-geographic Web API Guidelines

The goal would be to advance the [OGC Web Guidelines](https://github.com/opengeospatial/OGC-Web-API-Guidelines) to an approved document that can facilitate the development of OGC API standards. 

The OAB is asking for collective feedback from those working on the OGC API standards, i.e. the Standards Working Groups (SWGs). 

We discussed the topic in a Features API SWG meeting, below is a brief summary. As presented, there are several concerns about the proposed motion:

* For most part, the "non-geographic" aspects of the API design will and should reflect the underlying standards (mainly from IETF) and commonly used practices, tools and specifications including OpenAPI. If there are disagreements about an approach these can be raised as issues and discussed for each draft OGC API standard. Moving resources to a general guideline development activity does not seem to be a good use of the limited resources.
* Currently the draft OGC Web API Guidelines are written as a checklist to help those that design OGC API standards by documenting common practice in OGC API standards and elsewhere. It is ok to deviate from the guidelines, if there are reasons. Is the idea to change this towards firm requirements?
* The OGC Web API Guidelines should not change the fact that the design of OGC API standards should be driven by what works best in draft implementations. From the wording of the motion this is not clear.

The SWGs were asked to provide feedback by today, but we only got to documenting this issue now. If there are any comments, please provide input before 2020-12-04 so we can provide feedback to the OAB during the next OGC Member Meeting.

The OAB has also asked for volunteers. If any SWG member is interested in contributing to the guideline development, please let me and @pvretano know, too.

cc @ghobona

**Comment by ghobona** [comment]
All, 

I will be reporting back to the OAB on Monday 7 December at 2:00 PM EST.

If there are any comments or volunteers then please let me know by noon EST on Monday 7 December.
