### ISSUE TITLE
Need to refactor JSON encoding of CQL ...

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-features#460]
In the course of writing JSON-encoded examples for CQL I ran into an issue.  The current JSON encoding relies on the fact that keys can be repeated but whether that is legal or not is unclear.  Most JSON parser I tried usually take the first key and ignore the rest which is a problem.  To avoid the entire issue, I am going to refactor the JSON encoding just a bit to avoid this problem.

**Comment by m-mohr** [comment]
Although it's legal, it's not recommended: https://stackoverflow.com/questions/21832701/does-json-syntax-allow-duplicate-keys-in-an-object/23195243 I guess an array would work?!

**Comment by ghobona** [comment]
My **unofficial** test would be "how would a tool such as [OpenAPI Tools Generator](https://github.com/OpenAPITools/openapi-generator) handle the definition?".

**Comment by m-mohr** [comment]
@ghobona I don't think that would test anything valuable. It's not about the OpenAPI definition, but about the values you pass to the server. And as many JSON parsers indeed can't handle multiple keys with the same name AND it is not recommended by the RFC, I think it should definitely be changed as @pvretano proposes.

**Comment by ghobona** [comment]
@m-mohr I now see that RFC 8259 is very clear on the topic:  "The names within an object SHOULD be unique."

**Comment by cholmes** [comment]
How likely is this to merge in the next day or two? We're pushing for a STAC API 1.0-beta.1 release, and were going to try to merge in [CQL alignment](https://github.com/radiantearth/stac-api-spec/pull/51), but we probably will just wait for beta.2 to bring in CQL if this won't get in this week.

**Comment by pvretano** [comment]
@cholmes I'm going to say not likely.  Sorry about that!  Other SWG members need to review and I need to add examples.

**Comment by cholmes** [comment]
Ok, no problem at all - thanks for the fast response. And yes, examples would definitely be helpful.

**Comment by cportele** [comment]
Reopen for review in SWG meeting on 2020-12-07

**Comment by m-mohr** [comment]
Is there an example for the new JSON encoding? I couldn't find one in the PR...

**Comment by pvretano** [comment]
@m-mohr there will be.  @cportele and I are adding examples this week.
