### ISSUE TITLE
Describing features properties

### ISSUE THREAD

**Issue by NuriaJulia** [opengeospatial/ogcapi-features#476]
I'm trying to implement a transactional OAPI features client.  I need to know the properties of the feature (or collection) but in the new standard the DescribeFeature request has disappeared.
How can I get this information? Is this '.../collections/{collectionId}/schema' an standard request '?

**Comment by cportele** [comment]
Meeting 2021-01-18: This will be addressed as part of the proposed schema activity. @cportele will draft a proposal that would go into that new part, but could also (temporarily) be copied into part 4 (to make it complete) until the schema part is published. This is similar to the queryables schema from part 3.

**Comment by cportele** [comment]
Addressed in PR #504. Two items for discussion:

- Currently this references a schema resource (at `/collections/{collectionId}/schema`). There is a query parameter `type` as a qualifier about the type of schema to return. The default probably should be the response schema in case of a read-access to the feature (e.g., `type=read`) and for the create/replace/update operations, which all can have a somewhat different schema, it would be `type=create`, `type=replace` and `type=update`. For the queryables from part 3 we should then move this from `/collections/{collectionId}/queryables` to `/collections/{collectionId}/schema?type=queryables`.
- Currently every server would have to provide the schemas, but this is probably too strong? Alternatives are changing it into recommendations or another requirements class for schemas.

**Comment by cportele** [comment]
Meeting 2021-02-01: The general approach with the schema resource looks good. However, schema support should be optional; change to a recommendation and provide context (@cportele).
