### ISSUE TITLE
Clarification of difference between PUT, PATCH and POST

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-features#478]
There's a need to provide clarification on the difference between PUT, PATCH and POST.

Proposed rules suggested:

* PATCH does not allow you to update the identifier
* PUT does allow you to set the identifier
* POST allows you to send to a parent resource

Needs further discussion in the SWG.

**Comment by cportele** [comment]
Meeting 2021-01-18: @pvretano will add informative text about the questions raised in this issue. See also #329.

**Comment by cportele** [comment]
Meeting 2021-02-15: The current version is clear about the behaviour of POST, PUT and PATCH, so we think the issue can be closed.
