### ISSUE TITLE
The SWG should consider the "HTTP dilemma" and clarify in the spec

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-features#479]
There is a need for the SWG to also consider the "HTTP dilemma".

* HTTP POST /collections/<abc> <payload=GET query> => alternative to HTTP GET /collections/<abc>?<query> if URL gets too long!
* HTTP POST /collections/<abc> <payload=feature content> => create one/multiple resources

Suggestion to allow HTTP POST to be used for retrieving data, in addition to allowing it to be used for inserting data.

**Comment by cportele** [comment]
Close, there was no additional discussion.

The general POST topic is discussed in #449.
