### ISSUE TITLE
CQL: Restrict timezone in temporal literals to UTC ("Z")?

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-features#483]
OGC API Features uses RFC 3339 for timestamps, i.e., all timestamps have a time zone.

Currently temporal literals in CQL can be in any time zone. Should at least Simple CQL be restricted to UTC?

**Comment by heidivanparys** [comment]
This is perhaps related to this? The OAB discussed this apparently before (I don't have access to that part of the OGC portal), but some others here perhaps do) https://github.com/opengeospatial/geopackage/issues/530#issuecomment-724845716

**Comment by cportele** [comment]
I do not have access to the OAB part of the OGC portal either (access to the OAB project worked until about 2 months ago and that changed without information about the change). But since nothing is included in the [Policy Directives](https://portal.ogc.org/public_ogc/directives/directives.php), either the OAB is still discussing something or there was no result. If an OAB member has any further information, please let us know. 

cc @ogcscotts

**Comment by ogcscotts** [comment]
OAB Issues should now be visible to everyone, but only if you have a link to the Issue. We are trying to refine the access permissions for the OAB as well as update some operations (including considering moving Issues to GitHub). Stay tuned - hope to make the access simpler very soon.

**Comment by cportele** [comment]
Meeting 2021-06-21: We plan to fix the timezone to URC ("Z"), because it makes life easier in evaluating filter expressions. This would also be consistent with the GPKG approach and also the next generation 911 services use UTC. If there are any concerns about such a decision, please add a comment here in the next 2 weeks.

**Comment by cportele** [comment]
Meeting 2021-07-05: No comments have been added, so we will fix the timezone to "Z".
