### ISSUE TITLE
CQL: "Y" missing from the list of reserved keywords

### ISSUE THREAD

**Issue by jratike80** [opengeospatial/ogcapi-features#488]
In http://docs.ogc.org/DRAFTS/19-079.html#rc_simple-cql, Requirement 31, "The list of CQL keywords includes:"

"X" and "Z" appear in the list but "Y" doesn't.

**Comment by cportele** [comment]
"X" and "Z" are not related to coordinates and "Y" is not a keyword.

"X" is used in `hexStringLiteral = "X" quote [ {hexit} ] quote;`.

"Z" is used in `timeZoneOffset = "Z" | sign timeHour [[colon] timeMinute];`

**Comment by cportele** [comment]
Meeting 2021-07-19: Obsolete, can be closed.
