### ISSUE TITLE
CQL: Question about using % as a wildcard in LIKE

### ISSUE THREAD

**Issue by jratike80** [opengeospatial/ogcapi-features#489]
**Requirement 18, /req/simple-cql/like-predicate**

> The patternExpression SHALL be a POSIX regular expression (see https://pubs.opengroup.org/onlinepubs/9699919799/).

In the examples https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/examples/examples.txt the SQL-alike percent syntax is used

`CQL: owner LIKE 'Mike%'`

This percent syntax is defined at least in https://portal.ogc.org/files/?artifact_id=831 "Catalog Interface
Implementation Specification (Version1.0)"

```
<character pattern> ::= <character string literal> /* In a character pattern
the character percent is used as a wildcard to represent an
arbitrary string. This allows LIKE to implement the effect of many
characters matching operations, such as: contains, begins with,
ends with, not contains, not begins with, not ends with, and so
forth. For example:
 attribute like '%contains_this%'
 attribute like 'begins_with_this%'
 attribute like '%ends_with_this'
 attribute like ‘d_ve’ will match ‘dave’ or “dove””
 attribute not like '%will_not_contain_this%'
 attribute not like 'will_not_begin_with_this%'
 attribute not like '%will_not_end_with_this’*/
```

I must admit that I am not so good in reading the Posix regexp document.  If patternExpression SHALL be a POSIX regular expression, does it mean that the percent syntax is not valid in LIKE?

**Comment by pvretano** [comment]
@jratike80 you are looking at the **WRONG** examples file.  The file cql/examples/example.txt is an OLD file using an OLD syntax.  I was going to remove it from the repo but instead have decided to move all the examples in example.txt into separate files in cql/standard/schema/examples.  All examples from example.txt will be updated to use the correct syntax.  Unfortunately you are reviewing FASTER that I can edit.  Please stand by and I will tag you to review the PULL request that updates the examples.

**Comment by pvretano** [comment]
@jratike80 I have removed the old examples.txt file and instead added a bunch of examples to extensions/cql/standard/schema/examples from that file which have also been updated to the correct CQL and JSON syntax.  Please take a look and let me know if you need any problems before we merge.  The link to the PR is: https://github.com/opengeospatial/ogcapi-features/pull/490.

**Comment by jratike80** [comment]
This is clear now. Follow-up questions and a comment:

- Are clients supposed to have full support for POSIX regexp?
- What use cases were in mind when regexp was selected instead of percent syntax?
- CQL that is used in CSW and this new CQL dialect for OAPI Features use different syntax for string comparisons. That may lead to some confusion. But I guess that it is too late to add a new keyword for the LIKE(RegExp) operation.

**Comment by cportele** [comment]
Thanks for your review and questions, @jratike80.

> Are clients supposed to have full support for POSIX regexp?

The standard does not impose requirements on clients, only on servers. Servers have to have full support for POSIX regex, clients can use the subset that they want to support.

> What use cases were in mind when regexp was selected instead of percent syntax?

Regex are more powerful filters for text than simple wildcard expressions. Plus they are widely used and supported in most environments. We can express in the schema of an attribute that it matches a regex pattern, so it makes sense to allow the use of regex also for filtering.

> CQL that is used in CSW and this new CQL dialect for OAPI Features use different syntax for string comparisons. That may lead to some confusion. But I guess that it is too late to add a new keyword for the LIKE(RegExp) operation.

It is not too late for changes before the standard is published! Yes, we hope that the general structure of CQL and the filter parameters should be stable, but we want more eyes on it and see, if there are any problems. Comments like yours are valuable feedback. This is why we want to move the document to what OGC calls "public review" and get implementation/usage feedback. 

For the specific question, I think there are three options:

* Support LIKE with wildcards. Less powerful, but consistent with the "old" CSW CQL.
* Support LIKE with regex. More powerful, but maybe confusing to those knowing CSW.
* Support LIKE with wildcards and add another operator with support for regex. Supports both, but servers would have to implemented an additional operator where LIKE is basically just a subset of the regex operator.

**Comment by aaime** [comment]
Regular expression support is widely available indeed, and if not available in the base storage, it can be emulated in memory.
What worries me is the efficiency of it, I don't commonly see index support for it.
On the other end, LIKE has at least partial index support, for prefix searches, and in some databases, also for containment searches (which are the most common case for UIs allowing some sort of auto-complete while typing).
So first worry, using regexs as the default, would put servers in a position of supporting something potentially quite inefficient, or not expose partial text searches at all.

The second issue I see comes from the old regex adage: "You decided to solve a problem with regular expressions. Now you have two problems". 
Laughs aside, regular expressions are often poorly understood, while LIKE syntax is more commonly understood.

Personally, I'd go for the third option @cportele mentioned: create a separate operator to support regex searches, and keep LIKE in its SQL-like simplicity, and make support for regex optional.

**Comment by pvretano** [comment]
@aaime @jratike80 @cportele I am happy to just revert back to SQL LIKE semantics.  My thinking was that REGEX was more powerful (if more difficult to learn ... even I got confused between SQL LIKE semantics and REGEX semantics and I have been using both for years).  If we do decide to flip back then I don't think it is necessary to ALSO support REGEX.  If anyone want REGEX support, they can write and extension to add a REGEX LIKE operator or something like that.  Thoughs?  Should I fall back to SQL LIKE semantics?

**Comment by jratike80** [comment]
I would prefer to turn back to SQL/CSW LIKE. It is easy to learn, SQL users know how to use it already, and I believe that majority of use cases can be handled with it.

**Comment by cportele** [comment]
Yes, I guess the conclusion of the discussion is that we should continue to use the standard SQL LIKE mechanism with `%` and `_` as wildcards as part of Simple CQL. 

If we add support for regex, it should be in a separate requirements class and maybe this could also be added in a future revision.

**Comment by jratike80** [comment]
Does the CQL in CSW support `_` as a single character wildcard? In version 1.0 https://portal.ogc.org/files/?artifact_id=831 it is not documented, but maybe it is in later versions. BTW what is the best document about CQL?

If we support `_` we should also document how to escape the underscore if it appears in the string. Sooner or later somebody wonders why `like 'foo_%` finds `foo_bar` but also `foozbar`.

**Comment by pvretano** [comment]
@jratike80 hard to say.  The latest version of the CSW specification is here http://docs.opengeospatial.org/is/12-168r6/12-168r6.html#54 and the BNF is in pretty bad shape and I would not use that as a reference for CQL.  The BEST document for CQL is this extension document that you are reviewing right now.  Here is a reference to the "nightly build" of the document: http://docs.opengeospatial.org/DRAFTS/19-079.html.  The original SQL LIKE semantic that was part of CQL allowed the wildcard, single char and escape characters to be specified so I will re-introduce that again.

**Comment by pvretano** [comment]
@cportele @aaime @jratike80 OK, I will reintroduce the SQL LIKE semantic into CQL.  Might take be a day or two since I have other fish to fry at the moment.  Please stand by ...
