### ISSUE TITLE
Case insensitive language tokens in CQL.

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-features#495]
Right now the language tokens in CQL TEXT are case sensitive.  
I think they should be case insensitive and am seeking input about the approach I should take to make this change. There are two possibilities.

1. The simple approach is to add requirements saying that the language token are case insensitive.  
2. The more onerous approach is to define productions for each language token along the line of and=("A"|"a")("N"|"n")("D"|"d") and then reference these productions in the rules.

 Sidebar: I should probably see if BNF/ABNF/EBNF has some shorthand syntax for this.

Comments?

**Comment by cportele** [comment]
I think that is built into ABNF: 

> ABNF strings are case insensitive and the character set for these strings is US-ASCII.

And there is another RFC to allow literals in an ABNF grammar to be case sensitive: https://tools.ietf.org/html/rfc7405

So, I think `/req/simple-cql/caseless` is not strictly required and it can just be converted to informative text pointing out that all keywords are case insensitive.
