### ISSUE TITLE
Upload Recording of 2021-02-15 SWG Meeting to OGC Portal

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-features#507]
The recording of each OGC API SWG meeting is supposed to be posted to the OGC Portal. This GitHub issue is meant to keep track of the upload of the recordings and also to serve as a quick reference. Note that the recordings are to remain access controlled (only accessible by OGC Members).

**Comment by cportele** [comment]
@ghobona - There is nothing I can do. I do not have access to the recordings and I do not see the SWG meetings in my OGC GTM account. 

<img width="438" alt="Screenshot 2021-02-15 at 11 42 50" src="https://user-images.githubusercontent.com/4245251/107936514-0a59fa80-6f83-11eb-851a-fe4c317c3891.png">

@pvretano, do you have access to them?

**Comment by ghobona** [comment]
The portal event was created by @pvretano , so the recording will appear in his Gotomeeting dashboard.

I have just changed the assignment to @pvretano

**Comment by ghobona** [comment]
The  recording is at https://portal.ogc.org/files/?artifact_id=96472

The link is access controlled.
