### ISSUE TITLE
datetime versus date-time

### ISSUE THREAD

**Issue by chris-little** [opengeospatial/ogcapi-features#508]
Both strings `datetime` and `date-time` occur in the document as well as `date` and `time`. 

`datetime` is the widely accepted, and is used in API-EDR, even though it broke the kebab-case convention.

Havng both forms is confusing.

**Comment by cportele** [comment]
@chris-little - `datetime` is (only) used for the API parameter and `date-time` is the name of the token in the RFC 3339 BNF. Both are what they are, so there is no way around this that I can see. What change are you proposing?

**Comment by chris-little** [comment]
@cportele If the OpenAPI parameter is `datetime' and `date-time' is only the BNF token, then all is fine, and consistent with API-EDR.
