### ISSUE TITLE
Support optimistic locking using etags for PUT/PATCH?

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-features#515]
See, for example, https://sookocheff.com/post/api/optimistic-locking-in-a-rest-api/. This should be quite useful for some scenarios. Of course, it should be a separate conformance class.

**Comment by cportele** [comment]
Meeting 2021-03-15: Add optimistic locking as an additional conformance class.

**Comment by cportele** [comment]
Open comments from the review of #524:

* Since `Last-Modified` is used in the examples, maybe we should mention it in the text somewhere, even if we do not add any normative text related to the header?
* The `If-Match` requirements are only requirements for the server (our standardisation target) and what the server has to do with requests. Maybe we can make that clearer in the wording and also clarify explicitly in the informative text that the server will send a 412 in case of a missing `If-Match` header. We may also add more guidance to clients in informative text.
* Shouldn't we also allow "*" as a value in If-Match (if the server wants to support this)? Currently that is not allowed.

**Comment by pvretano** [comment]
06-DEC-2021: @pvretano to review and update the Optimistic Locking clause accordingly.

**Comment by cportele** [comment]
Meeting 2022-06-06: @pvretano will correct the broken sentence in `REQ_etag-put-response` and then merge the PR. Any comments will be collected in new issues.
