### ISSUE TITLE
Implementations for new task "Schemas"

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-features#527]
> A new part "Schemas" will specify Schema resources for the features in a feature collections and will consider at least the following types of schemas in a consistent way: the queryable properties of the features that may be used in filter expressions; the returnable properties included in feature representations retrieved from the Features and Feature resource; the storage properties that are processed in requests mutating a feature; the sortable properties that may be used to sort features in Features responses. Existing specifications for Schema resources in OGC API Features standards should eventually be moved to this part.

Before we assign a new part number to a new task and start to work on a new document, we need commitments for three independent implementations for each proposed conformance class. 

If you have an interest in this extension, please consider to commit to implementing this extension and let us know in a comment to this issue.

Relevant links:

- [Initial proposal](https://github.com/opengeospatial/ogcapi-features/tree/master/proposals/schemas)
- [Issues related to this extension](https://github.com/opengeospatial/ogcapi-features/projects/11)

**Comment by pvretano** [comment]
CubeWerx commits to an implementation.

**Comment by cportele** [comment]
interactive instruments commits to implementing the extension in [ldproxy](https://github.com/interactive-instruments/ldproxy).

**Comment by jerstlouis** [comment]
Ecere commits to an implementation in its GNOSIS Map Server.

**Comment by cportele** [comment]
Code Sprint 2024-02-27: All three implementations exist, we can close this issue. We will update the implementation pages.
