### ISSUE TITLE
CQL: Spatial predicates supporting WKT geometry are too complex for "Simple CQL"

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-features#532]
I would like to see Spatial predicates and Temporal predicates in their own conformance class, not in "Simple CQL", as it currently groups together essential thing like property/value filters, with much less essential things such as clients describing and intersecting geometry in WKT.

It would make more sense to me for intersects to be grouped with that 'advanced spatial', as if services implement intersects then they likely can implement everything else easily. But if the server doesn't have a use case for WKT geometry provided by clients, it is a lot to implement that is all tied in together with the simple filters & logic.

While "Core" supports filters, those are subject to dataset attributes conflicting with defined query parameters, and generally speaking a `filter` query parameter feels like the more correct way to do filtering. The filtering also allows logical operators which Core does not support.

**Comment by cportele** [comment]
Meeting 2021-06-07: Since there were no objections, we will follow this approach.

**Comment by cportele** [comment]
PR #587 addresses the temporal operators
