### ISSUE TITLE
CQL: Consider renaming anyinteracts to tintersects

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-features#533]
If there is no strong requirement to leave CQL unchanged, consider renaming `anyinteracts` to `tintersects`, as the current name does not seem to carry its meaning of intersecting time, and will just confuse everyone.

**Comment by heidivanparys** [comment]
A similar request has been formulated earlier towards the "Filter Encoding 2.0" standard. From http://ogc.standardstracker.org/show_request.cgi?id=101

> 
> The title name of the AnyInteracts temporal operator is not immediately intuitive to users. By changing the title to TIntersects reflects terminology used in use cases and scenarios. For example:
> 
>  “...and the scheduled reservation activity time interval intersects with the subscription time interval.”

**Comment by cportele** [comment]
Meeting 2021-04-26: Define TDISJOINT based on OWL Time disjoint and TINTERSECTS and NOT TDISJOINT. This is analogous to the spatial operators.
