### ISSUE TITLE
Part3: LIKE is unnecessarily complex

### ISSUE THREAD

**Issue by jampukka** [opengeospatial/ogcapi-features#541]
I wonder if we could make the LIKE predicate simpler than what it is now in Part3 draft by removing the ability to change wildcard characters (WILDCHAR, SINGLECHAR, ESCAPECHAR) from the default values. There's very little benefit in having this ability at all or at least I'm having hard time seeing it.

I do agree we should have a case-insensitive version of LIKE in simple-cql. However I wonder if having a separate predicate for this (ILIKE for example) would be easier to implement?

**Comment by aaime** [comment]
Agree with @jampukka

**Comment by pvretano** [comment]
I mostly agree with simplifying LIKE.  However, I think ILIKE does not intuitively imply case less LIKE so I would prefer we just stick with the current setup.

**Comment by cportele** [comment]
I would prefer ILIKE, because that seems to be the way this is done in a number of SQL implementations.

**Comment by aaime** [comment]
By the way, I've found that LIKE's "NOCASE" keyword is also used in the "in" predicate. Seems again a bit complex, and also somewhat inconsistent, in that a "in" is just a shorthand for a chain of or-ed equality comparisons. But in an equality comparison, there is no way to express case insensivity. Should I open a separate issue for it?

**Comment by pvretano** [comment]
@cportele I don't like it there either ... but I am not religious about it ... and Oracle SQL does not define an ILIKE using UPPER() or LOWER() instead.
General questions for everyone ...
(1) Do we wanted case insensitive comparisons in core (i.e. simple CQL)?  I think yes.
(2) How should we do it consistently everywhere.  I say forget NOCASE and ILIKE and simply define a built-in function named UPPER() and/or LOWER() that people can inject anywhere they want case-less comparisons.  Any other proposals?

**Comment by cportele** [comment]
Meeting 2021-04-12: Current thinking:

- Remove options to change the WILDCHAR, SINGLECHAR, ESCAPECHAR values and keep them fixed.
- Case insensitive should be supported in Simple CQL
- Instead of (NO)CASE the definition of functions UPPER/LOWER enables also case insensitive comparisons for `=`etc, so this seems to be most flexible and consistent with SQL implementations.

**Comment by jampukka** [comment]
I agree with having case insensitive comparison(s) in simple-cql core (`http://www.opengis.net/spec/ogcapi-features-3/1.0/req/simple-cql`). One other thing about `UPPER()/LOWER()` solution is that it requires the service to support `http://www.opengis.net/spec/ogcapi-features-3/1.0/req/functions` which purposely (I think) is a separate conformance class.

It certainly does work better for other comparisons e.g. `=` and `IN` for example `LOWER(my_prop) = 'foo'` and `LOWER(foo) IN ('a','b','c')` but on the flip side it requires custom logic to handle it properly for just those equal-ly operations. Also once you start mixing in other functions it gets complicated really fast e.g. `SUBSTRING(LOWER(my_prop), 1, 3) = 'foo'` vs. `LOWER(SUBSTRING(my_prop, 1, 3)) = 'foo'` (that's obviously just more complicated way to write `LOWER(my_prop) LIKE 'foo%'` but I couldn't come up with better example on the spot but I hope you all get the point)

Also I think a function solution isn't as explicit as a separate operator (we could come up with a better name for it if `ILIKE` is not intuitive enough.

**Comment by cportele** [comment]
2021-05-10:

* Support for UPPER/LOWER would not imply support for the functions conformance class. INTERSECTS is a built-in function, too. The functions conformance class adds the resource that lists the functions that clients can use, like the queryables resource.
* It was not clear to those at the call what the complication is, if a server indicates that it supports other functions. @jampukka, could you clarify?
* There could be an OGC register of well-known functions. Currently this is not part of Part 3. But it would be a good idea to keep the idea as a future consideration.

**Comment by cportele** [comment]
Meeting 2021-06-07: In the meeting we were still of the opinion that having a general mechanism for case-insensitive predicates that is not restricted to LIKE is a good argument for the UPPER/LOWER approach. This also resolves the NOCASE modifier in the IN predicate. If there are still concerns about implementation complexity we could move this to a separate conformance class.

**Comment by jampukka** [comment]
I'm fine with the idea. Couple of questions still, which of these should be handled as case-insensitive comparisons:
1) `LOWER(myprop) = LOWER('foo')`
2) `LOWER(myprop) = 'foo'`
2) `LOWER(myprop) = 'Foo'`
3) `LOWER(myprop) = UPPER('foo')'`
4) `LOWER(myprop) = UPPER(myprop2)`
5) `LOWER(SUBSTRING(myprop, 1, 3)) = myprop2`

**Comment by cportele** [comment]
@jampukka - String comparisons are case-sensitive, but UPPER/LOWER can be used to normalize the case so that the comparison is effectively case-insensitive. So:

* Case 3, 4 and 5 will always evaluate to false
* Case 7 will only evaluate to true, if myprop has no uppercase characters
* Case 1 and 2 will evaluate to true, if LOWER(myprop) is 'foo'
* Case 6 will evaluate to true, if myprop2 has no uppercase characters and matches the myprop substring (converted to lowercase)

**Comment by jampukka** [comment]
That's what I was expecting and those are the only sensible results.

Could we still find a way for simple case-insensitive string comparisons (`=`, `<>`, `LIKE`, `IN`)? I can't think of a reason a client would use LOWER/UPPER in filter other than as a mean of achieving case-insensitive string comparisons, especially as it only applies to the filter and not the output.

While LOWER/UPPER obviously can solve the problem it's not the same as a "no-case" flag because I can't determine the intent behind the comparison. For example, say I've indexed the expression `LOWER(myprop)` in PostgreSQL which I would like to use when the client wants case-insensitive comparison on that property. Maybe for another collection I've indexed the expression `UPPER(myprop)` and would like to use that when client wants case-insensitive comparisons there. Now if client asks for `myprop LIKE 'foo%' NOCASE` or `myprop ILIKE 'foo%'` I can apply the knowledge of `UPPER(myprop)` and get the result efficiently from the database. But if the client asks for `LOWER(myprop) LIKE 'foo%'` then `UPPER(myprop)` index is no good. Sure I could index both expressions, but that's just one solution for one database engine, other datasources might have different ways of efficient case-insensitive string comparisons.

**Comment by pvretano** [comment]
@jampukka remember that CQL is simply way of expressing a filter at the API.  A implementation of the API will still have to translate that to an underlying query language.  If that language is SQL, the translation is easier since CQL is close to SQL.  However that does not mean that it will be a straight translation.  You may have to rewrite the predicate to deal with the optimizer intricacies of the underlying database or to deal with knowledge you have of the underlying mode such as an index on UPPER(myprop).  Another point, say we did implement ILIKE.  Well, Oracle does not implement ILIKE so if your underlying database was Oracle you would need to do such a translation anyway.

**Comment by jampukka** [comment]
Yes that's exactly my point. The issue is I'm not sure if I will be able to reliably "detect" that user wanted the functionality case-insensitive LIKE would provide. With ILIKE there's no such ambiguity. Yes I do still have to translate it to so that the underlying data storage also understands it but at least I know for sure what I'm translating.

**Comment by cportele** [comment]
Meeting 2021-06-14: UPPER/LOWER could lead to edge cases, in particular with non-ASCII alphabets - some code quality checkers raise warnings. We should select the one that has the fewest issues (it seems to be UPPER, but we need to research). We should include text that recommends how to make case-insensitive comparisons consistently. Probably even remove one of the two function (probably LOWER, keep UPPER). @pvretano will do a survey and update the PR.

**Comment by plutoscarab** [comment]
It seems like both UPPER and LOWER will have edge cases for some languages. Maybe what is needed is something more along the lines of Unicode case folding normalization which ILIKE could implement but UPPER or LOWER couldn't. http://unicode.org/reports/tr21/tr21-5.html#Caseless_Matching
