### ISSUE TITLE
Ambiguity around Next, Prev, and Offset in Features Core 1.0 Response

### ISSUE THREAD

**Issue by captaincoordinates** [opengeospatial/ogcapi-features#542]
[Features Core Part 1 1.0 Response section](http://docs.ogc.org/is/17-069r3/17-069r3.html#_response_6) appears to contain contradictory information and I am hoping for clarification on what exactly is intended.

This section includes the following **will** statement:

> If the server has any more results available than it returns (the number it returns is less than or equal to the requested/default/maximum limit) then the server will include a link to the next set of results.

There are also multiple statements around when a `Next` link **will** be included in a response.

Although the spec makes multiple references to an `offset` parameter, and makes mention of an approach similar to WFS 2.0's `startIndex` parameter, support for any kind of offset is not mandated through a **SHALL** requirement. The spec appears to say both
1) a conformant implementation will provide a link to the next set of results, but
2) a conformant implementation is not required to provide any way to advance through a result set that exceeds the `limit` parameter.

Can somebody please clarify what is the expectation for an implementation that complies with Features Core Part 1? pygeoapi - frequently described as this spec's reference implementation - uses an `offset` parameter.

**Comment by cportele** [comment]
See also #75.

The `next` link is required, there are no requirements on the details of the link URI. 

This supports implementations that use explicit URIs and expose the paging mechanics through an `offset` parameter, like it is used in examples. However, it is also perfectly valid to use opaque URIs for the next links that hide the information how the API handles paging. The choice will depend on the type of the feature datastore used by the tool/API. 

In general, clients should simply dereference the URI to the next page and not parse the URI.

An extension that specifies the `offset` parameter is on the list of potential future extensions.

Does this answer your question?

**Comment by captaincoordinates** [comment]
Yes, I think so, thanks.
