### ISSUE TITLE
Do we really need the /queryables endpoint in Part 3?

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-features#543]
Given that Part 4 defines the `/schema` endpoint with `type=create/replace/update` can't we just add `type=query` to get the queryables?
In other words, in Part 3, remove the `/queryables` endpoint, replace it with the `/schema` endpoint with `type=query` and define  appropriate requirements/recommendations for a simpler JSON Schema (e.g. no need to enum).

**Comment by cportele** [comment]
Yes, this is the [proposal](https://github.com/opengeospatial/ogcapi-features/tree/master/proposals/schemas) for consolidating all schema representations (currently in the proposal just with `type=queryables`, not `type=query`).

**Comment by jampukka** [comment]
I think we need to be careful not to create a dependency to an initial proposal for future extension. If we do require `GET /collections/{collectionId}/schema?type=queryables` in Part 3 then Schemas extension has very little room for any changes. Same goes for Part 4. I'd prefer if we had the Schemas pattern fixed before finalizing Part 4.

Would this affect both the global `/queryables` and the local `/collections/{collectionId}/queryables`? There aren't any plans for global `/schema` resource in the proposal for Schemas.

**Comment by cportele** [comment]
Agreed, we need to make sure we get the timing right and be careful with dependencies. In general, the idea is that Schemas should progress in sync with Part 4 through the process. We could also decide that we wait with finalizing Part 3 to avoid potential conflicts.

**Comment by pvretano** [comment]
@cportele type=create, type=update and type=queryables?  `query` sounds better to me and it is a real word! ;) ... but I am not religious about it!

**Comment by pvretano** [comment]
@jampukka @cportele perhaps we need to put schema into its own extension.

**Comment by cportele** [comment]
@pvretano `type=query` is fine with me.

Schema will have its own extension and consolidate all schema representations. It is one of the four new task that were approved.

**Comment by pvretano** [comment]
@cportele yes, I thought so, but just wanted to make sure.  The dependencies are cleaner that way ...

**Comment by cportele** [comment]
Meeting 2021-06-07: We should keep the queryables in the document and add a note that there may be another approach after the schema harmonization activity is complete that will supersede/deprecate the current approach.
