### ISSUE TITLE
Part 3: Remove the tokens T and F as boolean literals

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-features#545]
The boolean literals `true` and `false` are ok since they're reserved words in many languages, including many versions of SQL.  However, `t` and `f` are common variable names, and are completely redundant in this context.
We should probably remove `t` and `f` as boolean literals.

**Comment by aaime** [comment]
I would support removal, too.

**Comment by aaime** [comment]
Also, the BNF grammar available on the site also considers 1 and 0 as booleans, though the spec does not seem to corroborate:

https://github.com/opengeospatial/ogcapi-features/blob/master/extensions/cql/standard/schema/cql.bnf#L437

Pheraps those ought to be removed too.

**Comment by cportele** [comment]
2021-05-10: Remove `t`, `f`, `0`, `1`

**Comment by cportele** [comment]
Resolved by #590
