### ISSUE TITLE
Part 3: Change nocase to case

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-features#548]
Saying "nocase" instead of something like "case" introduces confusing double-negatives.  Perhaps we should just use `case` instead.  `case`=true means do the comparison taking case into account.  `case`=false means to the comparison caselessly.

**Comment by cportele** [comment]
Also see #541

**Comment by cportele** [comment]
Meeting 2021-06-07: This is obsolete, whatever we do, we won't keep CASE/NOCASE.
