### ISSUE TITLE
Array operator naming seems inconsistent, "ACONTAINS vs CONTAINED BY"

### ISSUE THREAD

**Issue by aaime** [opengeospatial/ogcapi-features#549]
I would go either for `CONTAINS`/`CONTAINED BY` or for `ACONTAINS`/`ACONTAINEDBY`

I'm guessing that that the A prefix has been added to avoid an overlap with spatial operators, but it should be consistent across the board (A stands for array and it's coaleshed in the same word, so why not attach the "by" at the end, instead of having a space in between?)

In terms of consistency across data types, for temporal operators there is a  `TCONTAINS`, whose inverse is `DURING~, for spatial there is `CONTAINS`, whose opposite is... missing?

**Comment by cportele** [comment]
Meeting 2021-04-12: So far, the rule has been to use the name and only add a prefix, if there is a conflict. But that does not have to stay that way. Make a decision after the review process is closed. We will try to organise a call with all commenters after the review period to get a consensus about resolving the most critical issues (including backwards compatibility with CSW CQL).

**Comment by cportele** [comment]
See #562

**Comment by cportele** [comment]
Meeting 2021-06-07: This issue will be resolved by #562 and can be closed.
