### ISSUE TITLE
CQL one letter "keywords"

### ISSUE THREAD

**Issue by aaime** [opengeospatial/ogcapi-features#550]
Looking at the CQL BNF, and in particular, the [keywords](http://docs.ogc.org/DRAFTS/19-079r1.html#cql-text), there is a number of short (one letter) tokens that (I believe) were not present in the CSW specification, such as:

- T/F (already discussed in another issue)
- B and X
- E
- Z

Normally the keywords of a language cannot be used for anything else, for example, they cannot be property names (or at least, they would have to be double quoted). 

Specifically for `B` and `X`, they are used for `bitstring` and `hexstring`. The specification is not even talking about them, I don't see examples either. Given it's already possible to specify escape chars to handle complex names in CQL, I'm guessing they are there to allow specifying binary values? Is this actually necessary? If so, should it be in the scope of a "Simple CQL"?

`Z` is used as part of time specifications. But does that make it a keyword? Should a "Z" property be double quoted?
Same goes for `E`, used to specify numbers in scientific notation. I'm guessing the context should tell the parser if we are talking about a variable name or a number, e.g.. `E > 1.436E10`, first one is a property name, the second is used as part of a scientific number.

**Comment by cportele** [comment]
Meeting 2021-04-12: The comment makes sense and we think the proposal should be implemented. @pvretano will write a PR.

**Comment by cportele** [comment]
Implemented by recent commits
