### ISSUE TITLE
Potential error in CQL-JSON schema: property vs propertyName

### ISSUE THREAD

**Issue by constantinius** [opengeospatial/ogcapi-features#552]
The schema (both json-schema and the OAPI one) define the `propertyRef` structure as such:

```
"propertyRef": {
     "type": "object",
     "required": ["property"],
     "properties": {
        "propertyName": { "type": "string" }
     }
 },
```

It states that the `property` property be present which is missing in the available properties. The `propertyName` instead is never used, also the examples reference the `property` only.

**Comment by cportele** [comment]
Thanks! Yes, "propertyName" is an error and has to be changed to "property".
