### ISSUE TITLE
CQL: inconsistencies between req 18G with schemas

### ISSUE THREAD

**Issue by constantinius** [opengeospatial/ogcapi-features#553]
Requirement 18G is as such:
> If the SINGLECHAR modifier is not specified, the default singlechar character SHALL be "_".

The json-schema and OAPI schema define the `"."` character to be the default.

**Comment by cportele** [comment]
"." is the single wildcard character in regular expressions, but this is the simpler/different LIKE operator and in LIKE the single wildcard character is "_".

See also #541.

**Comment by cportele** [comment]
Meeting 2021-07-19: No change as discussed in the comment above. Close.
