### ISSUE TITLE
CQL: JSON Schema for CQL: timeString -> instantString, periodString -> intervalString, ...

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-features#556]
The terminology used in Annex C, JSON Schema for CQL should match the terminology used in the rest of the document, in particular clause 8.7 Temporal predicates, 9.3 Requirements Class "Enhanced Temporal Operators" and Annex B: CQL BNF, where "instant" and "(time) interval" are used.

So in Annex C, all occurrences of `timeString` should be replaced by `instantString`, all occurrences of `periodString` should be replaced by `intervalString`, all occurrences of `typedTimeString` should be replaced by `typedInstantString` and all occurrences of `typedPeriodString` should be replaced by `typedIntervalString`.

**Comment by cportele** [comment]
Meeting 2021-06-07: Yes, we should use consistent terminology.
