### ISSUE TITLE
CQL: inconsistency regarding evaluation of filter expressions to null?

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-features#557]
i. Abstract:

> The filter expression always evaluates to true, false **or null**

4.1.4 predicate:

> set of computational operations applied to a data instance which evaluate to true or false

(no mention of null here)

8.2 CQL filter expression:

> A predicate is an expression that evaluates to the Boolean values of TRUE or FALSE **or that evaluates to the value NULL** when dealing with unknown values.

Requirements 10, 14, 17, 18 (and more) mention filter expressions evaluating to `TRUE` and to `FALSE`, but not to `NULL`.

Is there an inconsistency? Can a filter expression evaluate to NULL or not, within the context of this standard?

**Comment by pvretano** [comment]
@heidivanparys yes there seems to be.  No, a filter expression should only evaluate to true (resource is in the result set) or false (resource is not in the result set).  I've assigned this to myself to take a look at all mentions of NULL and make sure they are consistent.
