### ISSUE TITLE
CQL: definition of resource and web resource / source for publisher

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-features#558]
I would suggest using the following instead:

4.1.7 resource
entity that might be identified ([Dublin Core Metadata Initiative - DCMI Metadata Terms](
https://www.iso.org/obp/ui/#iso:std:iso:15836:-2:ed-1:v1:en:term:3.1.10))

4.1.8 web resource
resource that is identified by an HTTP URI

I am not sure the definition of resource can be found on https://www.dublincore.org/specifications/dublin-core/dcmi-terms/ but the ISO version defines "resource" like that, see link above.

Perhaps some notes can be added referring to the dissertation in the current definition, if needed. Or some of the text in https://www.rfc-editor.org/rfc/rfc3986.html on "resource".

In addition: add perhaps the following reference (or similar) to the bibliography (won't ISO require that?):
[DCMI] DCMI USAGE BOARD. DCMI Metadata Terms [online]. DCMI Recommendation. Dublin Core Metadata Initiative, 20 January 2020. Available from: http://dublincore.org/documents/dcmi-terms/. This standard is also published as ISO 15836:2019, 
Information and documentation — The Dublin Core metadata element set.

**Comment by cportele** [comment]
Meeting 2021-06-07: @cportele will investigate.

**Comment by cportele** [comment]
The current definition is based on what is in Common Core. I see no problem changing the definitions to the ones proposed. Personally, I do not think we need to add notes.

If Common eventually becomes a standard, there may be a push to use the definitions from Common, but that could also be handled in the future.

**Comment by cportele** [comment]
Meeting 2021-07-05: We will make the change in Part 3 (and hope the Common will make the same change in response to https://github.com/opengeospatial/ogcapi-common/issues/240, cc @cmheazel).
