### ISSUE TITLE
CQL: URI escaping / percent-encoding?

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-features#561]
Should the standard say something about URI escaping, or percent-encoding, as it is called in https://www.rfc-editor.org/rfc/rfc3986.html#section-2.1, when using CQL Text? See e.g. example 10 and the `filter-crs` parameter in there.

**Comment by cportele** [comment]
Meeting 2021-06-07: In general it should be well-understood, but an informative reminder can be helpful.
