### ISSUE TITLE
CQL: Naming of operators

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-features#562]
As the naming is not yet decided 100% according to https://github.com/opengeospatial/ogcapi-features/issues/549#issuecomment-817877359: personally I would prefer the following, for consistency...:

- prefix "s" for all **s**patial operators
- prefix "t" for all **t**emporal operators
- prefix "a" for all **a**rray operators

**Comment by cportele** [comment]
2021-05-10: Use consistently prefixes "s_", "a_" and "t_" for spatial, array and temporal operators.

**Comment by cportele** [comment]
PR #587 addresses the temporal operators

**Comment by aaime** [comment]
Given the language is deviating from the CQL as defined in the CSW extension, I would suggest to also change the name of the extension to avoid confusion. "CQL2"? "API CQL?"? Maybe "AQL" (API Query Language).

When GeoServer added extra behavior to the original CQL, we dubbed the result ECQL (Extended CQL). However, those were simple extensions and a valid CQL statement was also a valid ECQL. In this case the deviation is backwards incompatible.
Oh, I know... "NoCQL"? Just kidding!!
