### ISSUE TITLE
CQL: requirement /req/filter/filter-crs-param: HTTP status code

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-features#563]
Requirement /req/filter/filter-crs-param, subrequirement C: 

> The server SHALL return an error, if it does not support the CRS identified in `filter-crs` for the resource.

Should that be the following in order to be consistent with /req/crs/fc-bbox-crs-valid-value and /req/crs/fc-crs-valid-value?

The server SHALL return HTTP status code 400, if it does not support the CRS identified in `filter-crs` for the resource.

**Comment by cportele** [comment]
Meeting 2021-06-07: This should not be stated in the Filter req class, which will be used by other specs beside Features. We should add the 400 requirement in the Features Filter req class.
