### ISSUE TITLE
CQL: ISO 8601-2 - example 2: open end time interval

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-features#564]
The last example of the temporal geometry examples seems to use the ISO 8601-2:2019 notation for open end time interval: `2019-09-09/..` and `[ "2019-09-09", ".." ]`

Is a dependency to the ISO 8601 standard missing? In particular, is [ISO 8601-2](https://www.iso.org/obp/ui/#iso:std:iso:8601:-2:ed-1:v1:en) a required dependency, for supporting "time intervals with open or unknown starts or ends"?

RFC 3339 refers to (older versions of) ISO 8601 but states

> Date and time expressions indicate an instant in time. Description of time periods, or intervals, is not covered here.

and RFC 3339 does not cover the[ second part of the latest ISO 8601 standard](https://www.iso.org/obp/ui/#iso:std:iso:8601:-2:ed-1:v1:en), that was published in 2019 and is no revision of an earlier ISO 8601-2 but completely new.

**Comment by cportele** [comment]
Meeting 2021-06-07: Yes, it is missing (also in Part 1).
