### ISSUE TITLE
CQL: closed-closed vs closed-open intervals

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-features#566]
The CQL standard does not mention anything about [closed time intervals](https://mathworld.wolfram.com/ClosedInterval.html) vs [half-closed time intervals](https://mathworld.wolfram.com/Half-ClosedInterval.html), nor does the Time Ontology it seems. The only thing is indirect: ISO 8601-1 says for [time interval](https://www.iso.org/obp/ui#iso:std:iso:8601:-1:ed-1:v1:en:term:3.1.1.6):

> part of the time axis limited by two instants and, unless otherwise stated, the limiting instants themselves

Whether the end instant of a time interval is part of the interval itself will have consequences for the behaviour of the temporal relations MEET/METBY, BEGINS and ENDS.

Background info:
Time intervals are used for associating a [valid time interval](https://link.springer.com/referenceworkentry/10.1007%2F978-1-4614-8265-9_1066) and a [transaction time interval](https://link.springer.com/referenceworkentry/10.1007/978-1-4614-8265-9_1064) to a version of a feature in order to implement [bitemporal history](https://martinfowler.com/articles/bitemporal-history.html) for features. Common practice is to use closed-open time intervals for this, this is e.g. the case for bitemporal databases implementing the SQL standard (ISO/IEC 9075), see also [ISO/IEC TR 19075-2:2015](https://standards.iso.org/ittf/PubliclyAvailableStandards/c060394_ISO_IEC_TR_19075-2_2015.zip). When implementing an API on top of a database with temporal data, we must be able to take closed-open time intervals into account.

**Comment by cportele** [comment]
Since we use/reference ISO 8601, the rules of that standard applies, i.e., time intervals are closed. This is stated in Part 1 in the context of the `datetime` parameter:

> For time intervals this includes the start and end time.

We need to restate this in Part 3.

It is unfortunate that different standards use different semantics, but this is the way it is. For servers using an SQL backend, they need to map this to a SQL query that fits the SQL definition, e.g. add a second at the end, if the temporal resolution is one second. We should also discuss this in a note.

**Comment by heidivanparys** [comment]
> For servers using an SQL backend, they need to map this to a SQL query that fits the SQL definition, e.g. add a second at the end, if the temporal resolution is one second. We should also discuss this in a note.

The simplest solution would be to combine instant-instant comparisons - as we do today in SQL queries - instead of using operators operating on time intervals and having to a second/a day/sht else (depending on the temporal resolution).
