### ISSUE TITLE
CQL: usefulness of the current Simple CQL regarding temporal predicates

### ISSUE THREAD

**Issue by heidivanparys** [opengeospatial/ogcapi-features#570]
I am wondering how useful the current Simple CQL requirements class is regarding temporal predicates, as the only relationship supported is `ANYINTERACTS`. I understand that implementing all relationships from Allen's interval algebra is too much, but, as also argued in #565, I think that a distinction should be made between

- instant-instant relations
- instant-interval relations
- interval-interval relations

I would like to suggest including instant-instant relations in Simple CQL, i.e. supporting before, equals and after for instants. Isn't it the case that any other relation involving intervals actually can be expressed by comparing their start and end instants?

**Comment by cportele** [comment]
Meeting 2021-04-26: We agreed to add after, before and equals for instants.

**Comment by jampukka** [comment]
Agree Simple CQL core should define capability to compare instant-instant either with <,>,= or t_before, t_after, t_equals. It would be problematic if such simple comparisons for dates and date-times were only available in temporal_operators conformance class.
