### ISSUE TITLE
More CQL comments ...

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-features#578]
There don't seem to be any monadic Positive and Negate operations: -A, +A.  While the Positive operation is effectively a no-op, Negate is useful and just about all languages have it.  To simulate it, one would need to translate -A to 0-A.

The JSON schema definition for "divExpression" has «"required": ["*"],» instead of «"required": ["/"],».

The JSON syntax includes operation symbols like "+" and "*" but not "<" and ">=", using text abbreviations instead.  This should be consistent.

The JSON comparison operators use FORTRAN terms "eq", "gt", and "lt", but not "ge" and "le".

JSON doesn't include the "ne" comparison operator, even though the text syntax and just about every other language does.  This creates the awkward need to translate A <> B into NOT(A == B) and vice-versa when building expressions.  These representations have different parse trees and might spoil some optimizations, such as with database indexes.

**Comment by cportele** [comment]
Meeting 2021-06-07: @pvretano is working on PR.
