### ISSUE TITLE
Part 1 -- conformance class OAS 3 uses inconsistent URIs

### ISSUE THREAD

**Issue by philvarner** [opengeospatial/ogcapi-features#580]
In the conformsTo example in 7.4.2. Response, the OAS conformance class is 

`http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas30`

but in A.7. Conformance Class OpenAPI 3.0, the value is

`http://www.opengis.net/spec/ogcapi-features-1/1.0/conf/oas3`

(without a `0` at the end)

**Comment by cportele** [comment]
Thank you. This has already been fixed (issue: #317, PR: #345). See the [Editor's draft](http://docs.opengeospatial.org/DRAFTS/17-069r4.html). The fix will be included in a future 1.0.1 release.

**Comment by philvarner** [comment]
Thanks, now that I know about the draft, I'll check that before filing issues.
