### ISSUE TITLE
CQL: wildcard queryables or definable queryable/term behavior

### ISSUE THREAD

**Issue by philvarner** [opengeospatial/ogcapi-features#582]
First, my understanding from the spec is that only properties defined in queryables are permitted to be used in filter expressions where `propertyName` tokens may appear. If a token not defined in queryables is used, an error should be thrown. 

I love the idea of being able to advertise what terms are legal, but also see significant limitations when dealing with dynamic items.

Since this is the case, it makes it difficult for collections of items that have disparate groups of properties to present a correct queryables list. For example, you could possibly have to perform an aggregation over all of the Items to union together all of the property names in them if you wanted to allow query over any of them.  This is hard for dynamic collections of items. 

Ideally, there would be a way to advertise and permit users to query over queryables that may not be defined. For example, if they see a field 'properties.cloud_cover', they can attempt to query over that field even if it's not in queryables, and it may or may not work. 

One option would be to allow wildcard queryables, like `*` or `properties.*`, which indicate that a user can use any property (for `*`) or any property in the `properties` object of an item in a filter expression. 

Another option would be to allow the server or client to determine the semantics of the use of undefined queryables, such that the queryables is only a recommendation for what can be used as a term, but other terms can also be used without immediately returning an error b/c they weren't defined in queryables.

**Comment by cportele** [comment]
Meeting 2021-06-21: @philvarner - But how would a client determine which properties can be used in a filter? Out-of-band information? A query first to see what the data contains?

**Comment by cportele** [comment]
@philvarner - Could you clarify the issue / proposal? See the open questions from above:

> But how would a client determine which properties can be used in a filter? Out-of-band information? A query first to see what the data contains?

Thanks!

**Comment by philvarner** [comment]
I was thinking out-of-band. The key idea here was there was a way to have semantics where clients can pass arbitrary properties without the server needing to reject them because they that aren't advertised as queryables.

**Comment by cportele** [comment]
Meeting 2021-08-30: We can support this by leveraging the `additionalProperties` member. If set to `false` the server would not accept any property that is not explicitly mentioned, but if set to `true` this would be like the `*` proposal and any property can be used in an expression (and evaluate to `null`, if the property does not exist for a feature). We would not define the behaviour if the more complex JSON Schema options for additional properties would be used. @cportele will draft a PR.

**Comment by jampukka** [comment]
Is there any use case for allowing the client to tell the server how it would like the server to act? e.g. "I don't care if you ignore one or more of these filtering expressions, just don't return an error". The default would be to return an error as that's least surprising and in line with Part 1: Core section 7.6.

I'm perfectly fine with the suggested solution, just something that came to my mind.

**Comment by cportele** [comment]
@jampukka - In the design it is only the server (the data publisher) that decides the behaviour. If there is a need in the future to standardize how servers should accept client preferences when processing query requests, I think the ["handling" preferences in the Prefer header](https://datatracker.ietf.org/doc/html/rfc7240#section-4.4) could be used.
