### ISSUE TITLE
Part 3: filtering within nested fields

### ISSUE THREAD

**Issue by philvarner** [opengeospatial/ogcapi-features#583]
This issue is about how to query over nested fields, possibly with intermediate lists.

Using this STAC snippet as an example:

```json
"features": [
    {
      "type": "Feature",
      "assets": {
        "B5": {
          "eo:bands": [
            {
              "common_name": "nir",
              "name": "B5"
            }
          ],
          "href": "https://landsat-pds.s3.us-west-2.amazonaws.com/c1/L8/060/247/LC08_L1TP_060247_20180905_20180912_01_T1/LC08_L1TP_060247_20180905_20180912_01_T1_B5.TIF",

          "type": "image/tiff; application=geotiff; profile=cloud-optimized",
        }
      }
]
```

One common type of filter is "only Items that have in their `assets` object a value that has an `eo:bands` value that contains a `common_name` value of "nir". Quite a complex query!

I see two approaches as CQL is defined now:

1 - you can define a "synthetic" queryable that refers to those dict/map keys, e.g., queryable "bands" means Item.assets.*.eo:bands , and then write`'nir' IN bands` -- the implementation is then responsible for generating the appropriate query to support that
2 - define a function that takes an Item and a key, and resolves to a boolean that represents the aforementioned test

Are these legal and/or reasonable approaches to this?

**Comment by pvretano** [comment]
@philvarner, yes that was one of the use cases envisioned for queryables but wouldn't the synthetic queryable be something like "common_band_name" means "item.assets.*.eo:bands.common_name" and the predicate would be `common_band_name='nir'`?

**Comment by philvarner** [comment]
> @philvarner, yes that was one of the use cases envisioned for queryables but wouldn't the synthetic queryable be something like "common_band_name" means "item.assets.*.eo:bands.common_name" and the predicate would be `common_band_name='nir'`?

I was thinking bands would be an array of string, as if you'd done a map operation over it to collect all the common_names that were defined. Otherwise, you would have the unusual semantics for `=` that both `common_band_name='nir'` and `common_band_name='blue'` could be true if an Item had an asset that was nir and another that was blue.

Thanks for confirming that that's a reasonable way to handle queryables.

**Comment by pvretano** [comment]
@philvarner ah, OK ... makes sense.   

You should be aware of issue #527 too.  Queryables really represent a view on the underlying information model that is suitable for querying ... or ... queryables represent the query schema of the collection.  There are other schemas too ... the create schema, the update schema, the sortable schema, etc.  Issue #527 and the proposal therein is meant to address these various schema requirements.  Practically it should not have an effect on the way things work.  The only difference would probably be instead of `GET /collections/{collectionId}/queryables` you would do `GET /collections/{collectionId}/schema?type=queryables`.  We have not discussed whether we should fold this into CQL now ... probably not, but I thought you should be aware of this related issue.

**Comment by lossyrob** [comment]
I think [jq](https://stedolan.github.io/jq/manual/#Basicfilters) filtering has some good syntax defined for digging into things like JSON lists that may be appropriate here. It can get pretty complex, but something to think about.

For example, if I have json

```javascript
{
  "features": [
    {
      "type": "Feature",
      "assets": {
        "B5": {
          "eo:bands": [
            {
              "common_name": "nir",
              "name": "B5"
            }
          ],
          "href": "https://landsat-pds.s3.us-west-2.amazonaws.com/c1/L8/060/247/LC08_L1TP_060247_20180905_20180912_01_T1/LC08_L1TP_060247_20180905_20180912_01_T1_B5.TIF",
          "type": "image/tiff; application=geotiff; profile=cloud-optimized"
        },
        "thumbnail": {
          "href": "https://landsat-pds.s3.us-west-2.amazonaws.com/c1/L8/060/247/LC08_L1TP_060247_20180905_20180912_01_T1/thumnb.gif"
        }
      }
    }
  ]
}
```

I can pipe that into  

```
> jq '.features[].assets[]."eo:bands"[]?.common_name'
```

To get a list containing just `nir` as output.

tbh it took some head scratching to figure out that syntax - it usually does with getting the right jq syntax - but it's at least a starting point on how to define a queryable that descends into a complex object past nested lists and objects.

**Comment by philvarner** [comment]
> @philvarner ah, OK ... makes sense.
> 
> You should be aware of issue #527 too. Queryables really represent a view on the underlying information model that is suitable for querying ... or ... queryables represent the query schema of the collection. There are other schemas too ... the create schema, the update schema, the sortable schema, etc. Issue #527 and the proposal therein is meant to address these various schema requirements. Practically it should not have an effect on the way things work. The only difference would probably be instead of `GET /collections/{collectionId}/queryables` you would do `GET /collections/{collectionId}/schema?type=queryables`. We have not discussed whether we should fold this into CQL now ... probably not, but I thought you should be aware of this related issue.

I think what this means for STAC is the want to define a standard set of queryables (maybe per extension) that define how these deeply-nested structures map to propertyName terms. I'm going to need to think more about that.

**Comment by cportele** [comment]
Meeting 2021-07-19: @cportele to draft a response and explain with examples how one can use queryables to filter on properties in sub-objects.

**Comment by cportele** [comment]
@philvarner 

For your case you could define a queryable `common_band_names` defined as an array of strings

```yaml
description: an array of common band names included in the assets
type: array
items:
  type: string
```

Internally this could be mapped to the following JSON Path for a feature object (`f`):

`f['assets'][*]['eo:bands'][*]['common_name']`

I am just using JSON Path here to clarify the mapping. An implementation would use a mapping that fits its backend datastore, but these details are hidden from the user.

You can now use the array predicates to filter with the queryable. Examples using the text encoding:

* `common_band_names A_CONTAINS [ 'nir' ]` - includes at least a 'nir' band
* `common_band_names A_EQUALS [ 'nir', 'blue' ]` - 'nir' and 'blue' exist for the feature, but no other band

Does this help?

We may want to consider to include an example like this in the document to illustrate the queryables and highlight that they can be used to simplify querying and are not restricted to properties that exist one-to-one in the response encoding of the feature. What do you think, @pvretano? I could create a PR for this.

**Comment by philvarner** [comment]
That sounds like a reasonable solution to me. An example in the docs would be great.

**Comment by pvretano** [comment]
@cportele @philvarner I'll add the example above into the document.
