### ISSUE TITLE
Part 2, recommendation 1 URI pattern formatted as a link

### ISSUE THREAD

**Issue by PeterParslow** [opengeospatial/ogcapi-features#588]
the pattern "http://www.opengis.net/def/crs/{authority}/{version}/{code}" should not really be formatted as a link, because it is a pattern, not an instance - there is no expectation that clicking it should lead anywhere.

Issue present in both http://docs.opengeospatial.org/is/18-058/18-058.html and http://docs.opengeospatial.org/DRAFTS/18-058.html

**Comment by cportele** [comment]
I will create a PR that stops rendering the templates as clickable links. 

(This refers to Part 2, not Part 1.)

**Comment by cportele** [comment]
Please note that https://docs.ogc.org/is/18-058/18-058.html and the obsolete https://docs.ogc.org/DRAFTS/18-058.html will stay as they are, it will only affect the editor's draft at https://docs.ogc.org/DRAFTS/18-058.html and future documents.


https://docs.ogc.org/DRAFTS/18-058r1.html

**Comment by PeterParslow** [comment]
Apologies for naming the wrong part in the issue title! I have now changed that.

**Comment by cportele** [comment]
This is now fixed in the Editor's Draft: https://docs.ogc.org/DRAFTS/18-058r1.html#rec_crs_crs-format-model
