### ISSUE TITLE
Allow PUT to create resources?

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-features#595]
This is revisiting #329. The topic came up again during the May 2021 sprint in the context of styles. See https://github.com/opengeospatial/ogcapi-code-sprint-2021-05/issues/36. 

At least for the general requirements class, a mechanism is needed to support a client proposal for an identifier, if the server wants to support it. PUT would be a natural mechanism for this.

The feature-specific requirements class could still restrict creating features to POST.

**Comment by pvretano** [comment]
06-DEC-2021: ODATA does allow you to create new resources with a PUT if the resource does not have autogenerated identifiers.  However, ODATA does not have a mechanism to inspect the resource to see of it has autogenerated identifiers.  @cportele pointed out that we could add a key to the collection object to indicate whether autogenerated id's are available or not.  A similar use case are RDBMS's where you can have autogenerated primary keys in some cases.  ODATA reference: https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part1-protocol.html#_Toc31358981

**Comment by cportele** [comment]
Meeting 2022-09-12: @cportele will write a PR.
