### ISSUE TITLE
clarify handling of date/timestamp instants in CQL

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-features#602]
Open issue from the discussion in PR #587:

Include date or date-time handling in the comparison operators like `<` or `>` (textual description, examples, ATS). 

This should work with SQL backends, but will it create issues for NoSQL backends (MongoDB, Couchbase, ElasticSearch, GQL, GraphQL, etc)? @pvretano will investigate. If others would like that other backends should be considered, let us know here. Note there does not have to be a one-to-one mapping, there will always be parsing and processing involved.

**Comment by pvretano** [comment]
* All SQL databases support standard comparison operations with date/datatime/timestamps
* Cassandra (via CQL) behaves like SQL
* Couchbase "N1QL does not support the Date data type; however N1QL does provide a full range of functions which you can use to manipulate dates. See [Date Functions](https://docs.couchbase.com/server/current/n1ql/n1ql-language-reference/datefun.html) for more information."
* Elasticsearch supports full date math with comparison operators (and ES has a SQL interface too)
* GraphQL support date comparisons using their standard comparison operators
```
queryPost(filter: {
  title: { allofterms: "GraphQL" },
  datePublished: { ge: "2020-06-15" }
} ) { ... }
```

**Comment by cportele** [comment]
Meeting 2021-07-19: This supports the idea to support the standard comparison operators on instants, so we will make the change.
