### ISSUE TITLE
CQL and Apache Cassandra ...

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-features#609]
Just an FYI, Apache Cassandra also uses the acronym "CQL" presumably for "Cassandra Query Language".  There is also a command line tool named cqlsh.  May cause some confusion in the market at large.  So, the trend to rename CQL to CQL2 might be an even better idea in this context!

**Comment by cportele** [comment]
Meeting 2021-07-19: Agreed. Will be addressed by #603, so we can close here.
