### ISSUE TITLE
Add Abstract Test Suite

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-features#617]
* [x] Part 3
* [x] CQL2

**Comment by cportele** [comment]
I have been pondering how to write the abstract test suite for CQL2. This is not trivial, because to properly test the requirements we need to be able to evaluate that the result of an evaluation matches the filter expression, but we cannot assume that the queryables are also part of the response. In addition, to assess the implementation of some requirements (e.g., case folding) the test needs to know the data.

With just the knowledge about the queryables and their data types, we can only create general tests that construct valid filter expressions for a set of queryables and then tests that these are evaluated without an error. 

But this does not fully test the current requirements. The only way that I see how to properly test the requirements is to also have (conditional) tests with some (small) test dataset that covers all aspects and where the queryables are properties of the features. In instances where this data is loaded, we could perform tests with good coverage of the requirements.

I have been looking for a dataset that is available under an open data license, which has point/line string/polygon data, with string, floating point, integer, boolean, timestamp and date properties and with accents in some strings, but I have not been very successful. For example, the Natural Earth data does not include any timestamp or date properties.

Another option would be to simplify the requirements to only mandate that a filter expression that is valid for some set of queryables is evaluated, but move the description how the operators work to informative text.

Any thoughts or ideas?

**Comment by aaime** [comment]
Start with Natural Earth 110m set, add the missing attributes (they don't strictly need to have realistic values, it's a test dataset), package as a GeoPackage and distribute? Just thinking out loud.

Another potential source of data is the [OSM GeoPackage downloads](https://download.osmdata.xyz/), they do seem to have a last updated column.

**Comment by cportele** [comment]
Thanks, @aaime, I have used the approach (using some NE 110m layers and adding some attributes).

I still have to work on 5 conformance classes, but it would be good to have some eyes on the pull request #684 and get feedback, if this is going in the right direction. @pvretano, could you have a look, too, and let me know?
