### ISSUE TITLE
Array operators defines operator as "A_CONTAINED BY" but should it be "A_CONTAINED_BY"?

### ISSUE THREAD

**Issue by philvarner** [opengeospatial/ogcapi-features#643]
Array operators defines operator as `A_CONTAINED BY` but should it be `A_CONTAINED_BY` (underscore instead of space)?

**Comment by pvretano** [comment]
06-DEC-2021: Simple editorial fix @pvretano will check and fix if necessary.

**Comment by cportele** [comment]
I checked and could not find `A_CONTAINED BY` anymore. The space has been removed (and not replaced with an underscore), consistent with the style used in other operator names (see the temporal predicates).

**Comment by cportele** [comment]
Meeting 2022-01-17: Confirmed that all cases have been changed already (A_CONTAINEDBY). We can close the issue.
