### ISSUE TITLE
CRS support beyond WGS84 lon/lat

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-features#65]
Discussed in the Gitter chat during the [WFS 3.0 hackathon](https://github.com/opengeospatial/wfs3hackathon):

@aaime: I'm reading the spec but not understanding CRS treatment... on some parts it seems like it would be ignorable, in others that everything should default to CRS84... any clue?

@cportele: CRS handling in the Core is only a placeholder for future extensions. In the Core it is always WGS84 lon/lat.

@aaime: what about data that is some other CRS? Should it be left as is? Reprojected to WGS84?

@cportele: Reprojected to WGS84

@aaime: Agh... that's bad for all data in some other datum, the precision loss is is significant... does that mean WFS3 core is not for public administrations? (in Italy for example WGS84 data delivery is an extra, projected systems are the mandatory ones) and unfortunately, projected systems not even based on WGS84, but some other datum

@hannesaddec: @aaime and imagine one wants to make to display on a epsg:3035 map... are we projection than twice ?

@cportele: It is the same in Germany (and most of Europe). If high-precision is needed, the core will not be sufficient and an extension is needed. Support for additional CRS is one of the extensions we will be looking at this year. A key problem: How to encode data in JSON? GeoJSON is always WGS84 lon/lat...

@hannesaddec: only in the new GeoJSON specs..
2008 (yes) vs 2016 (restricted to wgs84 with a backdoor): However, where all involved parties have a prior arrangement, alternative coordinate reference systems can be used without risk of data being misinterpreted.... https://tools.ietf.org/html/rfc7946#page-12....

@cportele: Yes, that has been discussed to great length - if you use it in any other CRS all your users need to be aware of that - and their libraries would need to support that, too. I do not think this is the situation for most public WFSs where users may not be known in advance. So, yes, you may use a WFS with GeoJSON in other CRSs, but I do not see this as an approach to take in a conformance class of the standard.

I guess one approach would be to specify a new JSON encoding that is basically the GeoJSON encoding, but adds a capability to specify a CRS. This could not be called GeoJSON, but would have to use a new name (if the IETF licensing rules allow that approach). In a way this is similar to the approach in GeoSPARQL for WKT where GeoSPAQL specifies how to state the CRS for a WKT geometry.

@aaime: the WFS specification could add that "prior arrangement" between server and client, as an extra attribute, if the client has to explicitly ask for a CRS other than WGS84, there is probably not going to be confusion
Looking at the spec, I don't see anywhere an indication that using a different CRS would make it not geojson anymore, they explictly discuss the loophole instead of denying any other CRS usage

@cportele: I understand that, but having a geometry serialization that does not have a fixed CRS or a capability to declare the CRS of the coordinates seems to be a hack / "broken".

@aaime: the problem happens if you download the data in the context of the protocol, store it, and then give it to some other software outside of the arrangement
the real issue is in GeoJSON, the format became useless in a lot of applications due to the fixed CRS....

@pduchesne: +1 on having the core spec say that a CRS query parameter /should/ be supported, and if supported and specified the returned geojson /must/ be using that CRS. But since the geojson spec mandates the use of WGS84, wouldn't we have to return both geometries, in the requested CRS and in WGS84 ? To me adding an extra attribute (like 'projected_geom') doesn't break the spec, but changing the semantic of the existing 'geometry' attribute is another story.

@aaime: "doubling" the size of the payload will likely make many cry out loud

@pduchesne: indeed

**Comment by cportele** [comment]
To be discussed again. I think we need to address this soon. I see two options:
* Support a crs parameter in the core in a separate conformance class.
* Create a small extension that supports a crs parameter (asap).

My preference would be the second option, also to have a separate context for the GeoJSON / CRS discussion (separate from of the Core), which I am sure will be lengthy...

**Comment by rcoup** [comment]
My $2:

1. Specify _how_ to select a CRS in the core, and what to do if an invalid/unavailable CRS is requested. Otherwise we're kinda throwing the baby out with the bathwater with respect to geospatial here.
2. Default to WGS84 lon-lat (CRS84?), make it mandatory to implement.
3. Write an extension (promptly) saying how CRSs other than WGS84 should be dealt with, and how a server should list CRS options.
4. with respect to GeoJSON... if I call `/mydata/` and get GeoJSON back with CRS84, that's the default and fully compliant with the GeoJSON spec. If I call `/mydata/?crs=EPSG:2193` as a client I'm explicitly _asking_ for it in another CRS, and so IMO the "prior arrangement" clause in the GeoJSON spec applies.

**Comment by aaime** [comment]
Whatever you do, "triple pretty please" do not "refer axis order to the authority". Allow the server to clearly advertise what the order is and maybe bake it in the response as well.

**Comment by cportele** [comment]
Discussion in web-meeting 2018-03-12: Keep it outside of the core (consistent with the Spatial Data on the Web Best Practices and GeoJSON). Coordinate order in general is format dependent and it is unclear what we can state in general. @pvretano will draft the extension and look into this (the new ISO 19107 has a concept of axis permutation). We want to encourage everyone to do the right thing, but at the same time we want to make it work.

**Comment by cportele** [comment]
Addressed by part 2 and can be closed.
