### ISSUE TITLE
CQL2 Case-insensitive Comparison upper/lower

### ISSUE THREAD

**Issue by philvarner** [opengeospatial/ogcapi-features#656]
In CQL2 Text, the Case-insensitive Comparison tokens UPPER and LOWER look like they're just user-defined functions. In CQL2 JSON, they're special objects with the format

```
 { 
   "lower" : { "property": "foo" }
 }
```

or

```
 { 
   "upper" : { "property": "foo" }
 }
```

This requires a special case in the BNF and schema, when they could just be a pre-defined function with specific semantics for taking a string-valued expression and returning a string. I bring this up because I made the mistake of writing up some examples that treated them as functions, and someone challenged me on that thinking they were operators, and I had to go look in the openapi spec to see that they were neither, and instead their own thing.

If they were functions, they'd be written in JSON as: 

```
 { 
        "function" : "lower",
        "args": [ { "property": "foo" } ]
 }
```

```
{ 
        "function": "upper", 
        "args": [ { "property": "foo" } ]
 }
```

Which seems easier to me than having a separate special format for them.

**Comment by pvretano** [comment]
@philvarner already aware of the incongruity.  Will be handled as part of pr #641.

**Comment by philvarner** [comment]
Great, closing.
