### ISSUE TITLE
CQL2: quote in string literals

### ISSUE THREAD

**Issue by aaime** [opengeospatial/ogcapi-features#671]
I've been looking for ways to handle single quotes character literals, checked spec and BNF coming out empty.

In GeoServer CQL and ECQL implementation, we follow the same approach as SQL, that is, doubling up the quote, e.g.:

``roadName = 'Via dell''Avvento'``

In the case above, the quote is the Italian apostrophe (it does not have a special char for it, it's the same as quote, the practice in Italian is to use double quotes when citing somebody else).

**Comment by pvretano** [comment]
@aaime oops ... I'll fix that in a PR now ...

**Comment by cportele** [comment]
Addressed by #673
