### ISSUE TITLE
CQL: give CASEI and ACCENTI distinct conformance classes

### ISSUE THREAD

**Issue by aaime** [opengeospatial/ogcapi-features#672]
In the current standard, it seems one cannot implement only CASEI and advertise the "http://www.opengis.net/spec/cql2/1.0/req/case-insensitive-comparison", as that seems to include also the ACCENTI function.

I find this setup onerous from the implementation point of view, while case insensitive comparisons are easily implemented in most data sources, and are already implemented by anyone that dealt with Filter Encoding, accent insensitive requires an ad-hoc setup in the data source, and sometimes even language-specific, e.g., see:
https://www.postgresql.org/docs/12/collation.html

May I suggest giving the two functions separate conformance classes?

**Comment by pvretano** [comment]
@aaime we already considered that and decided to put them in one conformance class (see https://github.com/opengeospatial/ogcapi-features/pull/641#issuecomment-1014666589).  However, I can see your point too so I guess we will revisit the issue at the next SWG meeting.  Personally I'm agnostic about the issue ... either was works for me.

**Comment by aaime** [comment]
@pvretano say one is trying to do a OGC API Features that proxies a WFS 2.0. I believe case insensitive could be cascaded, but one cannot cascade accent insensitive filters. So either one declare it can do neither, or will do both, but the accent insensitive filters will have to be processed locally, after fetching data, rather than cascading it.

Does not seem ideal to me :-)
