### ISSUE TITLE
CQL2: interval() as temporal literal

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-features#674]
I am updating our implementation to CQL2 and I have run into the following problem:

All temporal intervals are defined as "temporal literals", however, this is incorrect as the rule is not restricted to literals:

```text
temporalLiteral = instantLiteral | intervalLiteral;

intervalLiteral = "INTERVAL" 
                  leftParen instantParameter comma instantParameter rightParen;

instantParameter = dateInstantString
                 | timestampInstantString
                 | quote dotdot quote
                 | propertyName
                 | function;
```

For example, I can define a temporal "literal" value as `INTERVAL(start, end)`, referencing two properties.  This does not look like a literal to me. It is more a regular function that can take a literal or a property reference (or another function) - similar to the pre-defined functions CASEI or ACCENTI.

One option to address this could be to define INTERVAL as a proper function, like CASEI and ACCENTI. DATE and TIMESTAMP could stay as qualifiers for strings that represent instants. This would update the `function` and `temporalLiteral` rules as follows:

```text
function = identifier leftParen {argumentList} rightParen
         | "CASEI" leftParen characterExpression rightParen
         | "ACCENTI" leftParen characterExpression rightParen
         | "INTERVAL" leftParen instantParameter comma instantParameter rightParen;

temporalLiteral = dateInstant | timestampInstant;
```

However, this would have an impact on the JSON encoding where we would get

```json
{ "name": "interval", "args": [ "2019-09-09", ".." ] }
```

instead of

```json
{ "interval": [ "2019-09-09", ".." ] }
```

In case of property references we would get:

```json
{ "name": "interval", "args": [ { "property": "start" }, { "property": "end" } ] }
```

Thoughts?

**Comment by aaime** [comment]
I'm building a CQL parser and stumbled on the same issue, in order to represent INTERVAL in memory I pretty much have to build a function taking two expressions, as the inputs are more variable than DATE/TIMESTAMP (where a Literal suffices).

The difference is really there, interval is dynamic while date/timestamp are not. There would be no issue if INTERVAL were to accept only literals as arguments. 

I guess having attribute reference support is desirable because an INTERVAL data type is commonly lacking in data sources, and ends up being represented by two separate fields, while date/timestamp fields are pretty much everywhere, so there is no strict need for dynamic behavior there. But just to draw a parallel, think of having a database that only supports date and time columns, then a ``TIMESTAMP(date, time)`` function would be equally interesting (or one that takes a function as input, e.g., concatenating the two columns as strings).

I may be unpopular with this proposal, but I'd restrict INTERVAL to take only literals as well, I recognize it removes some dynamic filtering possibility, but at the same time, makes implementation easier and the grammar consistent.

**Comment by cportele** [comment]
@aaime - The problem with this approach is that this would make most temporal operators (everything beside intersects/disjoint/equals/after/before) useless with most backends, since the temporal operators require intervals and if intervals can only be literals, they are effectively constants.

**Comment by aaime** [comment]
You are right, it would allow comparisons between instant and interval, but not between two intervals. Same limitation as the original CQL.
Indeed, I don't remember having used interval-based filters in CQL (like... ever) because we already supported simple comparisons with temporal data types as well.

**Comment by pvretano** [comment]
@cportele don't call it an `intervalLiteral`.  Call it an `intervalExpression` and renamed `temporalLiteral` to `temporalClause`.
````
temporalClause = instantLiteral | intervalExpression;

instantLiteral = dateInstant | timestampInstant;

dateInstant = "DATE" leftParen dateInstantString rightParen;

dateInstantString = quote fullDate quote;

timestampInstant = "TIMESTAMP" leftParen timestampInstantString rightParen;

timestampInstantString = quote fullDate "T" utcTime quote;

intervalExpression = "INTERVAL" leftParen instantParameter comma instantParameter rightParen;

instantParameter = dateInstantString
                             | timestampInstantString
                             | quote dotdot quote
                             | propertyName
                             | function;
````
Then rename all instances of `temporalLiteral` to `temporalClause`.

If you thinks this is OK, I can make the changes ...

**Comment by pvretano** [comment]
@cportele all the temporal and spatial operators are function too but for historical reasons we don't call those functions either.  This is just another case of that ... no?

**Comment by cportele** [comment]
@pvretano - The way I see it there are two topics:

1. We need to be clearer how we use the term "function". In the text we also use "function" to specify DATE, TIMESTAMP, INTERVAL, but these are not functions in the CQL2 grammar. We do not use the term function in the context of the spatial/temporal/array operators (neither in the text nor in the grammar). The simplest approach would be to update the grammar as you have proposed and also to revise the wording to not use "function" to specify DATE, TIMESTAMP, INTERVAL in the text. And we have to remove intervals from the section about literal values and move them somewhere else.

2. CASEI and ACCENTI are defined as functions in both the text and grammar. If we decide to not consider INTERVAL a function, but we decide to specify CASEI and ACCENTI as functions, I find it very hard to find an argument why one is a function and the other not. If we decide to not specify CASEI/ACCENTI as function this could be done as follows:

```
scalarExpression = characterClause
                 | numericLiteral
                 | ...;

characterClause = characterLiteral
         | "CASEI" leftParen characterExpression rightParen
         | "ACCENTI" leftParen characterExpression rightParen;

characterExpression = characterClause
                    | propertyName
                    | function;
```

**Comment by pvretano** [comment]
@cportele I think we should reserve the term "function" to mean user defined function or extensions function or whatever term we want to use to indicate a function that is NOT already defined in the grammar.  That would cover all the date functions, the spatial functions, etc.  It would also mean that we will need to move CASEI and ACCENTI as you suggest which I don't mind doing ... and also add some clarifying text to indicate that "function" means "extension function".  If you are OK with this approach, I can create a PR.

**Comment by pvretano** [comment]
@cportele yes, I think so ...

**Comment by cportele** [comment]
Related to this: Currently we have

```
patternExpression = characterLiteral;
```

We also need to support `CASEI` and `ACCENTI` in the pattern expression, so this needs to be changed to 

```
patternExpression = characterClause;
```

**Comment by cportele** [comment]
@pvretano - Are you already working on the PR for this issue? Otherwise I can address it in my current edits for the other issues (which affect the same files)...

**Comment by pvretano** [comment]
@cportele yes, I have an almost-completed PR for this.  The only thing left to do is to update the YAML version of CQL2 to be up to date relative to the JSON version.  I'll do that in the next couple of day and push the PR.
