### ISSUE TITLE
Can I add services without restarting the server?

### ISSUE THREAD

**Issue by codehub-rony** [opengeospatial/ogcapi-features#675]
Hi,

I have a question. Is there a way to setup an API without restarting Idproxy/server?

I want to create an API for a dataset by initializing a new configuration as shown in this [demo](https://github.com/interactive-instruments/ldproxy/blob/master/demo/vineyards/README.md). This works, but it requires a restart of Idproxy. Which basically takes down all services for a few seconds. 

When I add the service through the admin panel, it is added without a restart. Is there a way to use this 'reloading' functionality when working with the config files?

I guess my question is also related to/part of this [admin issue](https://github.com/interactive-instruments/ldproxy/issues/586) 

Kind regards,

Rony

**Comment by cportele** [comment]
This issue is not related to the OGC API Features standard, but to the ldproxy implementation. I am closing this issue and have opened a new issue in the ldproxy repository: https://github.com/interactive-instruments/ldproxy/issues/607
