### ISSUE TITLE
RFC reference URLS are (now) incorrect

### ISSUE THREAD

**Issue by nmtoken** [opengeospatial/ogcapi-features#679]
The RFC URLs in https://github.com/opengeospatial/ogcapi-features/blob/master/core/standard/clause_3_references.adoc are no longer correct.

For example:  

http://tools.ietf.org/rfc/rfc8288.txt now gives HTTP 404.

New link could be https://datatracker.ietf.org/doc/html/rfc2818 or https://www.rfc-editor.org/rfc/rfc2818.txt (plain text) or https://www.rfc-editor.org/rfc/rfc2818.html (html)

etc

**Comment by cportele** [comment]
Note to self: also check the links in the other documents...
