### ISSUE TITLE
unique values

### ISSUE THREAD

**Issue by schmity** [opengeospatial/ogcapi-features#681]
Hi, 
in my organisation there is a need to get unique values for a specific property from an OGC API Features collection. Is this already supported in OGC API Features, part 3 or planned?

E.g. like so:
GET /collections/mycollection/items?property=myproperty&unique=true

Best, 
Sebastian

**Comment by cportele** [comment]
@schmity - There is no concrete plan for such a capability. It would have to be its own resource (e.g. `/collections/mycollection/properties/myproperty`) since the `items` resource returns a FeatureCollection, but this request would return an array of values or some kind of statistics for a property.

**Comment by schmity** [comment]
Thanks for the insight. Unique values for properties might also fit in the collection resource, /collections/mycollection/, being similar to spatial and temporal extent in a way. 
The simple use case of our web developers (Masterportal) is to create a drop-down for filtering without having to parse the entire dataset. How would one adress that in a standardized way, if the dataset comes without code lists?

**Comment by schmity** [comment]
I came across a similar discussion in the OGC API - Features Repo, https://github.com/opengeospatial/ogcapi-features/issues/799#issuecomment-1458367695: "Just list the values as enum in the queryables schema."

Is there an option in ldproxy to retrieve the domain/unique values from the database dynamically?

**Comment by schmity** [comment]
https://github.com/opengeospatial/ogcapi-features/issues/799#issuecomment-1458367695 provides an answer to my question.

**Comment by schmity** [comment]
https://github.com/opengeospatial/ogcapi-features/issues/799#issuecomment-1458367695 provides a feasible approach for our use case.
