### ISSUE TITLE
Login to Idproxy

### ISSUE THREAD

**Issue by ahmadharis14** [opengeospatial/ogcapi-features#706]
While deploying the Idproxy, the default webpage of "http://localhost:7080/manager/" to first default log in with userid: admin and password: admin, when I change the password - it doesn't accept it. Only one time after hours of struggle - a new interface of log in came but it would not accept the log in. I am stuck here for days, any help would be very appreciated.

**Comment by cportele** [comment]
@ahmadharis14 - This is related to an implementation, not the specification, so I am closing this issue here. 

Please open an issue at https://github.com/interactive-instruments/ldproxy/issues instead.

**Comment by ahmadharis14** [comment]
Yeah sure
Thanks
