### ISSUE TITLE
Unary minus operator missing ...

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-features#709]
I may be missing something but I don't see the unary minus operator in the BNF.  For example, how would I say -a+10?  I think that the `numericExpression` production should be:

```` 
numericExpression = minus numericExpression 
                  | arithmeticExpression
                  | numericLiteral
                  | propertyName
                  | function;
````
Have not checked the JSON encoding yet but changes may be required there too.

**Comment by cportele** [comment]
Meeting 2022-06-20: We will make the change in the `arithmeticExpression` rule.
