### ISSUE TITLE
CQL2 division real or integer? data type dependent?

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-features#711]
Is the division operator (`/`) in CQL2 expected to perform integral or real division, and does it depend on the data types of its operands?
I think the specification needs to be clear about this.

In ECCSS / CMSS we have two separate operators, with `div` always performing integral division whereas `/` always preserves any fractional part, even when dividing integer values.

It might be worthwhile to consider whether separate operators are needed, especially considering that no remainder / modulo operators is defined separately -- if `/` is always fractional division, one cannot even use `a - (a/b)*b` to compute the remainder.

**Comment by pvretano** [comment]
The intent was that it be fractional division (i.e. 10/3=3.333) but I suppose this is something that will need to be disucssed in the SWG.  With regard to a modulo function I would say that is what the function conformance class is for.  However, another thing to discuss in the SWG ... that is how many functions/operators we define in the language and which ones we leave up to profiles or implementations to add.

**Comment by jerstlouis** [comment]
> how many functions/operators we define in the language and which ones we leave up to profiles or implementations to add

Considering that we have conformance classes, and that _Arithmetic Expressions_ currently only defines 5 of them (is `^` for exponents intended to be supported or not? See [comments in PR 710](https://github.com/opengeospatial/ogcapi-features/pull/710) about things missing for it), I think it should not be a stretch to require support for all 5.

I would even suggest throwing in integer division (`div`?) and modulo/remainder (`%`) for a total of 7. Or 6 if we exclude exponents, which to me seems like they could be left to profiled function calls and are less important than integer division and remainders, but I am a biased C-ish developer where we need to use `pow()` or `x*x*x`.

That being said, it might also be useful to later define profiled set of functions to standardize additional functionality, especially in the context where we will want to use CQL2 expressions not only for filtering predicates, but also for parameter values in symbolizers.
