### ISSUE TITLE
`/functions` -- out of scope for CQL2? (in Part 3: Filtering)

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-features#715]
Section 2 - Conformance and the BNF mention the path `/functions`, but no requirement specifies this in the CQL2 specification.
Perhaps this is a left over that should be removed from CQL2, since the implementation cannot be assumed to be a web server?

`/functions` is already mentioned in Part 3 where this belongs.

**Comment by pvretano** [comment]
Yup, should be removed from CQL2.  This path is part of Part 3.
