### ISSUE TITLE
`POLYGON\(`... in CQL2 examples

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-features#716]
Several examples (e.g., _Example 10_ in [Section 7.5.1](https://docs.ogc.org/DRAFTS/21-065.html#_spatial_data_types_and_literal_values)) have a `\` following `POLYGON` before the parentheses.

Is that intended / allowed?

**Comment by pvretano** [comment]
Typo.

**Comment by jerstlouis** [comment]
@pvretano Thanks, there are 5 occurrences of it. I can do a PR if you prefer.

**Comment by pvretano** [comment]
@cportele yes, I think you are correct about that.
