### ISSUE TITLE
CQL2: Permission 3 (binary comparison operators for time instants) targeting clients?

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-features#719]
If permission 3 `/per/basic-cql2/time-instant-comparison` is intended to be a permission for the clients, then this should really be a **requirement** for the server.

> In lieu of using the formal [temporal operators](https://docs.ogc.org/DRAFTS/21-065.html#temporal-operators), binary comparison operators may be used to evaluate simple temporal predicates (rule: binaryComparisonPredicate) involving time instants (rule: instantLiteral).

**Comment by cportele** [comment]
Meeting 2022-07-04: The permission is not a permission for the server and will be converted to informative text that clarifies that all implementations have to support comparisons of instants (and clients make use of that capability).
