### ISSUE TITLE
CQL2: Requirement 2C is a requirement on the client; 2B "literal value"

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-features#721]
[Req 2C](http://docs.ogc.org/DRAFTS/21-065.html#basic-cql2_property):
> The data type of the literal value SHALL match the expected data type for the expression within which the property name reference appears.

This requirement is not expressed in function of the target of the standard (the server).
To some extent, _Permission 2_  already lets the server decide how to handle mismatched data types:

> If a predicate or operator has operands that have incompatible data types, the server MAY either return an error or it MAY cast the operands to compatible data types.

Related to point 2 of #705 as well.

Also [Req 2B](http://docs.ogc.org/DRAFTS/21-065.html#basic-cql2_property):

> The property name reference SHALL evaluate to a **literal** value or NULL.

I believe _literal value_ here is not used with the [usual meaning](https://stackoverflow.com/questions/485119/what-does-the-word-literal-mean):

> A literal is "any notation for representing a value **within source code**"

Perhaps this could be something like:

> The property name reference SHALL evaluate to its corresponding value, or NULL if unset or invalid.

Also an issue in [Req 17](http://docs.ogc.org/DRAFTS/21-065.html#functions).

**Comment by cportele** [comment]
Meeting 2022-07-04:

* Change 2B to "The property name reference SHALL evaluate to its corresponding value, or NULL if unset". 
* Remove 2C since this is covered by Permission 2.
* Change 17 to "The function SHALL evaluate to its return value ..."
