### ISSUE TITLE
Part 4: PATCH with new property

### ISSUE THREAD

**Issue by benoitdm-oslandia** [opengeospatial/ogcapi-features#737]
From the spec, in the UPDATE section, the example http://docs.ogc.org/DRAFTS/20-002.html#_example_4 add a new property `primary_material` which does not seem to be in the original schema. 

IMHO, I think could be tricky to handle this case where we accept to add new properties to existing feature. 

By the way, does it mean all the feature of this collection will have this new property? And, in this case, what should be the default value?

**Comment by cportele** [comment]
Meeting 2022-09-12: See #736 for an answer (no, the server does not have to accept a property that it does not support and that violates the schema constraints).
