### ISSUE TITLE
Etags and optimistic locking

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-features#744]
After implementing support for 'Optimistic Locking' we see the need for more guidance or additional requirements regarding ETags for feature resources.

In general, a weak ETag seems to be more appropriate for a feature resource to support the 'optimistic locking' use case, because the same weak ETag can be used for two different representations of the same resource; that is, they are semantically equivalent, but not byte-for-byte identical. Semantically equivalent is the pre-condition to avoid 'lost updates' in our use case. Byte-for-byte identical is not required for this and hard to achieve, because our representations include various parts that can change without any semantic change to the feature. One example are the `self` and `alternate` links, which can change without any change to the feature in the backend datastore (title properties will change depending on the language, an alternate link will be added, if a new encoding is supported by the API, etc.). Other changes could be differences in whitespace or differences in the sequence of members in the JSON objects. So, byte-for-byte identical is essential for caching and supporting range requests, but not for the PUT/PATCH validation in our case.

However, the ETag of a feature in the GeoJSON representation must be a strong ETag since conditional request with `If-Match` will ignore weak ETags.

As an aside: For `If-None-Match` headers weak validation is used; i.e., the use of weak ETags is sufficient to support 304 Not Modified responses on GET requests to features.

Here are some options that I see:

* Deviate from HTTP and allow weak validation for `If-Match`. Bad idea, because this is not what client and server libraries for HTTP will support.
* Support an option to retrieve a "normalized" GeoJSON representation of a feature, so that a strong ETag can be used; i.e., no API links like `alternate` (which are not relevant for a replace/update/delete operation anyhow), no whitespace, consistent ordering of members (which may be difficult to guarantee depending on how the JSON is serialized), fixed CRS, fixed Encoding, etc. Then clients will have to fetch the feature before editing a feature for a PUT/PATCH/DELETE request. Fetching the latest version before editing a feature is probably not a bad idea in general, but this approach still seems to be quite and probably too complex.
* Use `Last-Modified` instead of `ETag` as the validator. The client just needs to remember when the feature was retrieved. But it requires that the API knows about the last modification timestamp of every single feature. But maybe that is ok for APIs that need optimistic locking?

**Comment by benoitdm-oslandia** [comment]
Hi @cportele,

I believed from the OGC draft, the string eTag is (only) computed according to the data in the database (or the storage) but you are suggesting it should be computed according to the geojson data (which can change from an call to another as you mentioned)?

**Comment by cportele** [comment]
Meeting 2022-08-15: We will keep this open, but in general `Last-Modified` seems more appropriate than strong `ETag`s for features. Still `ETag` may be more appropriate for other resource types where byte-by-byte identify is applicable. @pvretano will work on a PR.

@benoitdm-oslandia - A strong ETag must be computed from the bytes that are returned via the API. A weak ETag is what would make sense for features, but `If-None-Match` requires strong ETags.
