### ISSUE TITLE
CQL2 (AT): A.12 CQL2 Text A.13 CQL2 JSON

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-features#750]
- [A.12.1 Conformance Test 49](http://docs.ogc.org/DRAFTS/21-065.html#_conformance_test_49) cql2-text/validate currently says _Validate the filter expression in CQL2 JSON_ but should be saying **_CQL2 Text_**.
- The current wording of[ A.12](http://docs.ogc.org/DRAFTS/21-065.html#_conformance_test_49) and [A.13](http://docs.ogc.org/DRAFTS/21-065.html#_conformance_test_50) (_Validate the filter expression against BNF / JSON Schema_) seems incorrect / not testable. What filter expressions? The Filter expressions are provided by the test. I think these abstract tests should instead say something like:
   - Execute conformance tests for all supported conformance classes by selecting cql2-text / cql2-json (e.g., `filter-lang=` and specifying the filter (e.g., `filter=`) for these tests encoded as cql2-text / cql2-json and assert that they are all successful.

Perhaps it should also include a prelude to this at the beginning of the conformance test series to clarify that a test suite should re-encode the filters for Conformance tests 1-48 in the appropriate encoding as defined in 49 and 50 (or maybe 49 and 50 should be first?), to allow for servers that only support cql2-json, but not cql2-text. Maybe this is a small tweak to the current prelude to the tests:

> All eleven conformance classes for the standardization target type "servers that evaluate filter expressions" have the following parameter:
Filter Language: The CQL2 encoding to be used in the test, either "CQL2 Text" or "CQL2 JSON";

EDIT: I just noticed that the target type is different and says _Representations of a filter expression_ (did not expect this).

However, I think the target should still be _Servers that evaluate filter expressions_ and this re-wording would allow this, and would allow test suites to test compliance with them.
e.g., I still expect _OGC API - Features_ services implementing Part 3 to declare conformance to _cql2-text_ and _cql2-json_, and implementations for Symbology Encodings that use CQL2 filters as selectors / parameter values would also be "servers" conforming to either.

[Section 2](http://docs.ogc.org/DRAFTS/21-065.html#_conformance) would also need to be updated to reflect the change, if applied.

**Comment by cportele** [comment]
Meeting 2022-08-01: @cportele thinks the current approach is correct and consistent with the Mod Spec. He will check this more closely and document his findings. We can continue the discussion afterwards.

**Comment by cportele** [comment]
Meeting 2022-08-15:

* On the requirements classes and standardization targets, this should be consistent with Part 1 and how we handle GeoJSON, HTML, GML as well as the parameterized conformance classes in the ModSpec.
  * Proposal from Jerome: "Execute conformance tests for all supported conformance classes by selecting cql2-text / cql2-json (e.g., filter-lang= and specifying the filter (e.g., filter=) for these tests encoded as cql2-text / cql2-json and assert that they are all successful". And to change the target of the requirements class to "Servers that evaluate filter expressions".  
* In Conformance Test 49, CQL2 JSON needs to be changed to CQL2 Text.

**Comment by cportele** [comment]
I have created a PR, see #761.

This implements the proposal. The Mod Spec suggests a different approach, but the difference is that parameters of conformance classes in the Mod Spec are only discussed to parameterize the output that a server creates (e.g. GML, KML, etc.). In the CQL2 case this is different and we parameterize the input. Since we want to be able to declare conformance with CQQL2 Text/JSON orthogonal to the filter capability conformance classes the proposed approach seems to be the natural approach.

If the Mod Spec is revised at some point in the future, these aspects should be considered in the revision.

**Comment by cportele** [comment]
Meeting 2022-09-12: This change looks like a good approach. We will keep this open until the next meeting for review.
