### ISSUE TITLE
Advertising CQL2 support in the Conformance Declaration

### ISSUE THREAD

**Issue by ghobona** [opengeospatial/ogcapi-features#752]
State clearly in Clause 2 (Conformance) and Annex A.1.1 (Conformance Test 1) of Part 3 that "If the server supports CQL2, it shall advertise the URI `http://www.opengis.net/spec/cql2/1.0/conf/basic-cql2` in its Conformance Declaration".

The need to improve the conformance declaration in relation to CQL2 was identified in Section 13.3.3 of the draft FMSDI ER (22-013r1) which is on the Pending Documents register.

**Comment by cportele** [comment]
@ghobona - CQL2 is not limited to the use in OGC Web APIs and is a separate standard, so this would be an inappropriate statement in the CQL2 standard.

In addition, it is not the responsibility of Clause 2 to say that. Clause 2 introduces the requirements/conformance classes. For convenience we also provide the list of the URIs in Clause 2. But it is the responsibility of the specification of the Conformance Declaration resource to provide normative statements for the resource, not Clause 2. 

Maybe we could add an informative note in all clauses 2 of the OGC API standards to point that out, but I also doubt, if that would address the feedback from ER. I read the statement that the client did not inspect the Conformance Declaration or the OpenAPI definition (where that information could be found), it looked at the Collection resource. To address this, the information about the supported `filter-lang` values would need to be added to the Collection resource.

**Comment by ghobona** [comment]
@cportele I agree that CQL2 is not the place to add it. I was referring to Clause 2 in Part 3 of OGC API Features. 

An informative note would also be fine.

**Comment by cportele** [comment]
Meeting 2022-08-15: @cportele to add a sentence in Clause 2 to point out that any supported CQL2 conformance classes should be advertized in the Conformance Declaration, too. 

We cannot include it in the conformance test, because Part 3 can also be implemented without support for CQL2 (although most implementations of Part 3 will support CQL2 just like most implementations of OGC API Features support GeoJSON as a feature encoding).
