### ISSUE TITLE
CQL2 : Move subExpression to a separate conformance class 

### ISSUE THREAD

**Issue by jjrom** [opengeospatial/ogcapi-features#769]
I have been implementing Basic CQL2 support within [resto](https://github.com/jjrom/resto). With the existing implementation of resto, the support of Basic CQL2 logical and comparison operators is feasible without too much effort.
However, the support of sub expression (i.e. sub query within parenthesis) is much more difficult to achieve and requires a major refactoring of underlying querying class which is an issue for the project.

I don't know if other implementors faced this issue but I think that moving subExpression outside of Basic CQL2 to a separate conformance class would ease the support of Basic CQL2.

**Comment by jerstlouis** [comment]
Because currently the logical operators (`AND`, `NOT`, `OR`) are part of Basic CQL2, I would argue that sub-expresssions should remain there together with the logical operators as well so as to be able to unambiguously prioritize logic combinations.

**Comment by cportele** [comment]
Meeting 2022-11-21: We think that the ability to group logical expressions is as important as support for the AND/OR/NOT operators. Most/many expressions involving AND/OR/NOT will make use of parentheses. We are therefore leaning towards keeping the subExpression rule in the Basic requirements class. We plan to make a decision in the next meeting.

**Comment by cportele** [comment]
Meeting 2023-02-15: There were no further comments or concerns. We have therefore decided to leave it unchanged.
