### ISSUE TITLE
Does a bbox have to be 2d or 3d?

### ISSUE THREAD

**Issue by philvarner** [opengeospatial/ogcapi-features#786]
This issue was prompted by the stac-api-spec issue:

- https://github.com/radiantearth/stac-api-spec/issues/375

A STAC API user prompted up a good question -- is bbox that represents a single point (identical coordinates) or a line (either lat or lon are the same) valid? I wasn't able to find any restriction that the bbox must be 2 or 3 dimensional in either the GeoJSON spec or the OGC spec that clarifies some of the semantics on the use of GeoJSON (I can't remember which spec it was). Informally, something that is a "box" would need to be 2d or 3d.

**Comment by cportele** [comment]
@philvarner - we discussed this topic in #288. 

As a result, the following text was added after [/req/core/fc-bbox-response](https://docs.opengeospatial.org/is/17-069r4/17-069r4.html#req_core_fc-bbox-response):

> In case of a degenerated bounding box, the resulting geometry is used. For example, if the lower left corner is the same as the upper right corner, all features match where the geometry intersects with this point.

**Comment by philvarner** [comment]
Great, thanks!
