### ISSUE TITLE
Missing geometry column name in /collection/{collectionID} 

### ISSUE THREAD

**Issue by ufolr** [opengeospatial/ogcapi-features#795]
Im trying to work with the OGC API Features and CQL to query data.

I notice that I can't get the geometry column name in /collection/{collectionID}, but CQL need it, such as WITHIN( `geometry` , POLYGON(xxx)), the geometry column name need.

I understand geometry column name is not a property of properties, but it's a useful metadata info of collection. So, prove geometry column name explicitly as a filed in  /collection/{collectionID} is necessary, because CQL need it.
Just like this:
GET /collections/{collectionID}?/f=json
```json
"id": "myID",
"crs":xxx
"extent": "xxx"
"geo_col": "xxx"
```

I'm new to the OGC API Features Standard, maybe I missing some point?  please correct.

**Comment by cportele** [comment]
Hi @ufolr 

The properties that can be used in CQL2 filter expressions are published via the Queryables sub-resource of the Collection. See https://docs.ogc.org/DRAFTS/19-079r1.html#queryables.

**Comment by ufolr** [comment]
@cportele THX for your answer, it's very close to my usage scenario.
I read [this part](https://docs.ogc.org/DRAFTS/19-079r1.html#queryables) several times, but I didn't find a direct way to get the geometry property.
The `type`:`object` for spatial property is a SHOULD option, and also the `$ref` member is a SHOULD option.  I can't find out whether the property is a spatial property by whether there is a fixed tag。
I‘m thinking about is it a better way to make `type` as a MUST member for Queryables property? I'd like to discuss about it.

**Comment by cportele** [comment]
Meeting 2023-04-10:

* Change the `geojson-xxx` format tags to generic tags (e.g., `geometry-linestring`).
* There should be no `type` in the geometry property, since it may be a GeoJSON geometry or a WKT string or ....
* Make it a requirement to provide the format for geometry properties and for all others require that the `type` member is specified. Keep the rest in the recommendation.
* @cportele will create a PR.
