### ISSUE TITLE
Functions as a boolean expression

### ISSUE THREAD

**Issue by tschaub** [opengeospatial/ogcapi-features#796]
It looks like CQL2 allows functions to be used in place of numeric, string, geometry, temporal, and array expressions.  I'm curious if it is intentional that booleans are excluded from this list.

I'm looking to support a number of custom filter functions that express things like "user has X permission."  This could be expressed as a CQL2 function like this:

```json
{
  "function": {
    "name": "permission",
    "args": ["download"]
  }
}
```

The current spec/schema doesn't consider a function a boolean expression, so one option is to include the function in a binary comparison expression:
```json
{
  "op": "=",
  "args": [
    {
      "function": {
        "name": "permission",
        "args": ["download"]
      }
    },
    true
  ]
}
```

We have a number of similar boolean function type filters that I'd like to be able to support in CQL2, and I would like to avoid having to evaluate this extra comparison expression (or to get rid of it in the parser).

**Comment by pvretano** [comment]
Doh!  Not intentional ... I'll take a look.

**Comment by cportele** [comment]
Meeting 2023-03-13: The analysis is correct, this needs to be fixed. Thank you for alerting us.
