### ISSUE TITLE
domain values for queryable

### ISSUE THREAD

**Issue by pvgenuchten** [opengeospatial/ogcapi-features#799]
I have a use case to return a list of (unique) domain values for a queryable. The domain values could be defined on the data model (OASpecification) or extracted from the database using a group-by query. I haven't located any previous discussion on this topic, but maybe i overlooked a part of the issues.

I wonder if it would be of interest to set up the following pattern (either as a plugin or as a generic functionality)

| url | desc |
| --- | --- |
| /collections/main/queryables | List the available queryables |
| /collections/main/queryables/keywords | Paginated list of keywords used in features |
| /collections/main/queryables/keywords/forest | Alternative representation of (or forward to)  /collections/main/items?keywords=forest |

This is for example relevant if you want to populate a filter box with allowed values (or autocomplete)

**Comment by cportele** [comment]
@pvgenuchten

Providing the domain of values of a property is already possible today. Just list the values as `enum` in the queryables schema. See for example, https://demo.ldproxy.net/daraa/collections/TransportationGroundCrv/queryables?f=json. If the enum values are retrieved dynamically from the data (with or without caching) or a schema, explicitly configured, etc. should be an implementation decision.

Regarding `/collections/main/queryables/keywords/forest`: Personally I do not really see a value to standardize resources that are basically just an URI alias for the same resource. What would be the benefit for the user and why would it make sense to standardize such resources?

**Comment by pvgenuchten** [comment]
Thanx @cportele, provide the enum in the json response is an interesting option. The filter on features was just an idea, I agree not optimal from redundancy
