### ISSUE TITLE
Add explict comment about POST for query at items endpoint.

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-features#805]
I was in a discussion with some Records folks about the "overloading of POST at the `/items` endpoint".  

I had no idea what they were taking about and they explained that in some implementations of Features/Records POST is overloaded at the `/items` endpoint for use with CQL2-json for querying.

As far as I know, there is nothing in Part 3 or CQL2 that says or implies this. 
 Using POST for query is part of the [Search](https://htmlpreview.github.io/?https://github.com/opengeospatial/ogcapi-features/blob/master/proposals/search/standard/20-096.html) proposal and was also discussed in [TB18](https://gitlab.ogc.org/ogc/T18-Advanced_Filtering_of_SWIM_Feature_Data/-/issues/11).
We should probably include some text in Part 3 and/or CQL2 and/or Part 4 that makes it clear that POST at the `/items` endpoint is not for query and that, that capability (i.e. using POST for advanced queries) will be described in another part based on the [Search](https://htmlpreview.github.io/?https://github.com/opengeospatial/ogcapi-features/blob/master/proposals/search/standard/20-096.html) proposal and the work done is [TB18](https://gitlab.ogc.org/ogc/T18-Advanced_Filtering_of_SWIM_Feature_Data/-/issues/11).

**Comment by cportele** [comment]
I am not sure, that we have to prohibit using POST on `/items` for queries. If the content type is a feature encoding, it is a Create Feature operation. 

We have also implemented POST on `/items` as an option that can be activated, but only for media type `application/x-www-form-urlencoded` to support large filters. But as far as I can tell this is more an edge case that we do not need to standardize.

In any case, in general this strictly does not conflict with POSTing a new feature with content type `application/geo+json` or even with a CQL2 JSON query.

**Comment by cportele** [comment]
Meeting 2023-04-10: 

* There is nothing in OGC API Features that suggests to use POST with a filter on `/items`.
* Even if POST with a query payload (and a proper media type) and POST with a feature payload would work, it would still be confusing to POST on `/items` and one operation creates a feature and another one executes a query. Advanced queries should be executed using the Search extension.
* IETF is discussing a new HTTP method for idempotent requests with payload (QUERY is one of the method names under discussion), which could remove the ambiguity.
* Maybe the impression comes from STAC, but there POST also goes to `/stac/search` as far as we know.
* We can close this issue.
