### ISSUE TITLE
Required fields for links

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/ogcapi-features#818]
I'm currently comparing STAC, STAC API, OGC API Features and OGC API Records link objects.
STAC API made the `type` recently a required field due to [req 13B](https://github.com/opengeospatial/ogcapi-features/blob/master/core/standard/requirements/core/REQ_fc-md-links.adoc) in OAFeat, but the schema doesn't list type as being required:
http://schemas.opengis.net/ogcapi/features/part1/1.0/openapi/schemas/link.yaml
Or does 13B only apply to self and alternate links as mentioned in req. 13A?

@pvretano In Records the schema only requires href, I think: https://github.com/opengeospatial/ogcapi-records/blob/master/core/openapi/schemas/common/link.yaml 

In Commons the schema requires href and rel: https://github.com/opengeospatial/ogcapi-common/blob/master/19-072/openapi/schemas/link.yaml

I feel like there's a bit of alignment or clarification needed, not only in Features...?

**Comment by m-mohr** [comment]
Thanks, this was greatly misunderstood by us and even lead to a spec change recently in STAC where we required the type field in STAC API. I think it should be considered to clarify the wording... something like: "All links with relation type `self` and `alternate` SHALL include the ..."

**Comment by cportele** [comment]
Thanks for raising this. I will create a pull request (and also check, if we should make similar clarifications in other requirements).

**Comment by m-mohr** [comment]
I found at least a similar recommendation: https://github.com/opengeospatial/ogcapi-features/blob/master/core/standard/recomendations/core/REC_sfc-md-links.adoc (which somewhat contradicts with the requirement?)

And also https://github.com/opengeospatial/ogcapi-features/blob/master/core/standard/requirements/core/REQ_fc-md-items-links.adoc, https://github.com/opengeospatial/ogcapi-features/blob/master/core/standard/requirements/core/REQ_f-links.adoc, ... so it seems there are a couple of them. Thanks!

**Comment by cportele** [comment]
@m-mohr - Please have a look at https://github.com/opengeospatial/ogcapi-features/pull/819. Thanks!
