### ISSUE TITLE
Question: Conformance Links 404

### ISSUE THREAD

**Issue by ranchodeluxe** [opengeospatial/ogcapi-features#821]
There are conformance links for `/filter` and `/features-filter` that don't exist anymore but are still in the docs.

https://github.com/opengeospatial/ogcapi-features/blame/master/extensions/filtering/standard/clause_2_conformance.adoc#L40-L41

What's the plan with these? Can they be removed or are there updated conformance docs that we should be pointing to?

**Comment by cportele** [comment]
The conformance classes exist, but the links were broken. And two conformance classes were not listed. I have created a pull request in #822.
