### ISSUE TITLE
Finalizing Part 3 (Filtering) and CQL2

### ISSUE THREAD

**Issue by cportele** [opengeospatial/ogcapi-features#824]
Known tasks before a SWG motion to start the approval process:

* [x] Update document history with changes since the last tag.
* [x] Check consistency and testability of the Part 3 ATS with the requirements.
* [x] Final checks by the editors.

**Comment by cportele** [comment]
Meeting 2023-05-08: The plan is to finalize editing Part 3 and CQL2 before May 18 and upload both documents to pending. In parallel to the three week rule for the member meeting we will have a motion in the SWG.

**Comment by m-mohr** [comment]
What's the status on this @cportele? We are wondering when we can release the STAC API extension that is based on CQL2.

cc @philvarner

**Comment by pvretano** [comment]
@m-mohr there are still a couple of outstanding issues related to ACCENTI and CASEI that need to be resolved and a few other bits and pieces that need to be cleaned up.  Nothing too difficult but the ACCENTI and CASEI is time consuming and lately neither @cportele or I have had the time to work on this.  @cportele am I being too ambitious if I say that we will be going for an adoption vote late this year or Q1 2024?

**Comment by cportele** [comment]
@m-mohr @pvretano - It would be my goal that we try to finalize both Part 3 and CQL2 at the London Code Sprint, so that we can submit it to the approval process in November.

**Comment by m-mohr** [comment]
Thanks, that works for us and we'll wait with a stable release of our extension until this is released.

**Comment by philvarner** [comment]
Hi all, just wondering if there were any updates on the process from the last few months?

**Comment by pvretano** [comment]
@philvarner still dealing with a few final issues but getting there.  Mostly my fault.  Been too busy with other stuff to deal with the last few issues on my plate.  Hope to have them all cleared up by month's end.
