### ISSUE TITLE
CQL/Part 3: Default values in queryables?

### ISSUE THREAD

**Issue by m-mohr** [opengeospatial/ogcapi-features#835]
If I specify a `default` in the JSON Schema of a queryable, what does this mean?
Does this mean the default value is applied by default to the search unless the user specifies something else explicitly?

**Background:**
We have an API where we have data that is "offline" and "online", i.e. for the offline data we only have the metadata readily available and for the online data the data can be accessed directly. We have a boolean field `online: true/false` for this in the metadata. By default we only want the user to search for the online data, i.e. by default we want to exlude all items from the search results where `online` is set to `false`. We were thinking about indicating this via an `online` queryable which has the `default` set to `true`. This means if the queryable `online` is not explicitly set to `false`, the true filter applies and offline items are excluded.

Is this something that should be defined in the spec? Or should we just clarify what a default value in the queryable means? Thoughts?

**Comment by m-mohr** [comment]
Thanks. The intention from #215 seems clear, I think I'd clarify the wording. It's also what seems more flexible and would allow the mentioned use-case above. I could see similar use cases for hiding e.g. deprecated or expired resources by default (which we can have in STAC for example).

**Comment by cportele** [comment]
Meeting 2023-06-19: @cportele will write a pull request for Part 1 and Part 3.
