### ISSUE TITLE
Invalid or unintuitive `t_contains` example?

### ISSUE THREAD

**Issue by fmigneault** [opengeospatial/ogcapi-features#836]
According to the following definition: https://www.w3.org/TR/owl-time/#time:intervalContains
The second argument should be a proper interval. 
In other words, it should match this case:
```
|---[T1s----------T1e]---|
|-------[T2s--T2e]-------|
```

The following example uses `updated_at` as if it was a single `date-time` or `timestamp` property:
https://github.com/opengeospatial/ogcapi-features/blob/ed94465c4910a8c650f232dd4719efd40fdacd7e/cql2/standard/schema/examples/json/example55.json#L1-L7

Although "theorically", this could be valid if `updated_at` happened to be a `[date-start, date-end]` in the document, this use of `updated_at` is counter-intuitive with respect to all other examples that use the same `updated_at` as a date-time entity.

Using the same definition of [`t_contains`](https://www.w3.org/TR/owl-time/#time:intervalContains), it is possible to argue that it *could* be valid to allow the second argument to be a `date-time` entity, as illustrated below. This feels logical as well, as is probably what the original example was accomplishing. However, this does not seem to respect the time ontology (unless I missed something?).

```
|---[T1s----------T1e]---|
|----------[T2]----------|
```

Therefore, similar to:
- https://www.w3.org/TR/owl-time/#time:before | https://www.w3.org/TR/owl-time/#time:intervalBefore 
- https://www.w3.org/TR/owl-time/#time:after | https://www.w3.org/TR/owl-time/#time:intervalAfter

... there should probably be an explicit class equivalent to `time:contains` for this use case, and a proper example should be added to illustrate the `t_contains` operation using an interval.

**Comment by cportele** [comment]
Yes, thank you. We should update all examples of the temporal functions that expect proper intervals to use properties that are (sound like) proper intervals - or use an interval from begin and end instance properties. 

While there could also be a temporal function to check, if an interval contains an instance, in my view we should stick to the OWL Time definitions that we reference. The five temporal functions that can be used to analyze the relation between an interval and an instance (`t_before`, `t_after`, `t_intersects`, `t_disjoint`, `t_equals`) should be sufficient, I think.

**Comment by cportele** [comment]
Yes, although an interval of `created_at` and `updated_at` also sounds a bit constructed. What I meant are the cases where a resource has a temporal validity and where the interval of validity is represented by two attributes, one for the begin of the validity and another one for the end. 

Here is an example with an API of country boundaries, `gwsdate` and `gwedate` are the two temporal properties. The following request retrieves all country boundaries that did not change between 1950 and 1999: 

```json
{ 
   "op": "t_contains", 
   "args": [ 
     { "interval": [ { "property": "gwsdate" }, { "property": "gwedate" } ] },
     { "interval": [ "1950-01-01", "1999-12-31" ] }
   ] 
 } 
```

[Live query (using CQL2 Text)](https://demo.ldproxy.net/cshapes/collections/boundary/items?filter=t_contains%28interval%28gwsdate%2Cgwedate%29%2Cinterval%28%271950-01-01%27%2C%271999-12-31%27%29%29)

**Comment by cportele** [comment]
Meeting 2023-06-19: @cportele will work on a pull request and update the examples with temporal interval functions, where they are not clear.
