### ISSUE TITLE
CQL2: Logical operations on indeterminate values

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-features#841]
We just managed to verify the new [logic tests](https://docs.ogc.org/DRAFTS/21-065.html#_conformance_test_9) against our implementation (thanks again @cportele for putting these together, I believe they are incredibly useful abstract tests), and there are combinations where I have some doubts about the expected number of items being correct.

Three of these cases relate to performing a NOT logical operation on an indeterminate result due to a comparison with a NULL property (start):

```
p1: pop_other<>1038288
p2: start<=TIMESTAMP('2022-04-16T10:13:19Z')
p3: start IS NOT NULL
p4: start=TIMESTAMP('2022-04-16T10:13:19Z')
```

Logical expression:

`(NOT (start<=TIMESTAMP('2022-04-16T10:13:19Z')) AND pop_other<>1038288) OR (start IS NOT NULL AND start=TIMESTAMP('2022-04-16T10:13:19Z')) or not (pop_other<>1038288 OR start=TIMESTAMP('2022-04-16T10:13:19Z'))`

Expected number of results per table:    243
Number of results we would expect:       3

----

```
p1: pop_other<1038288
p2: start>=TIMESTAMP('2022-04-16T10:13:19Z')
p3: name>'København'
p4: pop_other<=1038288
```

Logical expression:

`(NOT (start>=TIMESTAMP('2022-04-16T10:13:19Z')) AND pop_other<1038288) OR (name>'København' and pop_other<=1038288) or not (pop_other<1038288 or pop_other<=1038288)`

Expected number of results per table:    241
Number of results we would expect:        199

----

```
p1: pop_other<1038288
p2: start<TIMESTAMP('2022-04-16T10:13:19Z')
p3: name IS NULL
p4: pop_other>=1038288
```

Logical expression:

`(NOT (start<TIMESTAMP('2022-04-16T10:13:19Z')) AND pop_other<1038288) OR (name IS NULL and pop_other>=1038288) or not (pop_other<1038288 or pop_other>=1038288)`

Expected number of results per table:    120
Number of results we would expect:        1

I would expect a NOT on an indeterminate value to remain indeterminate, rather than evaluating to TRUE.
Dealing with indeterminate values and logic is a bit tricky, I believe the following would be the correct rules to apply logic on indeterminate values:

```
    false AND [indeterminate] = false
    true AND [indeterminate] = [indeterminate]
    false OR [indeterminate] = [indeterminate]
    true OR [indeterminate] = true
    NOT [indeterminate] = [indeterminate]
```

Following these rules would ensure logic rules such as `NOT (A >= B)` being equivalent to `A < B` regardless of whether A and B can be determined or not.

I believe there are additional cases which would also have a different number of expected results if we follow the above rule for OR evaluation.
Currently there seems to be an assumption that `false OR [indeterminate] = false` making `NOT (false OR [indeterminate])` resolving to true rather than [indeterminate].

Would you agree this makes sense?

The language in clause 6.2 would need some corrections/clarifications:

> For the purpose of evaluating a CQL2 filter expression, a query predicate that evaluates to NULL (i.e. of unknown value) is essentually the same as one that evaluates to FALSE. That is, its effect is that a collection item being evaluated by the CQL2 filter expression would not be passed on for further evaluation.

`NULL` being equivalent to `FALSE` should only apply for the **final** evaluation of the CQL2 query.
For the same reason that a `NULL` property is treated differently than 0 and all comparisons with it evaluate to _indeterminate_ rather than true or false, indeterminate values really need to be treated differently than FALSE throughout the evaluation of an expression.

All different results based on those rules:

121 instead of 242 for:
(NOT (pop_other>1038288) AND pop_other<1038288) OR (pop_other IS NULL and start<TIMESTAMP('2022-04-16T10:13:19Z')) or not (pop_other<1038288 OR start<TIMESTAMP('2022-04-16T10:13:19Z'))

2 instead of 138 for:
(NOT (name<>'København') AND start<=TIMESTAMP('2022-04-16T10:13:19Z')) OR (boolean=true and name<'København') or not (start<=TIMESTAMP('2022-04-16T10:13:19Z') OR name<'København')

2 instead of 123 for:
(NOT (name<>'København') AND pop_other<1038288) OR (name='København' and start<TIMESTAMP('2022-04-16T10:13:19Z')) or not (pop_other<1038288 OR start<TIMESTAMP('2022-04-16T10:13:19Z'))

122 instead of 241 for:
(NOT (name IS NOT NULL) AND start>=TIMESTAMP('2022-04-16T10:13:19Z')) OR (start IS NULL and pop_other>1038288) or not (start>=TIMESTAMP('2022-04-16T10:13:19Z') OR pop_other>1038288)

137 instead of 241 for:
(NOT (start IS NOT NULL) AND name>='København') OR (boolean=true and start>=TIMESTAMP('2022-04-16T10:13:19Z')) or not (name>='København' OR start>=TIMESTAMP('2022-04-16T10:13:19Z'))

3 instead of 139 for:
(NOT (name>'København') AND start>=TIMESTAMP('2022-04-16T10:13:19Z')) OR (pop_other=1038288 and name<'København') or not (start>=TIMESTAMP('2022-04-16T10:13:19Z') OR name<'København')

138 instead of 242 for:
(NOT (name<='København') AND start<TIMESTAMP('2022-04-16T10:13:19Z')) OR (boolean IS NULL and name>'København') or not (start<TIMESTAMP('2022-04-16T10:13:19Z') OR name>'København')

2 instead of 242 for:
(NOT (pop_other<1038288) AND start>TIMESTAMP('2022-04-16T10:13:19Z')) OR (name<='København' and pop_other=1038288) or not (start>TIMESTAMP('2022-04-16T10:13:19Z') OR pop_other=1038288)

3 instead of 243 for:
(NOT (start<=TIMESTAMP('2022-04-16T10:13:19Z')) AND pop_other<>1038288) OR (start IS NOT NULL and start=TIMESTAMP('2022-04-16T10:13:19Z')) or not (pop_other<>1038288 OR start=TIMESTAMP('2022-04-16T10:13:19Z'))

3 instead of 243 for:
(NOT (pop_other<1038288) AND boolean=true) OR (name IS NOT NULL and start<=TIMESTAMP('2022-04-16T10:13:19Z')) or not (boolean=true OR start<=TIMESTAMP('2022-04-16T10:13:19Z'))

2 instead of 242 for:
(NOT (name<='København') AND pop_other IS NULL) OR (name='København' and start>TIMESTAMP('2022-04-16T10:13:19Z')) or not (pop_other IS NULL OR start>TIMESTAMP('2022-04-16T10:13:19Z'))

1 instead of 122 for:
(NOT (start>=TIMESTAMP('2022-04-16T10:13:19Z')) AND start>TIMESTAMP('2022-04-16T10:13:19Z')) OR (pop_other IS NULL and pop_other<=1038288) or not (start>TIMESTAMP('2022-04-16T10:13:19Z') OR pop_other<=1038288)

199 instead of 241 for:
(NOT (start>=TIMESTAMP('2022-04-16T10:13:19Z')) AND pop_other<1038288) OR (name>'København' and pop_other<=1038288) or not (pop_other<1038288 OR pop_other<=1038288)

1 instead of 120 for:
(NOT (start<TIMESTAMP('2022-04-16T10:13:19Z')) AND pop_other<1038288) OR (name IS NULL and pop_other>=1038288) or not (pop_other<1038288 OR pop_other>=1038288)

2 instead of 138 for:
(NOT (boolean IS NULL) AND start<TIMESTAMP('2022-04-16T10:13:19Z')) OR (start>TIMESTAMP('2022-04-16T10:13:19Z') and name<'København') or not (start<TIMESTAMP('2022-04-16T10:13:19Z') OR name<'København')

**Comment by pvretano** [comment]
@jerstlouis ... TLDR ... but the truth table for UNKNOWN values should go something like this:
```
NULL =  NULL -> NULL
NULL IS NULL -> TRUE
```


|Op1     |NOT (Op1)|
|--------|---------|
|TRUE    |FALSE    |
|FALSE   |TRUE     |
|UNKNOWN |UNKNOWN  | 

|Op1     |Op2     |Op1 AND Op2 |Op1 OR Op2|
|--------|--------|------------|----------|
|TRUE    |TRUE    |TRUE        |TRUE      |
|TRUE    |FALSE   |FALSE       |TRUE      |
|FALSE   |TRUE    |FALSE       |TRUE      |
|FALSE   |FALSE   |FALSE       |FALSE     |
|TRUE    |UNKNOWN |UNKNOWN     |TRUE      |
|FALSE   |UNKNOWN |FALSE       |UNKNOWN   |  
|UNKNOWN |TRUE    |UNKNOWN     |TRUE      |
|UNKNOWN |FALSE   |FALSE       |UNKNOWN   |  
|UNKNOWN |UNKNOWN |UNKNOWN     |UNKNOWN   |

I think this jives with what you are saying ... yes?

**Comment by jerstlouis** [comment]
@pvretano Yes, exactly what I believe it should be. See the [language in 6.2](https://docs.ogc.org/DRAFTS/21-065.html#basic-cql2_filter-expression) that seems to hint otherwise.
The _[Table 6](https://docs.ogc.org/DRAFTS/21-065.html#_conformance_test_9)_ in [A.3.6. Conformance Test 9](https://docs.ogc.org/DRAFTS/21-065.html#_conformance_test_9) also say otherwise.

**Comment by pvretano** [comment]
@jerstlouis read the first part of 6.2 and it seems to say ...

1. A CQL2 expression evaluates to TRUE, FALSE or NULL.
2. If the CQL2 expression evaluates to TRUE then the resource is part of the result set.
3. If the CQL2 expression evaluates to FALSE or NULL (i.e. unknown) then the resource is not part of the result set.

So basically, if the CQL2 is TRUE the resource/item is in the result set.  Otherwise it is not.  Seems OK ... no?

**Comment by jerstlouis** [comment]
@pvretano That's OK for the final evaluation of the result set.

> If a predicate evaluates to TRUE for an item, the item qualifies **for further processing** such as presentation in the result set, **being passed on to the next predicate in the filter for further evaluation**, and so forth.
> If the predicate evaluates to FALSE or NULL for an item, the item is **not available for further processing**.

That part is not OK to jive with those truth tables.

**Comment by pvretano** [comment]
Hmmm .... yeah, the wording may not be the best here.  Don't remember how I came up with the "...being passed on to the next predicate in the filter for further evaluation..." bit but that doesn't seem clear.  
I'll create a PR to clean this up and have it ready for discussion at the next SWG meeting.  I agree the TRUTH table in the specification would be helpful too.

**Comment by cportele** [comment]
I agree, such a change will help to clarify the requirements.

@jerstlouis - With respect to the test results, I think you are correct (at least for the first case, but since it is a systematic issue, I am sure the same is true for the other cases). It looks like we have an issue in the CQL2 to SQL conversion in our implementation. I will check all cases and update the ATS. Thanks!
