### ISSUE TITLE
Separation of templated and untemplated links ...

### ISSUE THREAD

**Issue by pvretano** [opengeospatial/ogcapi-features#844]
There is an issue of mixing templated and regular links in the same links section. Clients unaware of templaing will ignore the templated information and try to resolve the href with variables which will fail. This suggests that it might be worth considering splitting out the templated links from regular links.

This issue is cross-cutting and was motivated by a similar issue in Records. 

See here: opengeospatial/ogcapi-records#275 for a discussion on the issue in Record.

See also: https://github.com/opengeospatial/ogcapi-tiles/issues/159

**Comment by cportele** [comment]
Meeting 2023-07-31: Templated links are currently only in the Editor's Draft, not in any of the published specs. We wait for the discussion in Common / the Architecture DWG before considering to publish any new version of Part 1.
