### ISSUE TITLE
CQL2: conformance class for S_INTERSECTS for geometry, between Basic SO and SO classes

### ISSUE THREAD

**Issue by philvarner** [opengeospatial/ogcapi-features#859]
This comment is in the context of the Basic Spatial Operators being changed to only require support for S_INTERSECTS with bbox or Point, instead of also most other Geometry object. I think that's a good change to make the Basic Spatial Operators a simple to implement as possible, but it opens up a large gap between it and the Spatial Operators class. SO requires support for DE-9IM, which is much more difficult to implement, and in some cases, infeasible to implement if the backend database doesn't support those operators (as with Elasticsearch and OpenSearch). 

It would be nice if there were another spatial operators conformance class that has the same semantics as BSO perviously had, so that I can advertise that I support S_INTERSECTS with geometries, without having to "under advertise" I only support Basic, or be force to implement DE-9IM.

**Comment by cportele** [comment]
Meeting 2023-10-09: We agree. Keep the "new" Basic Spatial Operators class and bring back the previous Basic Spatial Operators class that supported S_INTERSECTS with any geometry as an intermediate Spatial Operators class (Intersects class, name to be determined).
