### ISSUE TITLE
CRS identifier required for geometry less collections

### ISSUE THREAD

**Issue by 3nids** [opengeospatial/ogcapi-features#866]
From https://github.com/opengeospatial/ogcapi-features/issues/765, geometry-less collections are allowed.

But the conformance tests are requiring a CRS identifier for the collection description.

How are we suppose to handle this?
Would there be a way to tell a collection doesn't have a geometry?

**Comment by cportele** [comment]
I do not see the conformance test that requires the "crs" member.

Test `/conf/core/fc-md-success`, item 3, states:

> In case the response includes a "crs" property, validate that the first value is either "http://www.opengis.net/def/crs/OGC/1.3/CRS84" or "http://www.opengis.net/def/crs/OGC/0/CRS84h".

Which conformance test is requiring "crs" in a collection?

**Comment by 3nids** [comment]
My bad, I thought it was my geometry less layers which were causing the failing test.

Here are the tests results:
![image](https://github.com/opengeospatial/ogcapi-features/assets/127259/a8f08ea5-7c92-4a83-bcf6-40d3702fcfef)

And here is what I have for the geometric collection:
![image](https://github.com/opengeospatial/ogcapi-features/assets/127259/5e44d521-3fd0-4cc6-9e81-154df2fdc559)

May I ask you to give an eye on this, if you see the problem...I'm a bit lost.
Cheers

**Comment by cportele** [comment]
@3nids - I do not see anything that is wrong related to CRSs - at least from a quick glance. This could be an issue in the CITE tests. Maybe open an issue in the repository of the tests: https://github.com/opengeospatial/ets-ogcapi-features10/issues.

What is incorrect though is `extent.tempora.interval`. If the value is present, there must be a non-null value that is an array of two values (datetime or null). But that probably does not trigger CRS-related errors. If there is no temporal extent, just don't include the "temporal" member.
