### ISSUE TITLE
CQL2 (Spatial Functions): Short definitions of boundary/interior/exterior, S_RELATE

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-features#869]
Regarding _Spatial Functions_ requirement class:

Although this is surely covered in detail in SFA, it would be great to summarize what is meant by Interior, Boundary and Exterior, as this is especially not obvious for LineStrings and Points:

**Polygons**

- Boundary: The rings
- Interior: Everything between the outer and inner rings
- Exterior: Everything else in the plane

**LineStrings**

- Boundary: The two extremity points
- Interior: The line segments within the two extremities
- Exterior: Everything else in the plane

**Points**

- Boundary: Empty set
- Interior: The point itself
- Exterior: Everything else in the plane

PostGIS has a great summary here: https://postgis.net/workshops/postgis-intro/de9im.html

It would be great to also include `S_RELATE()` / `S_RELATEMATCH()` which take a 9 character DE-9IM matrix string. All of the other functions can be described as a logical combinations of S_RELATE() checks (as detailed at https://en.wikipedia.org/wiki/DE-9IM#Spatial_predicates), and `S_RELATE` allows some additional specific checks as well.

If S_RELATE() is included, or even otherwise as background information, an explanation of DE-9IM Clementini Matrices would be very useful to the reader (as illustrated at https://postgis.net/workshops/postgis-intro/de9im.html and https://en.wikipedia.org/wiki/DE-9IM#Illustration).

For me, it is a lot easier to understand (and implement) each of the S_ functions as the logical OR combinations of DE-9IM matrices S_RelateMatch() than as the mathematical definition in the current Table 2 and the Figures immediately below, so I think it would be a great complementary addition.

**Comment by cportele** [comment]
Meeting 2023-12-18:

* Include the explanation about boundary/interior/exterior in the document.
* Include the definition of the spatial functions in terms of the relate match function matrices.
* Do not include S_RELATE() or S_RELATEMATCH() functions at this late stage. It would have to be in a separate requirements class.
* Add [DE-9IM](https://en.wikipedia.org/wiki/DE-9IM) in the bibliography and reference it from the section where we mention DE-9IM.

**Comment by cportele** [comment]
Code Sprint 2024-02-26: We should not repeat existing material, but simply add the PostGIS reference to the bibliography and add an explanatory note referencing the bibliography entry. Also add the DE-9IM reference.
