### ISSUE TITLE
CQL2 (Arrays): Remaining square brackets

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-features#871]
As a follow-up to #718 fixed in #784 , there are still some square brackets in the [latest generated draft in 7.8.1. Arrays and 7.8.3 Examples](https://docs.ogc.org/DRAFTS/21-065.html#_arrays):

> Example 18. Array examples
> arrays (Text)
> [ 'a', 'c' ]
> [ 'a', true, 1 ]
> [ DATE('1969-07-16'), DATE('1969-07-20'), DATE('1969-07-24') ]

https://docs.ogc.org/DRAFTS/21-065.html#_examples_3
> Example 19. Evaluate if the value of an array property contains the specified subset of values.
> A_CONTAINS(layer:ids, ["layers-ca","layers-us"])

**Comment by cportele** [comment]
Thanks @jerstlouis, I was already working on a PR to fix examples, so I added these changes in #873, too.
