### ISSUE TITLE
Schemas: QUDT -- URI or id ? Add an example?

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-features#909]
In the last Coverages Sprint we had discussed the Schemas units and were wondering whether QUDT would be specified as a unit or as a URI:

https://github.com/opengeospatial/ogcapi-coverages/issues/173#issuecomment-1941680959

I believe this is still not clearly communicated. It would be good to clarify that, and perhaps also add an example using QUDT to dispel any confusion. ( https://docs.ogc.org/DRAFTS/23-058.html#additional-keywords )

**Comment by cportele** [comment]
OK, so maybe we should also specify in `/req/schemas/unit` how to specify QUDT units like we do for UCUM.

**Comment by ghobona** [comment]
Please note that @nicholascar has advocated for QUDT at previous OGC-NA meetings.

**Comment by cportele** [comment]
Meeting 2024-04-22: Add the requirement and example. Include the full URI (e.g. "https://qudt.org/vocab/unit/HectoPA") as the value and "QUDT" as the value for `unitLang`.
