### ISSUE TITLE
Schemas: `x-ogc-unit-lang` or `x-ogc-unitLang` ?

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-features#910]
The suggestion to try to achieve consistency across the specs was to use kebab-case for query parameters, but camelCase for JSON schemas.

If the JSON Schema mechanism is to prefix with `x-ogc-` that is one thing, but for the rest of the identifier should we use camelCase?

The main reason I ask is because we also want to rely on the same concept of `x-ogc-definition`, `x-ogc-unit` and `x-ogc-unit-lang` as part of the uniform additional dimensions in the collection description extent where dimensions are listed for Coverages (and Maps / Tiles and more) where it now mainly replaces the CIS DomainSet, to define dimensions beyond spatial and temporal (e.g., pressure levels).

There we would not need to prefix it by `x-ogc-` so it would simply be `definition`, `unit` and `unitLang`.

**Comment by cportele** [comment]
Good point about the camelCase convention for JSON keys.

**Comment by jerstlouis** [comment]
This would also apply to `x-ogc-propertySeq`.

**Comment by cportele** [comment]
Meeting 2024-04-22: Change to camel case after "x-ogc-".
