### ISSUE TITLE
Schemas: Clarifications / Example on what URIs / vocabs should be used for `x-ogc-definition`

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-features#913]
It would be great to clarify / provide examples of what URIs should be used for properties / field definitions (`x-ogc-definition`).

I imagine we might want to support both OGC and non-OGC definitions?

Would there be multiple vocabulary options even within the OGC definitions?

Would there be a need to specify the vocabulary used here as well (as a separate property)?

Would be great to have something consistent here across Features / Connected Systems / Coverages / SensorThings / OMS...

Some example of things we would like to have example definitions for:

- Pressure level
- All of these measurements at https://maps.gnosis.earth/ogcapi/collections/climate:cmip5:singlePressure/schema?f=json
- What about more general vs. more specific things, for example temperature in general vs. temperature at sea level?

cc. @glennlaughlin @joanma747 @alexrobin

**Comment by cportele** [comment]
I agree that examples are useful. If you have some live examples, let us know or create a PR.

There are various registers or vocabularies that may be the source for such definitions. I do not think that we should limit the nature of the resources that this can point to. It is not the idea to restrict this to the OGC URIs.

So far, I did not see the need for a separate property identifying the vocabulary or register, the value is a URI. That resource can be investigated to find out more information including the vocabulary / register. (In SOSA, there is also just `observedProperty`, not another property that points to the vocabulary that contains the observed property.)

**Comment by jerstlouis** [comment]
@glennlaughlin As discussed, would be great if you could help us with these observed property examples from your awareness of OMS and related specs. Thanks!!

**Comment by jerstlouis** [comment]
Here is an example quantity definition from QUDT (shared by @ldesousa):

https://qudt.org/vocab/quantitykind/AtmosphericPressure

**Comment by cportele** [comment]
Meeting 2024-04-22: Add the QUDT example.
