### ISSUE TITLE
CQL2/Grammar: signedNumericLiteral does not seem to be defined correctly

### ISSUE THREAD

**Issue by jerstlouis** [opengeospatial/ogcapi-features#917]
The rule for `signedNumericLiteral` is:

```
signedNumericLiteral = [sign] exactNumericLiteral | approximateNumericLiteral;
```

From my understanding of how this EBNF should be interpreted, the `[sign]` would only apply to _exactNumericLiteral_, and this should be written instead as:

```
signedNumericLiteral =
   [sign] exactNumericLiteral |
   [sign] approximateNumericLiteral;
```

to allow for negative numbers using scientific notation.

On a related note, the choice of _exact_ vs. _approximate_ also strikes me as odd to identify the regular vs. scientific notation of floating point numbers, since floating point representations are never exact, and not anymore exact when using regular rather than scientific notation.

There is also a difficulty in incorporating the sign as part of the numeric literal, and we ended up having to do for the CartoSym-CSS grammar for ANTLR4 was to remove it (from the lexer numeric literal rule) and use a unary +/- operator that goes before the expression in the grammar. See:

https://github.com/opengeospatial/styles-and-symbology/blob/main/core/schemas/CartoSym-CSS-Lexer.g4#L52

https://github.com/opengeospatial/styles-and-symbology/blob/main/core/schemas/CartoSym-CSS-Grammar.g4#L63

EDIT: With the latest work on the CartoSym grammar, I'm realizing that it would be impossible to disembiguate an arithmetic subtraction from a tuple of coordinates with the second coordinate being negative inside a WKT point tuple. I haven't figured out how or whether this could be expressed in ANTLR4, which normally deals with context-free grammar only (though there are things like semantic predicates and modes that might be able to help with such context-specific cases). In our handwritten RD parser, we handle this special case based on whether we're parsing the inside of a WKT expression.

**Comment by cportele** [comment]
Meeting 2024-04-08: The syntax looks like a bug and needs to be fixed before publication. @pvretano - do you agree?

**Comment by cportele** [comment]
Meeting 2024-04-22:

* Yes, we will fix the rule.
* Yes, we will rename to "decimalNumericLiteral" and "scientificNumericLiteral.
