### ISSUE TITLE
Timeout when testing OGC API Features

### ISSUE THREAD

**Issue by fabiovinci** [opengeospatial/ogcapi-features#956]
It seems that there is a timeout issue with the Validator, specifically related to the OGC API - Features Test Suite.

The OGC validator fails to complete validation and the issue is impacting the INSPIRE Reference Validator which reuses the OGC test suite.

Related issue in the Validator-Helpdesk: [Timeout when testing OGC API Features](https://github.com/INSPIRE-MIF/helpdesk-validator/issues/1112)

Could you please check?

**Comment by cportele** [comment]
@fabiovinci - This repo is for the specification, not for the validator. I am, therefore, closing this issue here. 

@ghobona @dstenger - Could you have a look and point @fabiovinci where he should record his issue, since it is related to the CITE deployment, not the OGC API Features ETS?

**Comment by fabiovinci** [comment]
Dear @cportele,

since the other Test Suites appear to be working fine, I thought the issue was specific to this particular test suite.

Please point me to the correct repository to open this issue if you can't move it yourself.

**Comment by cportele** [comment]
@fabiovinci - If it is specific to the ETS, the repo is here: https://github.com/opengeospatial/ets-ogcapi-features10

**Comment by ghobona** [comment]
I will transfer the Issue over to the https://github.com/opengeospatial/ets-ogcapi-features10 repository.

Please note that @mbrachman is now responsible for CITE/Compliance testing and certification.
